// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class KnowledgeIssue {
  final String fingerprint;
  final String pageSlug;
  final String kind;
  final String description;

  const KnowledgeIssue({
    required this.fingerprint,
    required this.pageSlug,
    required this.kind,
    required this.description,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^
      pageSlug.hashCode ^
      kind.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeIssue &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          pageSlug == other.pageSlug &&
          kind == other.kind &&
          description == other.description;
}

class KnowledgeMetadata {
  final String applicableWhen;
  final String strength;
  final String? confirmedAt;

  const KnowledgeMetadata({
    required this.applicableWhen,
    required this.strength,
    this.confirmedAt,
  });

  @override
  int get hashCode =>
      applicableWhen.hashCode ^ strength.hashCode ^ confirmedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeMetadata &&
          runtimeType == other.runtimeType &&
          applicableWhen == other.applicableWhen &&
          strength == other.strength &&
          confirmedAt == other.confirmedAt;
}

class KnowledgeProposal {
  final String id;
  final String? pageId;
  final String targetSlug;
  final String kind;
  final String title;
  final String contentMd;
  final String applicableWhen;
  final List<String> snapshotIds;
  final List<String> eventIds;
  final String? baseHash;
  final String reason;
  final String status;
  final String createdAt;

  const KnowledgeProposal({
    required this.id,
    this.pageId,
    required this.targetSlug,
    required this.kind,
    required this.title,
    required this.contentMd,
    required this.applicableWhen,
    required this.snapshotIds,
    required this.eventIds,
    this.baseHash,
    required this.reason,
    required this.status,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pageId.hashCode ^
      targetSlug.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      contentMd.hashCode ^
      applicableWhen.hashCode ^
      snapshotIds.hashCode ^
      eventIds.hashCode ^
      baseHash.hashCode ^
      reason.hashCode ^
      status.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeProposal &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pageId == other.pageId &&
          targetSlug == other.targetSlug &&
          kind == other.kind &&
          title == other.title &&
          contentMd == other.contentMd &&
          applicableWhen == other.applicableWhen &&
          snapshotIds == other.snapshotIds &&
          eventIds == other.eventIds &&
          baseHash == other.baseHash &&
          reason == other.reason &&
          status == other.status &&
          createdAt == other.createdAt;
}

class SourceSnapshot {
  final String id;
  final String sourceId;
  final PlatformInt64 version;
  final String title;
  final String contentMd;
  final String contentHash;
  final String capturedAt;
  final String sourceKind;
  final String? locator;
  final String? opinion;
  final String? pageSlug;

  const SourceSnapshot({
    required this.id,
    required this.sourceId,
    required this.version,
    required this.title,
    required this.contentMd,
    required this.contentHash,
    required this.capturedAt,
    required this.sourceKind,
    this.locator,
    this.opinion,
    this.pageSlug,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sourceId.hashCode ^
      version.hashCode ^
      title.hashCode ^
      contentMd.hashCode ^
      contentHash.hashCode ^
      capturedAt.hashCode ^
      sourceKind.hashCode ^
      locator.hashCode ^
      opinion.hashCode ^
      pageSlug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceSnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sourceId == other.sourceId &&
          version == other.version &&
          title == other.title &&
          contentMd == other.contentMd &&
          contentHash == other.contentHash &&
          capturedAt == other.capturedAt &&
          sourceKind == other.sourceKind &&
          locator == other.locator &&
          opinion == other.opinion &&
          pageSlug == other.pageSlug;
}
