// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class KnowledgeReviewRecord {
  final String id;
  final String action;
  final String title;
  final String createdAt;
  final String? beforeContent;
  final String? originalContent;
  final String? resultContent;
  final String? originalApplicable;
  final String? resultApplicable;
  final Int64List selectedParts;
  final String description;
  final String? note;
  final String? revisionId;
  final String? targetSlug;

  const KnowledgeReviewRecord({
    required this.id,
    required this.action,
    required this.title,
    required this.createdAt,
    this.beforeContent,
    this.originalContent,
    this.resultContent,
    this.originalApplicable,
    this.resultApplicable,
    required this.selectedParts,
    required this.description,
    this.note,
    this.revisionId,
    this.targetSlug,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      action.hashCode ^
      title.hashCode ^
      createdAt.hashCode ^
      beforeContent.hashCode ^
      originalContent.hashCode ^
      resultContent.hashCode ^
      originalApplicable.hashCode ^
      resultApplicable.hashCode ^
      selectedParts.hashCode ^
      description.hashCode ^
      note.hashCode ^
      revisionId.hashCode ^
      targetSlug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeReviewRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          title == other.title &&
          createdAt == other.createdAt &&
          beforeContent == other.beforeContent &&
          originalContent == other.originalContent &&
          resultContent == other.resultContent &&
          originalApplicable == other.originalApplicable &&
          resultApplicable == other.resultApplicable &&
          selectedParts == other.selectedParts &&
          description == other.description &&
          note == other.note &&
          revisionId == other.revisionId &&
          targetSlug == other.targetSlug;
}
