// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class OrganizedTopic {
  final String title;
  final String contentMd;
  final String applicableWhen;
  final List<String> snapshotIds;
  final List<String> eventIds;

  const OrganizedTopic({
    required this.title,
    required this.contentMd,
    required this.applicableWhen,
    required this.snapshotIds,
    required this.eventIds,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      contentMd.hashCode ^
      applicableWhen.hashCode ^
      snapshotIds.hashCode ^
      eventIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OrganizedTopic &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          contentMd == other.contentMd &&
          applicableWhen == other.applicableWhen &&
          snapshotIds == other.snapshotIds &&
          eventIds == other.eventIds;
}

class TopicOrganizationPreview {
  final String id;
  final String mode;
  final List<String> inputSlugs;
  final List<OrganizedTopic> topics;
  final String status;

  const TopicOrganizationPreview({
    required this.id,
    required this.mode,
    required this.inputSlugs,
    required this.topics,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mode.hashCode ^
      inputSlugs.hashCode ^
      topics.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopicOrganizationPreview &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mode == other.mode &&
          inputSlugs == other.inputSlugs &&
          topics == other.topics &&
          status == other.status;
}
