// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class KnowledgeQueueItem {
  final String id;
  final String task;
  final String pageSlug;
  final String title;
  final String status;
  final String detail;
  final String? availableAt;

  const KnowledgeQueueItem({
    required this.id,
    required this.task,
    required this.pageSlug,
    required this.title,
    required this.status,
    required this.detail,
    this.availableAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      task.hashCode ^
      pageSlug.hashCode ^
      title.hashCode ^
      status.hashCode ^
      detail.hashCode ^
      availableAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeQueueItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          task == other.task &&
          pageSlug == other.pageSlug &&
          title == other.title &&
          status == other.status &&
          detail == other.detail &&
          availableAt == other.availableAt;
}

class KnowledgeQueuePage {
  final PlatformInt64 pending;
  final PlatformInt64 running;
  final PlatformInt64 waiting;
  final PlatformInt64 retry;
  final PlatformInt64 skipped;
  final PlatformInt64 completed;
  final PlatformInt64 total;
  final List<KnowledgeQueueItem> items;
  final bool hasMore;

  const KnowledgeQueuePage({
    required this.pending,
    required this.running,
    required this.waiting,
    required this.retry,
    required this.skipped,
    required this.completed,
    required this.total,
    required this.items,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      pending.hashCode ^
      running.hashCode ^
      waiting.hashCode ^
      retry.hashCode ^
      skipped.hashCode ^
      completed.hashCode ^
      total.hashCode ^
      items.hashCode ^
      hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeQueuePage &&
          runtimeType == other.runtimeType &&
          pending == other.pending &&
          running == other.running &&
          waiting == other.waiting &&
          retry == other.retry &&
          skipped == other.skipped &&
          completed == other.completed &&
          total == other.total &&
          items == other.items &&
          hasMore == other.hasMore;
}
