// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class KnowledgeDiffPart {
  final String before;
  final String after;
  final bool changed;

  const KnowledgeDiffPart({
    required this.before,
    required this.after,
    required this.changed,
  });

  @override
  int get hashCode => before.hashCode ^ after.hashCode ^ changed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeDiffPart &&
          runtimeType == other.runtimeType &&
          before == other.before &&
          after == other.after &&
          changed == other.changed;
}
