// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ArtifactVersion {
  final String slug;
  final String title;
  final String contentType;
  final PlatformInt64 version;
  final String? instruction;
  final String? model;
  final String? strategy;
  final String createdAt;
  final bool adopted;
  final String? adoptedRevision;

  const ArtifactVersion({
    required this.slug,
    required this.title,
    required this.contentType,
    required this.version,
    this.instruction,
    this.model,
    this.strategy,
    required this.createdAt,
    required this.adopted,
    this.adoptedRevision,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      title.hashCode ^
      contentType.hashCode ^
      version.hashCode ^
      instruction.hashCode ^
      model.hashCode ^
      strategy.hashCode ^
      createdAt.hashCode ^
      adopted.hashCode ^
      adoptedRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtifactVersion &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          title == other.title &&
          contentType == other.contentType &&
          version == other.version &&
          instruction == other.instruction &&
          model == other.model &&
          strategy == other.strategy &&
          createdAt == other.createdAt &&
          adopted == other.adopted &&
          adoptedRevision == other.adoptedRevision;
}

class LibraryEntry {
  final String slug;
  final String title;
  final String summary;
  final String kind;
  final String area;
  final String readingState;

  const LibraryEntry({
    required this.slug,
    required this.title,
    required this.summary,
    required this.kind,
    required this.area,
    required this.readingState,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      kind.hashCode ^
      area.hashCode ^
      readingState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryEntry &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          title == other.title &&
          summary == other.summary &&
          kind == other.kind &&
          area == other.area &&
          readingState == other.readingState;
}

class LibraryPage {
  final List<LibraryEntry> items;
  final bool hasMore;

  const LibraryPage({required this.items, required this.hasMore});

  @override
  int get hashCode => items.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LibraryPage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          hasMore == other.hasMore;
}

class SuggestionFeedback {
  final String decision;
  final String suggestion;
  final String? rewrite;
  final String createdAt;

  const SuggestionFeedback({
    required this.decision,
    required this.suggestion,
    this.rewrite,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      decision.hashCode ^
      suggestion.hashCode ^
      rewrite.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SuggestionFeedback &&
          runtimeType == other.runtimeType &&
          decision == other.decision &&
          suggestion == other.suggestion &&
          rewrite == other.rewrite &&
          createdAt == other.createdAt;
}
