// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<PendingActionDto>> listPendingActions({
  required String conversationId,
}) => RustLib.instance.api.crateApiConversationsListPendingActions(
  conversationId: conversationId,
);

Future<bool> updatePendingActionArgs({
  required String actionId,
  required String argsJson,
}) => RustLib.instance.api.crateApiConversationsUpdatePendingActionArgs(
  actionId: actionId,
  argsJson: argsJson,
);

/// 从对话中的草稿预览单独保存一张知识页，不确认同会话的其他动作。
Future<String> confirmKnowledgeDraft({
  required String conversationId,
  required String actionId,
}) => RustLib.instance.api.crateApiConversationsConfirmKnowledgeDraft(
  conversationId: conversationId,
  actionId: actionId,
);

/// 只拒绝这一篇待入库知识草稿，不删除已保存页面或其他待确认动作。
Future<void> declineKnowledgeDraft({
  required String conversationId,
  required String actionId,
}) => RustLib.instance.api.crateApiConversationsDeclineKnowledgeDraft(
  conversationId: conversationId,
  actionId: actionId,
);

/// Create a new conversation
Future<ConversationDto> createConversation({String? title, String? tag}) =>
    RustLib.instance.api.crateApiConversationsCreateConversation(
      title: title,
      tag: tag,
    );

/// List all non-archived conversations
Future<List<ConversationDto>> listConversations() =>
    RustLib.instance.api.crateApiConversationsListConversations();

/// List archived conversations
Future<List<ConversationDto>> listArchivedConversations() =>
    RustLib.instance.api.crateApiConversationsListArchivedConversations();

/// Rename a conversation
Future<void> renameConversation({
  required String conversationId,
  required String title,
}) => RustLib.instance.api.crateApiConversationsRenameConversation(
  conversationId: conversationId,
  title: title,
);

/// Archive or unarchive a conversation
Future<void> setConversationArchived({
  required String conversationId,
  required bool archived,
}) => RustLib.instance.api.crateApiConversationsSetConversationArchived(
  conversationId: conversationId,
  archived: archived,
);

/// Delete an archived ordinary conversation.
Future<bool> deleteArchivedConversation({required String conversationId}) =>
    RustLib.instance.api.crateApiConversationsDeleteArchivedConversation(
      conversationId: conversationId,
    );

/// Get a specific conversation
Future<ConversationDto?> getConversation({required String conversationId}) =>
    RustLib.instance.api.crateApiConversationsGetConversation(
      conversationId: conversationId,
    );

/// Send a message in a conversation
Future<MessageDto> sendMessage({
  required String conversationId,
  required String role,
  required String content,
  String? parentMessageId,
}) => RustLib.instance.api.crateApiConversationsSendMessage(
  conversationId: conversationId,
  role: role,
  content: content,
  parentMessageId: parentMessageId,
);

/// List messages in a conversation
Future<List<MessageDto>> listMessages({required String conversationId}) =>
    RustLib.instance.api.crateApiConversationsListMessages(
      conversationId: conversationId,
    );

/// Get child messages of a specific message (for branching conversations)
Future<List<MessageDto>> getChildMessages({required String parentId}) => RustLib
    .instance
    .api
    .crateApiConversationsGetChildMessages(parentId: parentId);

/// Get the message chain from root to a specific message
Future<List<MessageDto>> getMessageChain({required String messageId}) => RustLib
    .instance
    .api
    .crateApiConversationsGetMessageChain(messageId: messageId);

/// Generate AI reply for a conversation
Future<String> generateReply({
  required String conversationId,
  String? providerType,
  String? memoryType,
  int? memoryWindowSize,
}) => RustLib.instance.api.crateApiConversationsGenerateReply(
  conversationId: conversationId,
  providerType: providerType,
  memoryType: memoryType,
  memoryWindowSize: memoryWindowSize,
);

/// 获取最近 N 天的每日 token 用量统计（含当天，日期倒序）
Future<List<DailyTokenUsageDto>> getDailyTokenUsage({required int days}) =>
    RustLib.instance.api.crateApiConversationsGetDailyTokenUsage(days: days);

/// Conversation DTO for Flutter
class ConversationDto {
  final String id;
  final String? title;
  final String? tag;
  final String createdAt;
  final String updatedAt;
  final int messageCount;
  final String? lastMessagePreview;
  final bool archived;
  final String? wikiPageSlug;

  const ConversationDto({
    required this.id,
    this.title,
    this.tag,
    required this.createdAt,
    required this.updatedAt,
    required this.messageCount,
    this.lastMessagePreview,
    required this.archived,
    this.wikiPageSlug,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      tag.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      messageCount.hashCode ^
      lastMessagePreview.hashCode ^
      archived.hashCode ^
      wikiPageSlug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          tag == other.tag &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          messageCount == other.messageCount &&
          lastMessagePreview == other.lastMessagePreview &&
          archived == other.archived &&
          wikiPageSlug == other.wikiPageSlug;
}

/// Daily token usage DTO for Flutter（每日 token 使用统计）
class DailyTokenUsageDto {
  final String date;
  final PlatformInt64 promptTokens;
  final PlatformInt64 completionTokens;
  final PlatformInt64 totalTokens;
  final PlatformInt64 callCount;

  const DailyTokenUsageDto({
    required this.date,
    required this.promptTokens,
    required this.completionTokens,
    required this.totalTokens,
    required this.callCount,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      promptTokens.hashCode ^
      completionTokens.hashCode ^
      totalTokens.hashCode ^
      callCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyTokenUsageDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens &&
          callCount == other.callCount;
}

/// Message DTO for Flutter
class MessageDto {
  final String id;
  final String conversationId;
  final String? parentMessageId;
  final String role;
  final String content;
  final String createdAt;

  const MessageDto({
    required this.id,
    required this.conversationId,
    this.parentMessageId,
    required this.role,
    required this.content,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      parentMessageId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          parentMessageId == other.parentMessageId &&
          role == other.role &&
          content == other.content &&
          createdAt == other.createdAt;
}

class PendingActionDto {
  final String id;
  final String action;
  final String argsJson;
  final String createdAt;

  const PendingActionDto({
    required this.id,
    required this.action,
    required this.argsJson,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ action.hashCode ^ argsJson.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingActionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          argsJson == other.argsJson &&
          createdAt == other.createdAt;
}
