// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<EntityFactDto>> listEntityFacts({
  required String entityKind,
  required String entitySlug,
}) => RustLib.instance.api.crateApiEntitiesListEntityFacts(
  entityKind: entityKind,
  entitySlug: entitySlug,
);

Future<bool> deleteEntityFact({required String id}) =>
    RustLib.instance.api.crateApiEntitiesDeleteEntityFact(id: id);

Future<List<String>> listEntityAliases({
  required String entityKind,
  required String entitySlug,
}) => RustLib.instance.api.crateApiEntitiesListEntityAliases(
  entityKind: entityKind,
  entitySlug: entitySlug,
);

Future<void> addEntityAlias({
  required String entityKind,
  required String entitySlug,
  required String alias,
}) => RustLib.instance.api.crateApiEntitiesAddEntityAlias(
  entityKind: entityKind,
  entitySlug: entitySlug,
  alias: alias,
);

/// Merge two confirmed entities after explicit user confirmation.
Future<bool> mergeEntity({
  required String entityKind,
  required String sourceSlug,
  required String targetSlug,
}) => RustLib.instance.api.crateApiEntitiesMergeEntity(
  entityKind: entityKind,
  sourceSlug: sourceSlug,
  targetSlug: targetSlug,
);

Future<EntityMergeStatusDto?> getEntityMergeStatus({
  required String sourceSlug,
}) => RustLib.instance.api.crateApiEntitiesGetEntityMergeStatus(
  sourceSlug: sourceSlug,
);

/// Undo one merge only when every moved row still matches its merge snapshot.
Future<bool> undoEntityMerge({required String sourceSlug}) => RustLib
    .instance
    .api
    .crateApiEntitiesUndoEntityMerge(sourceSlug: sourceSlug);

class EntityMergeStatusDto {
  final String sourceSlug;
  final String targetSlug;
  final String entityKind;
  final String createdAt;

  const EntityMergeStatusDto({
    required this.sourceSlug,
    required this.targetSlug,
    required this.entityKind,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      sourceSlug.hashCode ^
      targetSlug.hashCode ^
      entityKind.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityMergeStatusDto &&
          runtimeType == other.runtimeType &&
          sourceSlug == other.sourceSlug &&
          targetSlug == other.targetSlug &&
          entityKind == other.entityKind &&
          createdAt == other.createdAt;
}
