// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 枚举系统字体（Linux/macOS/Windows；fontdb 直接扫描，不 spawn 外部命令）。
Future<List<SystemFontFace>> listSystemFonts() =>
    RustLib.instance.api.crateApiFontsListSystemFonts();

/// 一条系统字体字面。Dart 侧按家族去重、保留首选样式（Regular 优先）。
class SystemFontFace {
  final String family;
  final String file;
  final String style;

  const SystemFontFace({
    required this.family,
    required this.file,
    required this.style,
  });

  @override
  int get hashCode => family.hashCode ^ file.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemFontFace &&
          runtimeType == other.runtimeType &&
          family == other.family &&
          file == other.file &&
          style == other.style;
}
