// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_phase`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 列出全部活跃目标（最多 3 条，按近期→中期→长远排序）
Future<List<GoalDto>> listActiveGoals() =>
    RustLib.instance.api.crateApiGoalsListActiveGoals();

/// 列出已归档目标（历史，按归档时间倒序）
Future<List<GoalDto>> listArchivedGoals() =>
    RustLib.instance.api.crateApiGoalsListArchivedGoals();

/// 新建一条活跃目标
///
/// 活跃目标已满 3 条时拒绝并报错，界面须提示用户先归档一条，不得自动顶替既有目标。
Future<GoalDto> createGoal({required String content, required String phase}) =>
    RustLib.instance.api.crateApiGoalsCreateGoal(
      content: content,
      phase: phase,
    );

/// 编辑一条目标的正文与阶段（状态不变，故不受上限限制）
Future<void> updateGoal({
  required String id,
  required String content,
  required String phase,
}) => RustLib.instance.api.crateApiGoalsUpdateGoal(
  id: id,
  content: content,
  phase: phase,
);

/// 归档一条目标，让出活跃名额但保留内容与阶段作为历史
Future<void> archiveGoal({required String id}) =>
    RustLib.instance.api.crateApiGoalsArchiveGoal(id: id);

/// 复活一条已归档目标。活跃目标已满 3 条时同样拒绝。
Future<void> reactivateGoal({required String id}) =>
    RustLib.instance.api.crateApiGoalsReactivateGoal(id: id);

/// 目标 DTO
class GoalDto {
  final String id;
  final String content;

  /// near / mid / long
  final String phase;

  /// active / superseded
  final String status;
  final String createdAt;
  final String updatedAt;
  final String? supersededAt;

  const GoalDto({
    required this.id,
    required this.content,
    required this.phase,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
    this.supersededAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      phase.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      supersededAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GoalDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          phase == other.phase &&
          status == other.status &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          supersededAt == other.supersededAt;
}
