// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'wiki.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 抓取任意 URL 的内容（推文走 fxtwitter，普通页面走 HTML 文本提取）。
/// 只解析不写库，由后续「保存」动作决定。
Future<ImportUrlDto> fetchImportUrl({required String url}) =>
    RustLib.instance.api.crateApiImportFetchImportUrl(url: url);

/// 把抓取到的 URL 内容保存为知识库页面（kind=source，带 source_url 溯源）。
/// 用户点击「保存」才走这里入库。
Future<WikiPageDto> saveImportedPage({
  required String title,
  required String contentMd,
  required String sourceUrl,
  required String sourceKind,
  required List<String> tags,
}) => RustLib.instance.api.crateApiImportSaveImportedPage(
  title: title,
  contentMd: contentMd,
  sourceUrl: sourceUrl,
  sourceKind: sourceKind,
  tags: tags,
);

/// 任意 URL 抓取结果 DTO（推文或普通页面，只解析不入库）
class ImportUrlDto {
  final String sourceUrl;

  /// "tweet" | "webpage"
  final String sourceKind;
  final String? title;
  final String contentMd;
  final String? authorName;
  final String? screenName;

  const ImportUrlDto({
    required this.sourceUrl,
    required this.sourceKind,
    this.title,
    required this.contentMd,
    this.authorName,
    this.screenName,
  });

  @override
  int get hashCode =>
      sourceUrl.hashCode ^
      sourceKind.hashCode ^
      title.hashCode ^
      contentMd.hashCode ^
      authorName.hashCode ^
      screenName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportUrlDto &&
          runtimeType == other.runtimeType &&
          sourceUrl == other.sourceUrl &&
          sourceKind == other.sourceKind &&
          title == other.title &&
          contentMd == other.contentMd &&
          authorName == other.authorName &&
          screenName == other.screenName;
}
