// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../knowledge.dart';
import '../knowledge/maintenance.dart';
import '../knowledge/organization.dart';
import '../knowledge/queue.dart';
import '../knowledge/review.dart';
import '../storage/knowledge.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'wiki.dart';

// These functions are ignored because they are not marked as `pub`: `store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<List<KnowledgeRepairSource>> listKnowledgeRepairSources({
  required String slug,
}) => RustLib.instance.api.crateApiKnowledgeListKnowledgeRepairSources(
  slug: slug,
);

Future<String> prepareKnowledgeSourceRepair({
  required String slug,
  required List<String> snapshotIds,
}) => RustLib.instance.api.crateApiKnowledgePrepareKnowledgeSourceRepair(
  slug: slug,
  snapshotIds: snapshotIds,
);

Future<List<WikiPageDto>> listKnowledgeResolutionTargets({
  required String fingerprint,
}) => RustLib.instance.api.crateApiKnowledgeListKnowledgeResolutionTargets(
  fingerprint: fingerprint,
);

Future<void> resolveKnowledgeIssueWithRevision({
  required String fingerprint,
  required String slug,
  required String revisionId,
  required String note,
}) => RustLib.instance.api.crateApiKnowledgeResolveKnowledgeIssueWithRevision(
  fingerprint: fingerprint,
  slug: slug,
  revisionId: revisionId,
  note: note,
);

Future<List<KnowledgeReviewRecord>> listKnowledgeReviewHistory({
  required String slug,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiKnowledgeListKnowledgeReviewHistory(
  slug: slug,
  offset: offset,
);

Future<KnowledgeQueuePage> listKnowledgeWorkQueue({
  required PlatformInt64 offset,
  String? status,
}) => RustLib.instance.api.crateApiKnowledgeListKnowledgeWorkQueue(
  offset: offset,
  status: status,
);

Future<String> prepareTopicOrganization({
  required List<String> slugs,
  required String mode,
}) => RustLib.instance.api.crateApiKnowledgePrepareTopicOrganization(
  slugs: slugs,
  mode: mode,
);

Future<List<TopicOrganizationPreview>> listTopicOrganizations({
  required String slug,
}) => RustLib.instance.api.crateApiKnowledgeListTopicOrganizations(slug: slug);

Future<List<String>> resolveTopicOrganization({
  required String id,
  required bool accept,
}) => RustLib.instance.api.crateApiKnowledgeResolveTopicOrganization(
  id: id,
  accept: accept,
);

/// Background worker only; no manual insight trigger in the UI.
Future<PlatformInt64> tickKnowledgeInsights() =>
    RustLib.instance.api.crateApiKnowledgeTickKnowledgeInsights();

Future<List<KnowledgeBackgroundRunDto>> listKnowledgeBackgroundRuns() =>
    RustLib.instance.api.crateApiKnowledgeListKnowledgeBackgroundRuns();

Future<KnowledgePageDetails> getKnowledgePageDetails({required String slug}) =>
    RustLib.instance.api.crateApiKnowledgeGetKnowledgePageDetails(slug: slug);

Future<SourceSnapshot?> getKnowledgeSourceSnapshot({required String id}) =>
    RustLib.instance.api.crateApiKnowledgeGetKnowledgeSourceSnapshot(id: id);

Future<List<KnowledgeProposal>> listKnowledgeProposals() =>
    RustLib.instance.api.crateApiKnowledgeListKnowledgeProposals();

Future<List<KnowledgeIssue>> listKnowledgeIssues() =>
    RustLib.instance.api.crateApiKnowledgeListKnowledgeIssues();

Future<String> proposeKnowledgePage({
  required String slug,
  required String kind,
}) => RustLib.instance.api.crateApiKnowledgeProposeKnowledgePage(
  slug: slug,
  kind: kind,
);

Future<WikiPageDto?> resolveKnowledgeProposal({
  required String id,
  required bool accept,
}) => RustLib.instance.api.crateApiKnowledgeResolveKnowledgeProposal(
  id: id,
  accept: accept,
);

Future<void> updateKnowledgeMetadata({
  required String slug,
  required String applicableWhen,
  required String strength,
}) => RustLib.instance.api.crateApiKnowledgeUpdateKnowledgeMetadata(
  slug: slug,
  applicableWhen: applicableWhen,
  strength: strength,
);

Future<void> dismissKnowledgeIssue({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiKnowledgeDismissKnowledgeIssue(fingerprint: fingerprint);

Future<List<KnowledgeRevisionDto>> listKnowledgeRevisions({
  required String slug,
}) => RustLib.instance.api.crateApiKnowledgeListKnowledgeRevisions(slug: slug);

Future<List<KnowledgeDiffPart>> getKnowledgeProposalDiff({
  required String id,
}) => RustLib.instance.api.crateApiKnowledgeGetKnowledgeProposalDiff(id: id);

Future<WikiPageDto> acceptKnowledgeProposalParts({
  required String id,
  required Int64List selectedParts,
  required bool acceptApplicability,
  required List<String> resolvedIssues,
}) => RustLib.instance.api.crateApiKnowledgeAcceptKnowledgeProposalParts(
  id: id,
  selectedParts: selectedParts,
  acceptApplicability: acceptApplicability,
  resolvedIssues: resolvedIssues,
);

Future<String> prepareKnowledgeRestore({
  required String slug,
  required String revisionId,
}) => RustLib.instance.api.crateApiKnowledgePrepareKnowledgeRestore(
  slug: slug,
  revisionId: revisionId,
);

Future<List<KnowledgeCitation>> getKnowledgeCitations({
  required String task,
  required String ownerId,
}) => RustLib.instance.api.crateApiKnowledgeGetKnowledgeCitations(
  task: task,
  ownerId: ownerId,
);

Future<List<KnowledgeCitation>> getMessageKnowledgeCitations({
  required String messageId,
}) => RustLib.instance.api.crateApiKnowledgeGetMessageKnowledgeCitations(
  messageId: messageId,
);

Future<SourceUpdatePreview> previewKnowledgeSource({
  required String sourceUrl,
  required String contentMd,
}) => RustLib.instance.api.crateApiKnowledgePreviewKnowledgeSource(
  sourceUrl: sourceUrl,
  contentMd: contentMd,
);

/// Save the exact preview only if its base snapshot is still current.
Future<WikiPageDto> confirmKnowledgeSource({
  required String title,
  required String contentMd,
  required String sourceUrl,
  required String sourceKind,
  required List<String> tags,
  String? expectedSnapshotId,
}) => RustLib.instance.api.crateApiKnowledgeConfirmKnowledgeSource(
  title: title,
  contentMd: contentMd,
  sourceUrl: sourceUrl,
  sourceKind: sourceKind,
  tags: tags,
  expectedSnapshotId: expectedSnapshotId,
);

class KnowledgeBackgroundRunDto {
  final String task;
  final String status;
  final String startedAt;
  final String? finishedAt;
  final String? error;
  final PlatformInt64 resultCount;
  final String? sourceSlug;
  final String? sourceTitle;
  final PlatformInt64? sourceVersion;
  final String? detail;
  final String? retryAt;
  final String strategyVersion;

  const KnowledgeBackgroundRunDto({
    required this.task,
    required this.status,
    required this.startedAt,
    this.finishedAt,
    this.error,
    required this.resultCount,
    this.sourceSlug,
    this.sourceTitle,
    this.sourceVersion,
    this.detail,
    this.retryAt,
    required this.strategyVersion,
  });

  @override
  int get hashCode =>
      task.hashCode ^
      status.hashCode ^
      startedAt.hashCode ^
      finishedAt.hashCode ^
      error.hashCode ^
      resultCount.hashCode ^
      sourceSlug.hashCode ^
      sourceTitle.hashCode ^
      sourceVersion.hashCode ^
      detail.hashCode ^
      retryAt.hashCode ^
      strategyVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeBackgroundRunDto &&
          runtimeType == other.runtimeType &&
          task == other.task &&
          status == other.status &&
          startedAt == other.startedAt &&
          finishedAt == other.finishedAt &&
          error == other.error &&
          resultCount == other.resultCount &&
          sourceSlug == other.sourceSlug &&
          sourceTitle == other.sourceTitle &&
          sourceVersion == other.sourceVersion &&
          detail == other.detail &&
          retryAt == other.retryAt &&
          strategyVersion == other.strategyVersion;
}

class KnowledgePageDetails {
  final List<WikiPageDto> sourcePages;
  final List<WikiPageDto> outputPages;
  final List<SourceSnapshot> sources;
  final List<SourceSnapshot> history;
  final List<KnowledgeProposal> proposals;
  final List<KnowledgeIssue> issues;
  final KnowledgeMetadata metadata;

  const KnowledgePageDetails({
    required this.sourcePages,
    required this.outputPages,
    required this.sources,
    required this.history,
    required this.proposals,
    required this.issues,
    required this.metadata,
  });

  @override
  int get hashCode =>
      sourcePages.hashCode ^
      outputPages.hashCode ^
      sources.hashCode ^
      history.hashCode ^
      proposals.hashCode ^
      issues.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgePageDetails &&
          runtimeType == other.runtimeType &&
          sourcePages == other.sourcePages &&
          outputPages == other.outputPages &&
          sources == other.sources &&
          history == other.history &&
          proposals == other.proposals &&
          issues == other.issues &&
          metadata == other.metadata;
}

class KnowledgeRepairSource {
  final String snapshotId;
  final String? pageSlug;
  final String title;
  final PlatformInt64 version;
  final bool selected;
  final bool eligible;

  const KnowledgeRepairSource({
    required this.snapshotId,
    this.pageSlug,
    required this.title,
    required this.version,
    required this.selected,
    required this.eligible,
  });

  @override
  int get hashCode =>
      snapshotId.hashCode ^
      pageSlug.hashCode ^
      title.hashCode ^
      version.hashCode ^
      selected.hashCode ^
      eligible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeRepairSource &&
          runtimeType == other.runtimeType &&
          snapshotId == other.snapshotId &&
          pageSlug == other.pageSlug &&
          title == other.title &&
          version == other.version &&
          selected == other.selected &&
          eligible == other.eligible;
}

class KnowledgeRevisionDto {
  final String id;
  final String contentMd;
  final String reason;
  final String createdAt;

  const KnowledgeRevisionDto({
    required this.id,
    required this.contentMd,
    required this.reason,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ contentMd.hashCode ^ reason.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeRevisionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          contentMd == other.contentMd &&
          reason == other.reason &&
          createdAt == other.createdAt;
}

class SourceUpdatePreview {
  final String? existingSlug;
  final String? previousContent;
  final String? previousSnapshotId;
  final bool changed;

  const SourceUpdatePreview({
    this.existingSlug,
    this.previousContent,
    this.previousSnapshotId,
    required this.changed,
  });

  @override
  int get hashCode =>
      existingSlug.hashCode ^
      previousContent.hashCode ^
      previousSnapshotId.hashCode ^
      changed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceUpdatePreview &&
          runtimeType == other.runtimeType &&
          existingSlug == other.existingSlug &&
          previousContent == other.previousContent &&
          previousSnapshotId == other.previousSnapshotId &&
          changed == other.changed;
}
