// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../knowledge.dart';
import '../storage/knowledge.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'wiki.dart';

// These functions are ignored because they are not marked as `pub`: `store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Background worker only; no manual insight trigger in the UI.
Future<PlatformInt64> tickKnowledgeInsights() =>
    RustLib.instance.api.crateApiKnowledgeTickKnowledgeInsights();

Future<List<KnowledgeBackgroundRunDto>> listKnowledgeBackgroundRuns() =>
    RustLib.instance.api.crateApiKnowledgeListKnowledgeBackgroundRuns();

Future<KnowledgePageDetails> getKnowledgePageDetails({required String slug}) =>
    RustLib.instance.api.crateApiKnowledgeGetKnowledgePageDetails(slug: slug);

Future<SourceSnapshot?> getKnowledgeSourceSnapshot({required String id}) =>
    RustLib.instance.api.crateApiKnowledgeGetKnowledgeSourceSnapshot(id: id);

Future<List<KnowledgeProposal>> listKnowledgeProposals() =>
    RustLib.instance.api.crateApiKnowledgeListKnowledgeProposals();

Future<List<KnowledgeIssue>> listKnowledgeIssues() =>
    RustLib.instance.api.crateApiKnowledgeListKnowledgeIssues();

Future<String> proposeKnowledgePage({
  required String slug,
  required String kind,
}) => RustLib.instance.api.crateApiKnowledgeProposeKnowledgePage(
  slug: slug,
  kind: kind,
);

Future<WikiPageDto?> resolveKnowledgeProposal({
  required String id,
  required bool accept,
}) => RustLib.instance.api.crateApiKnowledgeResolveKnowledgeProposal(
  id: id,
  accept: accept,
);

Future<void> updateKnowledgeMetadata({
  required String slug,
  required String applicableWhen,
  required String strength,
}) => RustLib.instance.api.crateApiKnowledgeUpdateKnowledgeMetadata(
  slug: slug,
  applicableWhen: applicableWhen,
  strength: strength,
);

Future<void> dismissKnowledgeIssue({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiKnowledgeDismissKnowledgeIssue(fingerprint: fingerprint);

Future<List<KnowledgeRevisionDto>> listKnowledgeRevisions({
  required String slug,
}) => RustLib.instance.api.crateApiKnowledgeListKnowledgeRevisions(slug: slug);

Future<List<KnowledgeCitation>> getKnowledgeCitations({
  required String task,
  required String ownerId,
}) => RustLib.instance.api.crateApiKnowledgeGetKnowledgeCitations(
  task: task,
  ownerId: ownerId,
);

Future<List<KnowledgeCitation>> getMessageKnowledgeCitations({
  required String messageId,
}) => RustLib.instance.api.crateApiKnowledgeGetMessageKnowledgeCitations(
  messageId: messageId,
);

Future<SourceUpdatePreview> previewKnowledgeSource({
  required String sourceUrl,
  required String contentMd,
}) => RustLib.instance.api.crateApiKnowledgePreviewKnowledgeSource(
  sourceUrl: sourceUrl,
  contentMd: contentMd,
);

/// Save the exact preview only if its base snapshot is still current.
Future<WikiPageDto> confirmKnowledgeSource({
  required String title,
  required String contentMd,
  required String sourceUrl,
  required String sourceKind,
  required List<String> tags,
  String? expectedSnapshotId,
}) => RustLib.instance.api.crateApiKnowledgeConfirmKnowledgeSource(
  title: title,
  contentMd: contentMd,
  sourceUrl: sourceUrl,
  sourceKind: sourceKind,
  tags: tags,
  expectedSnapshotId: expectedSnapshotId,
);

class KnowledgeBackgroundRunDto {
  final String status;
  final String startedAt;
  final String? finishedAt;
  final String? error;
  final PlatformInt64 resultCount;

  const KnowledgeBackgroundRunDto({
    required this.status,
    required this.startedAt,
    this.finishedAt,
    this.error,
    required this.resultCount,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      startedAt.hashCode ^
      finishedAt.hashCode ^
      error.hashCode ^
      resultCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeBackgroundRunDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          startedAt == other.startedAt &&
          finishedAt == other.finishedAt &&
          error == other.error &&
          resultCount == other.resultCount;
}

class KnowledgePageDetails {
  final List<SourceSnapshot> sources;
  final List<SourceSnapshot> history;
  final List<KnowledgeProposal> proposals;
  final List<KnowledgeIssue> issues;
  final KnowledgeMetadata metadata;

  const KnowledgePageDetails({
    required this.sources,
    required this.history,
    required this.proposals,
    required this.issues,
    required this.metadata,
  });

  @override
  int get hashCode =>
      sources.hashCode ^
      history.hashCode ^
      proposals.hashCode ^
      issues.hashCode ^
      metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgePageDetails &&
          runtimeType == other.runtimeType &&
          sources == other.sources &&
          history == other.history &&
          proposals == other.proposals &&
          issues == other.issues &&
          metadata == other.metadata;
}

class KnowledgeRevisionDto {
  final String contentMd;
  final String reason;
  final String createdAt;

  const KnowledgeRevisionDto({
    required this.contentMd,
    required this.reason,
    required this.createdAt,
  });

  @override
  int get hashCode => contentMd.hashCode ^ reason.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeRevisionDto &&
          runtimeType == other.runtimeType &&
          contentMd == other.contentMd &&
          reason == other.reason &&
          createdAt == other.createdAt;
}

class SourceUpdatePreview {
  final String? existingSlug;
  final String? previousContent;
  final String? previousSnapshotId;
  final bool changed;

  const SourceUpdatePreview({
    this.existingSlug,
    this.previousContent,
    this.previousSnapshotId,
    required this.changed,
  });

  @override
  int get hashCode =>
      existingSlug.hashCode ^
      previousContent.hashCode ^
      previousSnapshotId.hashCode ^
      changed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceUpdatePreview &&
          runtimeType == other.runtimeType &&
          existingSlug == other.existingSlug &&
          previousContent == other.previousContent &&
          previousSnapshotId == other.previousSnapshotId &&
          changed == other.changed;
}
