// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../knowledge/organization.dart';
import '../knowledge/workflows.dart';
import 'knowledge.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'wiki.dart';

// These functions are ignored because they are not marked as `pub`: `store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<LibraryPage> browseKnowledge({
  required String query,
  String? area,
  String? kind,
  String? tag,
  String? state,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsBrowseKnowledge(
  query: query,
  area: area,
  kind: kind,
  tag: tag,
  state: state,
  offset: offset,
);

Future<String> knowledgeReadingState({required String slug}) => RustLib
    .instance
    .api
    .crateApiKnowledgeWorkflowsKnowledgeReadingState(slug: slug);

Future<void> setKnowledgeReadingState({
  required String slug,
  required String state,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsSetKnowledgeReadingState(
  slug: slug,
  state: state,
);

Future<List<ArtifactVersion>> listArtifactVersions({
  required String slug,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsListArtifactVersions(
  slug: slug,
  offset: offset,
);

Future<void> adoptArtifactVersion({
  required String slug,
  required String revisionId,
  required bool adopt,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsAdoptArtifactVersion(
  slug: slug,
  revisionId: revisionId,
  adopt: adopt,
);

Future<List<TopicOrganizationPreview>> topicOrganizationHistory({
  required String slug,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsTopicOrganizationHistory(
  slug: slug,
  offset: offset,
);

Future<void> undoTopicOrganization({required String id}) => RustLib.instance.api
    .crateApiKnowledgeWorkflowsUndoTopicOrganization(id: id);

Future<SuggestionFeedback?> getSuggestionFeedback({
  required String messageId,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsGetSuggestionFeedback(
  messageId: messageId,
);

Future<void> saveSuggestionFeedback({
  required String messageId,
  required String decision,
  required String suggestion,
  String? rewrite,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsSaveSuggestionFeedback(
  messageId: messageId,
  decision: decision,
  suggestion: suggestion,
  rewrite: rewrite,
);

Future<WikiPageDto> createArtifactFromMessage({
  required String slug,
  required String messageId,
  required String contentType,
  required String title,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsCreateArtifactFromMessage(
  slug: slug,
  messageId: messageId,
  contentType: contentType,
  title: title,
);

Future<List<BatchReviewResult>> resolveKnowledgeBatch({
  required List<String> ids,
  required bool accept,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsResolveKnowledgeBatch(
  ids: ids,
  accept: accept,
);

/// Load exactly the revision displayed in a comparison; id and body come from
/// one SQLite read, so a concurrent edit cannot pair old prose with a new id.
Future<KnowledgeRevisionDto> readArtifactVersion({
  required String slug,
  String? revisionId,
}) => RustLib.instance.api.crateApiKnowledgeWorkflowsReadArtifactVersion(
  slug: slug,
  revisionId: revisionId,
);

class BatchReviewResult {
  final String id;
  final bool success;
  final String detail;

  const BatchReviewResult({
    required this.id,
    required this.success,
    required this.detail,
  });

  @override
  int get hashCode => id.hashCode ^ success.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchReviewResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          success == other.success &&
          detail == other.detail;
}
