// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'knowledge_digest.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// 后台 worker 调用：处理一批到期的知识消化任务（最多一批，调用方循环排空）。
Future<KnowledgeDigestTickResult> triggerKnowledgeDigest() =>
    RustLib.instance.api.crateApiKnowledgeDigestTriggerKnowledgeDigest();

Future<KnowledgeDigestStatsDto> getKnowledgeDigestStats() =>
    RustLib.instance.api.crateApiKnowledgeDigestGetKnowledgeDigestStats();

/// 队列明细（只读）。`status` 为 None 时返回全部状态，按最近更新倒序。
Future<List<KnowledgeDigestJobDto>> listKnowledgeDigestJobs({
  String? status,
  required int limit,
}) => RustLib.instance.api.crateApiKnowledgeDigestListKnowledgeDigestJobs(
  status: status,
  limit: limit,
);

/// 最近的运行日志（只读），按开始时间倒序。
Future<List<KnowledgeDigestRunDto>> listKnowledgeDigestRuns({
  required int limit,
}) => RustLib.instance.api.crateApiKnowledgeDigestListKnowledgeDigestRuns(
  limit: limit,
);

class KnowledgeDigestJobDto {
  final String jobId;
  final String eventId;
  final String eventExcerpt;
  final String recordedAt;
  final String status;
  final PlatformInt64 attempts;
  final PlatformInt64 failedRounds;
  final String availableAt;
  final String? lastError;
  final String? skipReason;
  final String? batchId;
  final String updatedAt;

  const KnowledgeDigestJobDto({
    required this.jobId,
    required this.eventId,
    required this.eventExcerpt,
    required this.recordedAt,
    required this.status,
    required this.attempts,
    required this.failedRounds,
    required this.availableAt,
    this.lastError,
    this.skipReason,
    this.batchId,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      jobId.hashCode ^
      eventId.hashCode ^
      eventExcerpt.hashCode ^
      recordedAt.hashCode ^
      status.hashCode ^
      attempts.hashCode ^
      failedRounds.hashCode ^
      availableAt.hashCode ^
      lastError.hashCode ^
      skipReason.hashCode ^
      batchId.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeDigestJobDto &&
          runtimeType == other.runtimeType &&
          jobId == other.jobId &&
          eventId == other.eventId &&
          eventExcerpt == other.eventExcerpt &&
          recordedAt == other.recordedAt &&
          status == other.status &&
          attempts == other.attempts &&
          failedRounds == other.failedRounds &&
          availableAt == other.availableAt &&
          lastError == other.lastError &&
          skipReason == other.skipReason &&
          batchId == other.batchId &&
          updatedAt == other.updatedAt;
}

class KnowledgeDigestRunDto {
  final String id;
  final String startedAt;
  final String? finishedAt;
  final String status;
  final PlatformInt64 eventCount;
  final String? model;
  final PlatformInt64? durationMs;
  final List<String> createdSlugs;
  final List<String> updatedSlugs;
  final List<String> protectedSlugs;
  final String? error;

  const KnowledgeDigestRunDto({
    required this.id,
    required this.startedAt,
    this.finishedAt,
    required this.status,
    required this.eventCount,
    this.model,
    this.durationMs,
    required this.createdSlugs,
    required this.updatedSlugs,
    required this.protectedSlugs,
    this.error,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      startedAt.hashCode ^
      finishedAt.hashCode ^
      status.hashCode ^
      eventCount.hashCode ^
      model.hashCode ^
      durationMs.hashCode ^
      createdSlugs.hashCode ^
      updatedSlugs.hashCode ^
      protectedSlugs.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeDigestRunDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          startedAt == other.startedAt &&
          finishedAt == other.finishedAt &&
          status == other.status &&
          eventCount == other.eventCount &&
          model == other.model &&
          durationMs == other.durationMs &&
          createdSlugs == other.createdSlugs &&
          updatedSlugs == other.updatedSlugs &&
          protectedSlugs == other.protectedSlugs &&
          error == other.error;
}

class KnowledgeDigestStatsDto {
  final PlatformInt64 pending;
  final PlatformInt64 running;
  final PlatformInt64 retry;
  final PlatformInt64 succeeded;
  final PlatformInt64 failed;
  final PlatformInt64 skipped;
  final String? lastSuccessAt;
  final String? lastError;
  final String? lastErrorAt;

  const KnowledgeDigestStatsDto({
    required this.pending,
    required this.running,
    required this.retry,
    required this.succeeded,
    required this.failed,
    required this.skipped,
    this.lastSuccessAt,
    this.lastError,
    this.lastErrorAt,
  });

  @override
  int get hashCode =>
      pending.hashCode ^
      running.hashCode ^
      retry.hashCode ^
      succeeded.hashCode ^
      failed.hashCode ^
      skipped.hashCode ^
      lastSuccessAt.hashCode ^
      lastError.hashCode ^
      lastErrorAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KnowledgeDigestStatsDto &&
          runtimeType == other.runtimeType &&
          pending == other.pending &&
          running == other.running &&
          retry == other.retry &&
          succeeded == other.succeeded &&
          failed == other.failed &&
          skipped == other.skipped &&
          lastSuccessAt == other.lastSuccessAt &&
          lastError == other.lastError &&
          lastErrorAt == other.lastErrorAt;
}

@freezed
sealed class KnowledgeDigestTickResult with _$KnowledgeDigestTickResult {
  const KnowledgeDigestTickResult._();

  /// 尚未配置 AI provider：事件照常保存，任务等待
  const factory KnowledgeDigestTickResult.noProvider() =
      KnowledgeDigestTickResult_NoProvider;

  /// 没有到期可消化的事件
  const factory KnowledgeDigestTickResult.idle() =
      KnowledgeDigestTickResult_Idle;

  /// 一批事件消化成功（字段名避开 C 保留字：FFI 结构体里 `protected` 会被改名）
  const factory KnowledgeDigestTickResult.processed({
    required PlatformInt64 events,
    required List<String> createdSlugs,
    required List<String> updatedSlugs,
    required List<String> protectedSlugs,
  }) = KnowledgeDigestTickResult_Processed;

  /// 本批失败，已退避回队（原因见运行日志）
  const factory KnowledgeDigestTickResult.failed({
    required PlatformInt64 events,
    required String error,
  }) = KnowledgeDigestTickResult_Failed;
}
