// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto_from_active`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Get active AI provider info
Future<String?> getAiProvider() =>
    RustLib.instance.api.crateApiProviderConfigGetAiProvider();

/// Get the active AI provider full config (for settings page prefill)
Future<AiProviderConfigDto?> getAiProviderConfig() =>
    RustLib.instance.api.crateApiProviderConfigGetAiProviderConfig();

/// 列出全部 AI provider 配置（多配置，仅一个 is_active=true）
Future<List<AiProviderConfigDto>> listAiProviderConfigs() =>
    RustLib.instance.api.crateApiProviderConfigListAiProviderConfigs();

/// 新增或编辑 AI provider 配置；返回配置 id。
/// provider.id 为空表示新建；api_key 传空串表示保留原 key 不变（新建则必填）。
Future<String> saveAiProviderConfig({required AiProviderConfigDto provider}) =>
    RustLib.instance.api.crateApiProviderConfigSaveAiProviderConfig(
      provider: provider,
    );

/// 将指定配置设为激活（唯一激活项）
Future<void> setActiveAiProviderConfig({required String id}) => RustLib
    .instance
    .api
    .crateApiProviderConfigSetActiveAiProviderConfig(id: id);

/// 删除一个 AI provider 配置；若删除的是激活项，剩余第一条自动激活
Future<void> deleteAiProviderConfig({required String id}) =>
    RustLib.instance.api.crateApiProviderConfigDeleteAiProviderConfig(id: id);

/// Upsert the active AI provider config (settings page save)
Future<void> updateAiProviderConfig({
  required String baseUrl,
  required String model,
  required String apiKey,
}) => RustLib.instance.api.crateApiProviderConfigUpdateAiProviderConfig(
  baseUrl: baseUrl,
  model: model,
  apiKey: apiKey,
);

/// AI provider config DTO for Flutter settings page
class AiProviderConfigDto {
  final String id;
  final String name;
  final String providerType;
  final String baseUrl;
  final String model;
  final String apiKeySource;

  /// 明文密钥只在保存时上行；读取时不回传（用 api_key_source 判断是否已配置）
  final String apiKey;
  final bool isActive;
  final double temperature;
  final PlatformInt64? maxTokens;

  const AiProviderConfigDto({
    required this.id,
    required this.name,
    required this.providerType,
    required this.baseUrl,
    required this.model,
    required this.apiKeySource,
    required this.apiKey,
    required this.isActive,
    required this.temperature,
    this.maxTokens,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      providerType.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      apiKeySource.hashCode ^
      apiKey.hashCode ^
      isActive.hashCode ^
      temperature.hashCode ^
      maxTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiProviderConfigDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          providerType == other.providerType &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          apiKeySource == other.apiKeySource &&
          apiKey == other.apiKey &&
          isActive == other.isActive &&
          temperature == other.temperature &&
          maxTokens == other.maxTokens;
}
