// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 列出规则库（含已生效与待确认）
Future<List<RuleDto>> listRules() =>
    RustLib.instance.api.crateApiRulesListRules();

/// 新增一条规则（手动添加，直接生效）
Future<String> addRule({required String content}) =>
    RustLib.instance.api.crateApiRulesAddRule(content: content);

/// 删除一条规则
Future<void> deleteRule({required String ruleId}) =>
    RustLib.instance.api.crateApiRulesDeleteRule(ruleId: ruleId);

/// 个人经验规则 DTO
class RuleDto {
  final String id;
  final String content;
  final String status;
  final String createdAt;

  const RuleDto({
    required this.id,
    required this.content,
    required this.status,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ content.hashCode ^ status.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          status == other.status &&
          createdAt == other.createdAt;
}
