// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// 读取主题偏好（默认深色 + 琥珀 + Inter + 16px，保留现有观感；
/// 编辑器覆盖层无则 None，UI 回落全局）
Future<ThemePrefsDto> getThemePrefs() =>
    RustLib.instance.api.crateApiThemeGetThemePrefs();

/// 保存主题偏好（设置页「外观」保存）。编辑器覆盖层参数 None = 跟随全局，
/// 会从 app_meta 删除对应键（覆盖态回归继承态）。
Future<void> updateThemePrefs({
  required String mode,
  required String preset,
  required String font,
  required double fontSize,
  String? editorFont,
  double? editorFontSize,
  double? editorLineHeight,
}) => RustLib.instance.api.crateApiThemeUpdateThemePrefs(
  mode: mode,
  preset: preset,
  font: font,
  fontSize: fontSize,
  editorFont: editorFont,
  editorFontSize: editorFontSize,
  editorLineHeight: editorLineHeight,
);

/// 主题偏好 DTO（设置页「外观」：模式 + 预设 + 字体 + 正文字号；存 app_meta。
/// 后三项为编辑器内容区覆盖层，None = 跟随全局，见两层覆盖模型）
class ThemePrefsDto {
  /// "light" | "dark" | "system"
  final String mode;

  /// 预设名，如 "amber" | "indigo" | "aqua" | "violet"
  final String preset;

  /// 字体名，如 "inter" | "notoSansSc" | "notoSerifSc" | "system"
  final String font;

  /// 知识库正文字号（12.0–24.0，默认 16.0）
  final double fontSize;

  /// 编辑器（内容区）字体覆盖；None = 跟随全局
  final String? editorFont;

  /// 编辑器（内容区）字号覆盖；None = 跟随全局
  final double? editorFontSize;

  /// 编辑器（内容区）行距覆盖；None = 跟随全局
  final double? editorLineHeight;

  const ThemePrefsDto({
    required this.mode,
    required this.preset,
    required this.font,
    required this.fontSize,
    this.editorFont,
    this.editorFontSize,
    this.editorLineHeight,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      preset.hashCode ^
      font.hashCode ^
      fontSize.hashCode ^
      editorFont.hashCode ^
      editorFontSize.hashCode ^
      editorLineHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemePrefsDto &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          preset == other.preset &&
          font == other.font &&
          fontSize == other.fontSize &&
          editorFont == other.editorFont &&
          editorFontSize == other.editorFontSize &&
          editorLineHeight == other.editorLineHeight;
}
