// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'wiki.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// 列出待办（status 过滤：open/done/archived；None 时列出 open+done）
Future<List<TodoDto>> listTodos({String? status}) =>
    RustLib.instance.api.crateApiTodosListTodos(status: status);

/// 新建待办（用户手动创建，直接生效）
Future<TodoDto> createTodo({
  required String title,
  String? dueAt,
  String? priority,
  String? relatedWikiSlug,
  String? note,
}) => RustLib.instance.api.crateApiTodosCreateTodo(
  title: title,
  dueAt: dueAt,
  priority: priority,
  relatedWikiSlug: relatedWikiSlug,
  note: note,
);

/// 更新待办状态（open/done/archived）
Future<void> updateTodoStatus({required String id, required String status}) =>
    RustLib.instance.api.crateApiTodosUpdateTodoStatus(id: id, status: status);

/// 打开待办对应的可讨论工作项；无关联页时按需创建并回写关联。
Future<WikiPageDto> openTodoWorkItem({required String id}) =>
    RustLib.instance.api.crateApiTodosOpenTodoWorkItem(id: id);

/// 更新待办的可编辑字段（标题 / 补充 / 优先级 / 截止时间）。
/// 可选字段传 None 表示清除（如结束拖延、去掉截止时间）。
Future<void> updateTodo({
  required String id,
  required String title,
  String? note,
  String? priority,
  String? dueAt,
}) => RustLib.instance.api.crateApiTodosUpdateTodo(
  id: id,
  title: title,
  note: note,
  priority: priority,
  dueAt: dueAt,
);

/// 删除一条待办
Future<bool> deleteTodo({required String id}) =>
    RustLib.instance.api.crateApiTodosDeleteTodo(id: id);

/// 待办 DTO
class TodoDto {
  final String id;
  final String title;
  final String status;
  final String priority;
  final String? dueAt;
  final String? relatedEventId;
  final String? relatedWikiSlug;
  final String? note;
  final String createdAt;
  final String updatedAt;

  const TodoDto({
    required this.id,
    required this.title,
    required this.status,
    required this.priority,
    this.dueAt,
    this.relatedEventId,
    this.relatedWikiSlug,
    this.note,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      dueAt.hashCode ^
      relatedEventId.hashCode ^
      relatedWikiSlug.hashCode ^
      note.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          status == other.status &&
          priority == other.priority &&
          dueAt == other.dueAt &&
          relatedEventId == other.relatedEventId &&
          relatedWikiSlug == other.relatedWikiSlug &&
          note == other.note &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
