// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'wiki.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// 从 x.com / twitter.com 推文链接抓取长文（只解析 json，不写库）。
/// 是否入库由后续「保存」动作决定。
Future<TweetFetchDto> fetchTweet({required String url}) =>
    RustLib.instance.api.crateApiTweetFetchTweet(url: url);

/// 把已抓取的推文内容保存为知识库页面（kind=source）并返回该页。
/// 只有用户点击「保存」才走这里入库存。
Future<WikiPageDto> saveTweetPage({
  required String tweetId,
  required String text,
  String? title,
  String? authorName,
  String? screenName,
}) => RustLib.instance.api.crateApiTweetSaveTweetPage(
  tweetId: tweetId,
  text: text,
  title: title,
  authorName: authorName,
  screenName: screenName,
);

/// 把用户粘贴的纯文本保存为知识库页面（kind=topic），返回该页。
/// content_md 保留全文，不截断；tags 可选（页面保留「note」锚点标签）。
Future<WikiPageDto> saveTextPage({
  required String text,
  String? title,
  required List<String> tags,
}) => RustLib.instance.api.crateApiTweetSaveTextPage(
  text: text,
  title: title,
  tags: tags,
);

/// 判断一个网址是否需要走专用抓取 API（当前：x.com/twitter.com 推文 → fxtwitter）。
/// 返回 "tweet" 或 "web"，供导入入口统一分发，避免前端各自猜测。
Future<String> guessImportKind({required String url}) =>
    RustLib.instance.api.crateApiTweetGuessImportKind(url: url);

/// 针对一段抓取内容做一次性对话回复（不写库，供保存前与 AI 讨论内容）
Future<String> generateContentChat({
  required String content,
  required List<ContentChatMessageDto> messages,
}) => RustLib.instance.api.crateApiTweetGenerateContentChat(
  content: content,
  messages: messages,
);

/// 当前推文抓取服务（设置页读取；当前仅支持 fxtwitter）
Future<String> getTweetFetchService() =>
    RustLib.instance.api.crateApiTweetGetTweetFetchService();

/// 更新推文抓取服务（设置页保存）
Future<void> updateTweetFetchService({required String service}) =>
    RustLib.instance.api.crateApiTweetUpdateTweetFetchService(service: service);

/// 按推文链接查知识库是否已存在对应页面（URL 查重）。
/// 已保存过则返回该页 DTO（UI 直接打开、不再抓取）；否则返回 None。
/// 链接格式不合法 / 未找到都算「不存在」。
Future<WikiPageDto?> findTweetSourcePage({required String url}) =>
    RustLib.instance.api.crateApiTweetFindTweetSourcePage(url: url);

/// 内容对话消息 DTO（临时讨论的一条消息）
class ContentChatMessageDto {
  final String role;
  final String content;

  const ContentChatMessageDto({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentChatMessageDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

/// 抓取的推文内容 DTO（只解析，不入库）
class TweetFetchDto {
  final String tweetId;
  final String url;
  final String text;

  /// 文章型推文的标题（article.title），普通推文为 None
  final String? title;
  final String? authorName;
  final String? screenName;

  const TweetFetchDto({
    required this.tweetId,
    required this.url,
    required this.text,
    this.title,
    this.authorName,
    this.screenName,
  });

  @override
  int get hashCode =>
      tweetId.hashCode ^
      url.hashCode ^
      text.hashCode ^
      title.hashCode ^
      authorName.hashCode ^
      screenName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TweetFetchDto &&
          runtimeType == other.runtimeType &&
          tweetId == other.tweetId &&
          url == other.url &&
          text == other.text &&
          title == other.title &&
          authorName == other.authorName &&
          screenName == other.screenName;
}
