// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'conversations.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 获取（不存在则创建）某个知识页的处理会话，返回会话 DTO。
/// 页内 AI 聊天通过该会话进行；生成时自动注入页面内容。
Future<ConversationDto> ensureWikiPageChat({required String pageSlug}) =>
    RustLib.instance.api.crateApiWikiChatEnsureWikiPageChat(pageSlug: pageSlug);

/// 删除一个知识页的处理会话（重建时用）
Future<void> archiveWikiPageChat({required String pageSlug}) => RustLib
    .instance
    .api
    .crateApiWikiChatArchiveWikiPageChat(pageSlug: pageSlug);
