// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// List wiki pages（主列表）。kind/area 均为 None 时列出全部（不含派生产物）。
/// area：imported（素材库）/ network（人物项目）/ insight（知识沉淀）。
Future<List<WikiPageDto>> listWikiPages({String? kind, String? area}) =>
    RustLib.instance.api.crateApiWikiListWikiPages(kind: kind, area: area);

/// 某页的派生产物列表（AI 加工成果，挂在该页详情下，不进主列表）。
Future<List<WikiPageDto>> listWikiPageDerivatives({required String slug}) =>
    RustLib.instance.api.crateApiWikiListWikiPageDerivatives(slug: slug);

/// 直接把一段内容保存为某知识页的派生产物（页内 AI 聊天「保存」按钮用，跳过 AI 草拟确认）。
Future<WikiPageDto> createWikiDerivative({
  required String basedOnSlug,
  required String contentType,
  required String title,
  required String contentMd,
}) => RustLib.instance.api.crateApiWikiCreateWikiDerivative(
  basedOnSlug: basedOnSlug,
  contentType: contentType,
  title: title,
  contentMd: contentMd,
);

/// Get a single wiki page by slug
Future<WikiPageDto?> getWikiPage({required String slug}) =>
    RustLib.instance.api.crateApiWikiGetWikiPage(slug: slug);

/// 更新知识页标签（应用内整理元数据用；传空数组即清空）。返回更新后的页面。
Future<WikiPageDto> updateWikiTags({
  required String slug,
  required List<String> tags,
}) => RustLib.instance.api.crateApiWikiUpdateWikiTags(slug: slug, tags: tags);

/// 修改一张项目页关联的本地目录（目录搬家后在知识页纠正路径）。
/// 路径记进 `source_url`（file:// 规范形式）；新路径必须存在且是目录。返回更新后的页面。
Future<WikiPageDto> updateProjectPath({
  required String slug,
  required String newPath,
}) => RustLib.instance.api.crateApiWikiUpdateProjectPath(
  slug: slug,
  newPath: newPath,
);

/// 刷新一张目录导入的项目页：按 `source_url`（file://）重扫目录并整篇更新。
/// 目录不存在会直接报错（提示先改路径）。返回刷新后的页面。
Future<WikiPageDto> refreshProjectPage({required String slug}) =>
    RustLib.instance.api.crateApiWikiRefreshProjectPage(slug: slug);

/// 人类编辑保存一页正文（限可编辑 kind；素材页只读拒绝）。
/// 保存后 `human_edited_at` 置位：该页被 AI digest 视为人工持有，不再整篇覆盖。
/// `expected_updated_at`：乐观锁（§11 Q3）——传加载时的 updated_at（rfc3339），
/// 与当前不一致则报「编辑冲突」，拒绝静默覆盖编辑期间的后台写入；None 跳过校验。
Future<WikiPageDto> saveWikiPageContent({
  required String slug,
  required String contentMd,
  required String reason,
  String? expectedUpdatedAt,
}) => RustLib.instance.api.crateApiWikiSaveWikiPageContent(
  slug: slug,
  contentMd: contentMd,
  reason: reason,
  expectedUpdatedAt: expectedUpdatedAt,
);

/// 素材页观点评价（仅 source/note）。opinion：Some("endorse")=认可 / Some("reject")=不认可 /
/// None=清空回未表态（读取按缺省认可处理）。不改变正文、不置位人工编辑保护。
Future<WikiPageDto> setWikiOpinion({required String slug, String? opinion}) =>
    RustLib.instance.api.crateApiWikiSetWikiOpinion(
      slug: slug,
      opinion: opinion,
    );

/// Wiki page data transfer object for Flutter（知识库浏览）
class WikiPageDto {
  final String id;
  final String slug;
  final String kind;
  final String title;
  final String summary;
  final String contentMd;
  final List<String> tags;
  final List<String> sourceEventIds;
  final PlatformInt64 evidenceCount;
  final String firstSeenAt;
  final String lastSeenAt;
  final String status;
  final String createdAt;
  final String updatedAt;
  final String? sourceUrl;

  /// 来源/用途分区：imported（素材库）/ network（人物项目）/ insight（知识沉淀）/ derivative（派生产物）
  final String area;

  /// 派生产物指向的原页面 slug（仅 derivative 有值）
  final String? basedOn;

  /// 派生产物的加工类型（总结/提炼观点/抖音文案…，仅 derivative 有值）
  final String? contentType;

  /// 最近一次人工编辑正文的时间（非空 ⇔ 该页由人工持有，digest 不整篇覆盖）
  final String? humanEditedAt;

  /// 素材页观点评价：Some("endorse")/Some("reject")/None=未表态（缺省认可）
  final String? opinion;

  const WikiPageDto({
    required this.id,
    required this.slug,
    required this.kind,
    required this.title,
    required this.summary,
    required this.contentMd,
    required this.tags,
    required this.sourceEventIds,
    required this.evidenceCount,
    required this.firstSeenAt,
    required this.lastSeenAt,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
    this.sourceUrl,
    required this.area,
    this.basedOn,
    this.contentType,
    this.humanEditedAt,
    this.opinion,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      slug.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      contentMd.hashCode ^
      tags.hashCode ^
      sourceEventIds.hashCode ^
      evidenceCount.hashCode ^
      firstSeenAt.hashCode ^
      lastSeenAt.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      sourceUrl.hashCode ^
      area.hashCode ^
      basedOn.hashCode ^
      contentType.hashCode ^
      humanEditedAt.hashCode ^
      opinion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WikiPageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          slug == other.slug &&
          kind == other.kind &&
          title == other.title &&
          summary == other.summary &&
          contentMd == other.contentMd &&
          tags == other.tags &&
          sourceEventIds == other.sourceEventIds &&
          evidenceCount == other.evidenceCount &&
          firstSeenAt == other.firstSeenAt &&
          lastSeenAt == other.lastSeenAt &&
          status == other.status &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          sourceUrl == other.sourceUrl &&
          area == other.area &&
          basedOn == other.basedOn &&
          contentType == other.contentType &&
          humanEditedAt == other.humanEditedAt &&
          opinion == other.opinion;
}
