# Converts the app icon PNG into a C++ source file containing the raw bytes,
# so the GTK window can set its taskbar/window icon without depending on the
# icon theme or a filesystem path at runtime.
#
# The paths below are derived from the script's own location rather than being
# passed in via -D, which keeps the custom command robust across CMake
# versions and shells:
#
#   - INPUT:  app_icon.png next to this script (runner source dir)
#   - OUTPUT: app_icon_embedded.cpp in the current working directory
#             (the runner build dir, which CMake reports as
#             CMAKE_CURRENT_BINARY_DIR in -P script mode)

get_filename_component(_script_dir "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
set(APP_ICON_PNG "${_script_dir}/app_icon.png")
set(APP_ICON_EMBEDDED_SOURCE
    "${CMAKE_CURRENT_BINARY_DIR}/app_icon_embedded.cpp")

file(READ "${APP_ICON_PNG}" _icon_hex HEX)
string(TOLOWER "${_icon_hex}" _icon_hex)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " _icon_bytes "${_icon_hex}")

set(_icon_decl
"// Generated by make_embedded_icon.cmake - do not edit.\n\
#include <cstddef>\n\
extern \"C\" const unsigned char kAppIconPng[] = {\n\
  ${_icon_bytes}\n\
};\n\
extern \"C\" const std::size_t kAppIconPngSize = sizeof(kAppIconPng);\n"
)

file(WRITE "${APP_ICON_EMBEDDED_SOURCE}" "${_icon_decl}")