// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/todos.dart';
import 'frb_generated.dart';

// ⚠️ 手工补的：frb 2.14.0-beta.2 在 `crate::api` 下有多个子模块时会把 API 拆到
// `api/<module>.dart`，但生成的 barrel 只 import 了其中一个模块，漏掉其余模块，
// 导致下游 analyzer 报上百个 undefined_function / undefined_class。
// 下次重跑 codegen 后，如果 `flutter analyze` 出现大批 undefined，
// 就是这里被覆盖了，把下面这段重新贴回来即可（见 flutter_rust_bridge.yaml 的说明）。
export 'api/conversations.dart';
export 'api/entities.dart';
export 'api/fonts.dart';
export 'api/goals.dart';
export 'api/import.dart';
export 'api/knowledge_digest.dart';
export 'api/provider_config.dart';
export 'api/relations.dart';
export 'api/rules.dart';
export 'api/theme.dart';
export 'api/todos.dart';
export 'api/tweet.dart';
export 'api/wiki.dart';
export 'api/wiki_chat.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `decision_support_context`, `default_event_kind`, `default_recordable`, `effective_event_recordability`, `entry_is_recordable`, `generate_daily_review_with_provider`, `normalize_strings`, `parse`, `parse`, `process_analysis_queue`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DailyReviewItemV1`, `DailyReviewV1`, `EventAnalysisV1`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Initialize the bridge with database path
Future<String> initBridge({String? databasePath}) =>
    RustLib.instance.api.crateApiInitBridge(databasePath: databasePath);

/// Record a new event
Future<EventDto> recordEvent({required String rawText}) =>
    RustLib.instance.api.crateApiRecordEvent(rawText: rawText);

/// Save a plain personal input without waiting for AI/network.
/// Reusing an idempotency key returns the original routed result.
Future<InputRecordDto> submitInput({
  required String rawText,
  required String source,
  String? idempotencyKey,
}) => RustLib.instance.api.crateApiSubmitInput(
  rawText: rawText,
  source: source,
  idempotencyKey: idempotencyKey,
);

/// Start routing a URL input without creating a personal event. The raw URL is
/// durable before any network fetch begins and remains awaiting confirmation
/// until the preview is explicitly saved.
Future<InputRecordDto> beginUrlInput({
  required String rawText,
  String? idempotencyKey,
}) => RustLib.instance.api.crateApiBeginUrlInput(
  rawText: rawText,
  idempotencyKey: idempotencyKey,
);

/// Complete or fail the URL preview route while preserving the original input.
Future<InputRecordDto> finishUrlInput({
  required String inputId,
  String? wikiPageSlug,
  required bool failed,
}) => RustLib.instance.api.crateApiFinishUrlInput(
  inputId: inputId,
  wikiPageSlug: wikiPageSlug,
  failed: failed,
);

Future<InputRecordDto> submitConversationInput({
  required String conversationId,
  required String rawText,
  String? idempotencyKey,
}) => RustLib.instance.api.crateApiSubmitConversationInput(
  conversationId: conversationId,
  rawText: rawText,
  idempotencyKey: idempotencyKey,
);

/// List one local calendar day's complete personal record stream.
Future<List<DailyEntryDto>> listDailyEntries({required String date}) =>
    RustLib.instance.api.crateApiListDailyEntries(date: date);

Future<DailyOverviewDto> getDailyOverview({required String date}) =>
    RustLib.instance.api.crateApiGetDailyOverview(date: date);

Future<String> saveDailyReview({
  required String date,
  required String resultJson,
  required String promptVersion,
  required List<String> sourceEventIds,
}) => RustLib.instance.api.crateApiSaveDailyReview(
  date: date,
  resultJson: resultJson,
  promptVersion: promptVersion,
  sourceEventIds: sourceEventIds,
);

Future<DailyReviewResult> generateDailyReview({required String date}) =>
    RustLib.instance.api.crateApiGenerateDailyReview(date: date);

Future<EventAnalysisDetailDto?> getEventAnalysisDetail({
  required String eventId,
}) => RustLib.instance.api.crateApiGetEventAnalysisDetail(eventId: eventId);

Future<MessageRecordabilityDto?> getMessageRecordability({
  required String messageId,
}) =>
    RustLib.instance.api.crateApiGetMessageRecordability(messageId: messageId);

Future<MessageRecordabilityDto> setEventRecordability({
  required String eventId,
  required bool recordable,
}) => RustLib.instance.api.crateApiSetEventRecordability(
  eventId: eventId,
  recordable: recordable,
);

Future<bool> reanalyzeEvent({required String eventId}) =>
    RustLib.instance.api.crateApiReanalyzeEvent(eventId: eventId);

/// List all events
Future<List<EventDto>> listEvents() =>
    RustLib.instance.api.crateApiListEvents();

/// List completed analyses
Future<List<AnalysisDto>> listAnalyses() =>
    RustLib.instance.api.crateApiListAnalyses();

Future<AnalysisJobStatsDto> getAnalysisJobStats() =>
    RustLib.instance.api.crateApiGetAnalysisJobStats();

/// Trigger AI analysis for pending events
/// Returns `AnalysisTriggerResult`（结构化状态，取代字符串契约）。
Future<AnalysisTriggerResult> triggerAnalysis() =>
    RustLib.instance.api.crateApiTriggerAnalysis();

/// Analysis result DTO
class AnalysisDto {
  final String eventType;
  final double confidence;
  final String summary;
  final List<String> clarifications;

  const AnalysisDto({
    required this.eventType,
    required this.confidence,
    required this.summary,
    required this.clarifications,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      confidence.hashCode ^
      summary.hashCode ^
      clarifications.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisDto &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          confidence == other.confidence &&
          summary == other.summary &&
          clarifications == other.clarifications;
}

/// Durable event-analysis queue counts for operational visibility.
class AnalysisJobStatsDto {
  final PlatformInt64 pending;
  final PlatformInt64 running;
  final PlatformInt64 retry;
  final PlatformInt64 succeeded;
  final PlatformInt64 failed;

  const AnalysisJobStatsDto({
    required this.pending,
    required this.running,
    required this.retry,
    required this.succeeded,
    required this.failed,
  });

  @override
  int get hashCode =>
      pending.hashCode ^
      running.hashCode ^
      retry.hashCode ^
      succeeded.hashCode ^
      failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisJobStatsDto &&
          runtimeType == other.runtimeType &&
          pending == other.pending &&
          running == other.running &&
          retry == other.retry &&
          succeeded == other.succeeded &&
          failed == other.failed;
}

@freezed
sealed class AnalysisTriggerResult with _$AnalysisTriggerResult {
  const AnalysisTriggerResult._();

  /// 尚未配置 AI provider：不做分析，等待配置后再唤醒
  const factory AnalysisTriggerResult.noProvider() =
      AnalysisTriggerResult_NoProvider;

  /// 本轮成功处理了 count 条事件（含 0：队列为空或全部等待重试）
  const factory AnalysisTriggerResult.processed({
    required PlatformInt64 count,
  }) = AnalysisTriggerResult_Processed;
}

class DailyEntryDto {
  final String eventId;
  final String? inputId;
  final String? messageId;
  final String rawText;
  final String source;
  final String eventStatus;
  final String recordedAt;

  const DailyEntryDto({
    required this.eventId,
    this.inputId,
    this.messageId,
    required this.rawText,
    required this.source,
    required this.eventStatus,
    required this.recordedAt,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      inputId.hashCode ^
      messageId.hashCode ^
      rawText.hashCode ^
      source.hashCode ^
      eventStatus.hashCode ^
      recordedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyEntryDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          inputId == other.inputId &&
          messageId == other.messageId &&
          rawText == other.rawText &&
          source == other.source &&
          eventStatus == other.eventStatus &&
          recordedAt == other.recordedAt;
}

class DailyOverviewDto {
  final String date;
  final List<DailyEntryDto> entries;
  final DailyReviewDto? review;
  final List<TodoDto> todos;

  const DailyOverviewDto({
    required this.date,
    required this.entries,
    this.review,
    required this.todos,
  });

  @override
  int get hashCode =>
      date.hashCode ^ entries.hashCode ^ review.hashCode ^ todos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyOverviewDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          entries == other.entries &&
          review == other.review &&
          todos == other.todos;
}

class DailyReviewDto {
  final String id;
  final String date;
  final String promptVersion;
  final String createdAt;
  final List<DailyReviewItemDto> accomplishments;
  final List<DailyReviewItemDto> ideasDecisions;
  final List<DailyReviewItemDto> peopleProjects;
  final List<DailyReviewItemDto> followUps;

  const DailyReviewDto({
    required this.id,
    required this.date,
    required this.promptVersion,
    required this.createdAt,
    required this.accomplishments,
    required this.ideasDecisions,
    required this.peopleProjects,
    required this.followUps,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      date.hashCode ^
      promptVersion.hashCode ^
      createdAt.hashCode ^
      accomplishments.hashCode ^
      ideasDecisions.hashCode ^
      peopleProjects.hashCode ^
      followUps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyReviewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          promptVersion == other.promptVersion &&
          createdAt == other.createdAt &&
          accomplishments == other.accomplishments &&
          ideasDecisions == other.ideasDecisions &&
          peopleProjects == other.peopleProjects &&
          followUps == other.followUps;
}

class DailyReviewItemDto {
  final String text;
  final List<String> sourceEventIds;

  const DailyReviewItemDto({required this.text, required this.sourceEventIds});

  @override
  int get hashCode => text.hashCode ^ sourceEventIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyReviewItemDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          sourceEventIds == other.sourceEventIds;
}

@freezed
sealed class DailyReviewResult with _$DailyReviewResult {
  const DailyReviewResult._();

  const factory DailyReviewResult.noProvider() = DailyReviewResult_NoProvider;

  /// 当天没有可记录内容，未生成回顾
  const factory DailyReviewResult.noEntries() = DailyReviewResult_NoEntries;
  const factory DailyReviewResult.created({required String id}) =
      DailyReviewResult_Created;
}

class EntityFactDto {
  final String id;
  final String entityKind;
  final String entitySlug;
  final String factText;
  final String occurredAt;
  final PlatformInt64 confidence;
  final String sourceEventId;
  final String createdAt;
  final String lastSeenAt;

  const EntityFactDto({
    required this.id,
    required this.entityKind,
    required this.entitySlug,
    required this.factText,
    required this.occurredAt,
    required this.confidence,
    required this.sourceEventId,
    required this.createdAt,
    required this.lastSeenAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entityKind.hashCode ^
      entitySlug.hashCode ^
      factText.hashCode ^
      occurredAt.hashCode ^
      confidence.hashCode ^
      sourceEventId.hashCode ^
      createdAt.hashCode ^
      lastSeenAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityFactDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entityKind == other.entityKind &&
          entitySlug == other.entitySlug &&
          factText == other.factText &&
          occurredAt == other.occurredAt &&
          confidence == other.confidence &&
          sourceEventId == other.sourceEventId &&
          createdAt == other.createdAt &&
          lastSeenAt == other.lastSeenAt;
}

class EventAnalysisDetailDto {
  final String eventId;
  final String rawText;
  final String source;
  final String recordedAt;
  final String eventStatus;
  final String jobStatus;
  final PlatformInt64 attempts;
  final String? lastError;
  final String availableAt;
  final String? promptVersion;
  final String? analysisCreatedAt;
  final String? schemaVersion;
  final String? eventType;
  final double? confidence;
  final String? summary;
  final List<String> clarifications;
  final List<String> people;
  final List<String> projects;
  final List<String> activities;
  final List<String> followUps;
  final bool? recordable;
  final String? kind;
  final bool effectiveRecordable;
  final String effectiveKind;
  final String recordabilitySource;

  const EventAnalysisDetailDto({
    required this.eventId,
    required this.rawText,
    required this.source,
    required this.recordedAt,
    required this.eventStatus,
    required this.jobStatus,
    required this.attempts,
    this.lastError,
    required this.availableAt,
    this.promptVersion,
    this.analysisCreatedAt,
    this.schemaVersion,
    this.eventType,
    this.confidence,
    this.summary,
    required this.clarifications,
    required this.people,
    required this.projects,
    required this.activities,
    required this.followUps,
    this.recordable,
    this.kind,
    required this.effectiveRecordable,
    required this.effectiveKind,
    required this.recordabilitySource,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      rawText.hashCode ^
      source.hashCode ^
      recordedAt.hashCode ^
      eventStatus.hashCode ^
      jobStatus.hashCode ^
      attempts.hashCode ^
      lastError.hashCode ^
      availableAt.hashCode ^
      promptVersion.hashCode ^
      analysisCreatedAt.hashCode ^
      schemaVersion.hashCode ^
      eventType.hashCode ^
      confidence.hashCode ^
      summary.hashCode ^
      clarifications.hashCode ^
      people.hashCode ^
      projects.hashCode ^
      activities.hashCode ^
      followUps.hashCode ^
      recordable.hashCode ^
      kind.hashCode ^
      effectiveRecordable.hashCode ^
      effectiveKind.hashCode ^
      recordabilitySource.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventAnalysisDetailDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          rawText == other.rawText &&
          source == other.source &&
          recordedAt == other.recordedAt &&
          eventStatus == other.eventStatus &&
          jobStatus == other.jobStatus &&
          attempts == other.attempts &&
          lastError == other.lastError &&
          availableAt == other.availableAt &&
          promptVersion == other.promptVersion &&
          analysisCreatedAt == other.analysisCreatedAt &&
          schemaVersion == other.schemaVersion &&
          eventType == other.eventType &&
          confidence == other.confidence &&
          summary == other.summary &&
          clarifications == other.clarifications &&
          people == other.people &&
          projects == other.projects &&
          activities == other.activities &&
          followUps == other.followUps &&
          recordable == other.recordable &&
          kind == other.kind &&
          effectiveRecordable == other.effectiveRecordable &&
          effectiveKind == other.effectiveKind &&
          recordabilitySource == other.recordabilitySource;
}

/// Event data transfer object for Flutter
class EventDto {
  final String id;
  final String rawText;
  final String recordedAt;
  final String occurredAt;
  final String source;
  final String status;

  const EventDto({
    required this.id,
    required this.rawText,
    required this.recordedAt,
    required this.occurredAt,
    required this.source,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rawText.hashCode ^
      recordedAt.hashCode ^
      occurredAt.hashCode ^
      source.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rawText == other.rawText &&
          recordedAt == other.recordedAt &&
          occurredAt == other.occurredAt &&
          source == other.source &&
          status == other.status;
}

class InputRecordDto {
  final String id;
  final String rawText;
  final String source;
  final String routeStatus;
  final String? idempotencyKey;
  final String? eventId;
  final String? messageId;
  final String? wikiPageSlug;
  final String? todoId;
  final String createdAt;
  final String updatedAt;

  const InputRecordDto({
    required this.id,
    required this.rawText,
    required this.source,
    required this.routeStatus,
    this.idempotencyKey,
    this.eventId,
    this.messageId,
    this.wikiPageSlug,
    this.todoId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rawText.hashCode ^
      source.hashCode ^
      routeStatus.hashCode ^
      idempotencyKey.hashCode ^
      eventId.hashCode ^
      messageId.hashCode ^
      wikiPageSlug.hashCode ^
      todoId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputRecordDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rawText == other.rawText &&
          source == other.source &&
          routeStatus == other.routeStatus &&
          idempotencyKey == other.idempotencyKey &&
          eventId == other.eventId &&
          messageId == other.messageId &&
          wikiPageSlug == other.wikiPageSlug &&
          todoId == other.todoId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class MessageRecordabilityDto {
  final String messageId;
  final String eventId;
  final bool recordable;
  final String kind;
  final String source;
  final String jobStatus;
  final String? summary;

  const MessageRecordabilityDto({
    required this.messageId,
    required this.eventId,
    required this.recordable,
    required this.kind,
    required this.source,
    required this.jobStatus,
    this.summary,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      eventId.hashCode ^
      recordable.hashCode ^
      kind.hashCode ^
      source.hashCode ^
      jobStatus.hashCode ^
      summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageRecordabilityDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          eventId == other.eventId &&
          recordable == other.recordable &&
          kind == other.kind &&
          source == other.source &&
          jobStatus == other.jobStatus &&
          summary == other.summary;
}
