// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decision_support_context`, `default_event_kind`, `default_recordable`, `dto_from_active`, `effective_event_recordability`, `entry_is_recordable`, `generate_daily_review_with_provider`, `normalize_strings`, `parse`, `parse`, `process_analysis_queue`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DailyReviewItemV1`, `DailyReviewV1`, `EventAnalysisV1`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Initialize the bridge with database path
Future<String> initBridge({String? databasePath}) =>
    RustLib.instance.api.crateApiInitBridge(databasePath: databasePath);

/// Record a new event
Future<EventDto> recordEvent({required String rawText}) =>
    RustLib.instance.api.crateApiRecordEvent(rawText: rawText);

/// Save a plain personal input without waiting for AI/network.
/// Reusing an idempotency key returns the original routed result.
Future<InputRecordDto> submitInput({
  required String rawText,
  required String source,
  String? idempotencyKey,
}) => RustLib.instance.api.crateApiSubmitInput(
  rawText: rawText,
  source: source,
  idempotencyKey: idempotencyKey,
);

/// Start routing a URL input without creating a personal event. The raw URL is
/// durable before any network fetch begins and remains awaiting confirmation
/// until the preview is explicitly saved.
Future<InputRecordDto> beginUrlInput({
  required String rawText,
  String? idempotencyKey,
}) => RustLib.instance.api.crateApiBeginUrlInput(
  rawText: rawText,
  idempotencyKey: idempotencyKey,
);

/// Complete or fail the URL preview route while preserving the original input.
Future<InputRecordDto> finishUrlInput({
  required String inputId,
  String? wikiPageSlug,
  required bool failed,
}) => RustLib.instance.api.crateApiFinishUrlInput(
  inputId: inputId,
  wikiPageSlug: wikiPageSlug,
  failed: failed,
);

Future<InputRecordDto> submitConversationInput({
  required String conversationId,
  required String rawText,
  String? idempotencyKey,
}) => RustLib.instance.api.crateApiSubmitConversationInput(
  conversationId: conversationId,
  rawText: rawText,
  idempotencyKey: idempotencyKey,
);

/// List one local calendar day's complete personal record stream.
Future<List<DailyEntryDto>> listDailyEntries({required String date}) =>
    RustLib.instance.api.crateApiListDailyEntries(date: date);

Future<DailyOverviewDto> getDailyOverview({required String date}) =>
    RustLib.instance.api.crateApiGetDailyOverview(date: date);

Future<String> saveDailyReview({
  required String date,
  required String resultJson,
  required String promptVersion,
  required List<String> sourceEventIds,
}) => RustLib.instance.api.crateApiSaveDailyReview(
  date: date,
  resultJson: resultJson,
  promptVersion: promptVersion,
  sourceEventIds: sourceEventIds,
);

Future<String> generateDailyReview({required String date}) =>
    RustLib.instance.api.crateApiGenerateDailyReview(date: date);

Future<EventAnalysisDetailDto?> getEventAnalysisDetail({
  required String eventId,
}) => RustLib.instance.api.crateApiGetEventAnalysisDetail(eventId: eventId);

Future<MessageRecordabilityDto?> getMessageRecordability({
  required String messageId,
}) =>
    RustLib.instance.api.crateApiGetMessageRecordability(messageId: messageId);

Future<MessageRecordabilityDto> setEventRecordability({
  required String eventId,
  required bool recordable,
}) => RustLib.instance.api.crateApiSetEventRecordability(
  eventId: eventId,
  recordable: recordable,
);

Future<bool> reanalyzeEvent({required String eventId}) =>
    RustLib.instance.api.crateApiReanalyzeEvent(eventId: eventId);

Future<List<EntityFactDto>> listEntityFacts({
  required String entityKind,
  required String entitySlug,
}) => RustLib.instance.api.crateApiListEntityFacts(
  entityKind: entityKind,
  entitySlug: entitySlug,
);

Future<bool> deleteEntityFact({required String id}) =>
    RustLib.instance.api.crateApiDeleteEntityFact(id: id);

Future<List<String>> listEntityAliases({
  required String entityKind,
  required String entitySlug,
}) => RustLib.instance.api.crateApiListEntityAliases(
  entityKind: entityKind,
  entitySlug: entitySlug,
);

Future<void> addEntityAlias({
  required String entityKind,
  required String entitySlug,
  required String alias,
}) => RustLib.instance.api.crateApiAddEntityAlias(
  entityKind: entityKind,
  entitySlug: entitySlug,
  alias: alias,
);

/// Merge two confirmed entities after explicit user confirmation.
Future<bool> mergeEntity({
  required String entityKind,
  required String sourceSlug,
  required String targetSlug,
}) => RustLib.instance.api.crateApiMergeEntity(
  entityKind: entityKind,
  sourceSlug: sourceSlug,
  targetSlug: targetSlug,
);

Future<EntityMergeStatusDto?> getEntityMergeStatus({
  required String sourceSlug,
}) => RustLib.instance.api.crateApiGetEntityMergeStatus(sourceSlug: sourceSlug);

/// Undo one merge only when every moved row still matches its merge snapshot.
Future<bool> undoEntityMerge({required String sourceSlug}) =>
    RustLib.instance.api.crateApiUndoEntityMerge(sourceSlug: sourceSlug);

/// List all events
Future<List<EventDto>> listEvents() =>
    RustLib.instance.api.crateApiListEvents();

/// List completed analyses
Future<List<AnalysisDto>> listAnalyses() =>
    RustLib.instance.api.crateApiListAnalyses();

Future<AnalysisJobStatsDto> getAnalysisJobStats() =>
    RustLib.instance.api.crateApiGetAnalysisJobStats();

/// Get active AI provider info
Future<String?> getAiProvider() => RustLib.instance.api.crateApiGetAiProvider();

/// Get the active AI provider full config (for settings page prefill)
Future<AiProviderConfigDto?> getAiProviderConfig() =>
    RustLib.instance.api.crateApiGetAiProviderConfig();

/// 列出全部 AI provider 配置（多配置，仅一个 is_active=true）
Future<List<AiProviderConfigDto>> listAiProviderConfigs() =>
    RustLib.instance.api.crateApiListAiProviderConfigs();

/// 新增或编辑 AI provider 配置；返回配置 id。
/// provider.id 为空表示新建；api_key 传空串表示保留原 key 不变（新建则必填）。
Future<String> saveAiProviderConfig({required AiProviderConfigDto provider}) =>
    RustLib.instance.api.crateApiSaveAiProviderConfig(provider: provider);

/// 将指定配置设为激活（唯一激活项）
Future<void> setActiveAiProviderConfig({required String id}) =>
    RustLib.instance.api.crateApiSetActiveAiProviderConfig(id: id);

/// 删除一个 AI provider 配置；若删除的是激活项，剩余第一条自动激活
Future<void> deleteAiProviderConfig({required String id}) =>
    RustLib.instance.api.crateApiDeleteAiProviderConfig(id: id);

/// Upsert the active AI provider config (settings page save)
Future<void> updateAiProviderConfig({
  required String baseUrl,
  required String model,
  required String apiKey,
}) => RustLib.instance.api.crateApiUpdateAiProviderConfig(
  baseUrl: baseUrl,
  model: model,
  apiKey: apiKey,
);

/// Trigger AI analysis for pending events
/// Returns "no_provider" or "processed:<successful count>".
Future<String> triggerAnalysis() =>
    RustLib.instance.api.crateApiTriggerAnalysis();

Future<List<PendingActionDto>> listPendingActions({
  required String conversationId,
}) => RustLib.instance.api.crateApiListPendingActions(
  conversationId: conversationId,
);

Future<bool> updatePendingActionArgs({
  required String actionId,
  required String argsJson,
}) => RustLib.instance.api.crateApiUpdatePendingActionArgs(
  actionId: actionId,
  argsJson: argsJson,
);

/// 从对话中的草稿预览单独保存一张知识页，不确认同会话的其他动作。
Future<String> confirmKnowledgeDraft({
  required String conversationId,
  required String actionId,
}) => RustLib.instance.api.crateApiConfirmKnowledgeDraft(
  conversationId: conversationId,
  actionId: actionId,
);

/// 只拒绝这一篇待入库知识草稿，不删除已保存页面或其他待确认动作。
Future<void> declineKnowledgeDraft({
  required String conversationId,
  required String actionId,
}) => RustLib.instance.api.crateApiDeclineKnowledgeDraft(
  conversationId: conversationId,
  actionId: actionId,
);

/// 列出规则库（含已生效与待确认）
Future<List<RuleDto>> listRules() => RustLib.instance.api.crateApiListRules();

/// 新增一条规则（手动添加，直接生效）
Future<String> addRule({required String content}) =>
    RustLib.instance.api.crateApiAddRule(content: content);

/// 删除一条规则
Future<void> deleteRule({required String ruleId}) =>
    RustLib.instance.api.crateApiDeleteRule(ruleId: ruleId);

Future<ConversationDto> createConversation({String? title, String? tag}) =>
    RustLib.instance.api.crateApiCreateConversation(title: title, tag: tag);

/// List all non-archived conversations
Future<List<ConversationDto>> listConversations() =>
    RustLib.instance.api.crateApiListConversations();

/// List archived conversations
Future<List<ConversationDto>> listArchivedConversations() =>
    RustLib.instance.api.crateApiListArchivedConversations();

/// Rename a conversation
Future<void> renameConversation({
  required String conversationId,
  required String title,
}) => RustLib.instance.api.crateApiRenameConversation(
  conversationId: conversationId,
  title: title,
);

/// Archive or unarchive a conversation
Future<void> setConversationArchived({
  required String conversationId,
  required bool archived,
}) => RustLib.instance.api.crateApiSetConversationArchived(
  conversationId: conversationId,
  archived: archived,
);

/// Delete an archived ordinary conversation.
Future<bool> deleteArchivedConversation({required String conversationId}) =>
    RustLib.instance.api.crateApiDeleteArchivedConversation(
      conversationId: conversationId,
    );

/// Get a specific conversation
Future<ConversationDto?> getConversation({required String conversationId}) =>
    RustLib.instance.api.crateApiGetConversation(
      conversationId: conversationId,
    );

/// Send a message in a conversation
Future<MessageDto> sendMessage({
  required String conversationId,
  required String role,
  required String content,
  String? parentMessageId,
}) => RustLib.instance.api.crateApiSendMessage(
  conversationId: conversationId,
  role: role,
  content: content,
  parentMessageId: parentMessageId,
);

/// List messages in a conversation
Future<List<MessageDto>> listMessages({required String conversationId}) =>
    RustLib.instance.api.crateApiListMessages(conversationId: conversationId);

/// Get child messages of a specific message (for branching conversations)
Future<List<MessageDto>> getChildMessages({required String parentId}) =>
    RustLib.instance.api.crateApiGetChildMessages(parentId: parentId);

/// Get the message chain from root to a specific message
Future<List<MessageDto>> getMessageChain({required String messageId}) =>
    RustLib.instance.api.crateApiGetMessageChain(messageId: messageId);

/// Generate AI reply for a conversation
Future<String> generateReply({
  required String conversationId,
  String? providerType,
  String? memoryType,
  int? memoryWindowSize,
}) => RustLib.instance.api.crateApiGenerateReply(
  conversationId: conversationId,
  providerType: providerType,
  memoryType: memoryType,
  memoryWindowSize: memoryWindowSize,
);

/// 获取最近 N 天的每日 token 用量统计（含当天，日期倒序）
Future<List<DailyTokenUsageDto>> getDailyTokenUsage({required int days}) =>
    RustLib.instance.api.crateApiGetDailyTokenUsage(days: days);

/// List wiki pages（主列表）。kind/area 均为 None 时列出全部（不含派生产物）。
/// area：imported（素材库）/ network（人物项目）/ insight（知识沉淀）。
Future<List<WikiPageDto>> listWikiPages({String? kind, String? area}) =>
    RustLib.instance.api.crateApiListWikiPages(kind: kind, area: area);

/// 某页的派生产物列表（AI 加工成果，挂在该页详情下，不进主列表）。
Future<List<WikiPageDto>> listWikiPageDerivatives({required String slug}) =>
    RustLib.instance.api.crateApiListWikiPageDerivatives(slug: slug);

/// 直接把一段内容保存为某知识页的派生产物（页内 AI 聊天「保存」按钮用，跳过 AI 草拟确认）。
Future<WikiPageDto> createWikiDerivative({
  required String basedOnSlug,
  required String contentType,
  required String title,
  required String contentMd,
}) => RustLib.instance.api.crateApiCreateWikiDerivative(
  basedOnSlug: basedOnSlug,
  contentType: contentType,
  title: title,
  contentMd: contentMd,
);

/// Get a single wiki page by slug
Future<WikiPageDto?> getWikiPage({required String slug}) =>
    RustLib.instance.api.crateApiGetWikiPage(slug: slug);

/// 更新知识页标签（应用内整理元数据用；传空数组即清空）。返回更新后的页面。
Future<WikiPageDto> updateWikiTags({
  required String slug,
  required List<String> tags,
}) => RustLib.instance.api.crateApiUpdateWikiTags(slug: slug, tags: tags);

/// 修改一张项目页关联的本地目录（目录搬家后在知识页纠正路径）。
/// 路径记进 `source_url`（file:// 规范形式）；新路径必须存在且是目录。返回更新后的页面。
Future<WikiPageDto> updateProjectPath({
  required String slug,
  required String newPath,
}) => RustLib.instance.api.crateApiUpdateProjectPath(
  slug: slug,
  newPath: newPath,
);

/// 刷新一张目录导入的项目页：按 `source_url`（file://）重扫目录并整篇更新。
/// 目录不存在会直接报错（提示先改路径）。返回刷新后的页面。
Future<WikiPageDto> refreshProjectPage({required String slug}) =>
    RustLib.instance.api.crateApiRefreshProjectPage(slug: slug);

/// 人类编辑保存一页正文（限可编辑 kind；素材页只读拒绝）。
/// 保存后 `human_edited_at` 置位：该页被 AI digest 视为人工持有，不再整篇覆盖。
/// `expected_updated_at`：乐观锁（§11 Q3）——传加载时的 updated_at（rfc3339），
/// 与当前不一致则报「编辑冲突」，拒绝静默覆盖编辑期间的后台写入；None 跳过校验。
Future<WikiPageDto> saveWikiPageContent({
  required String slug,
  required String contentMd,
  required String reason,
  String? expectedUpdatedAt,
}) => RustLib.instance.api.crateApiSaveWikiPageContent(
  slug: slug,
  contentMd: contentMd,
  reason: reason,
  expectedUpdatedAt: expectedUpdatedAt,
);

/// 素材页观点评价（仅 source/note）。opinion：Some("endorse")=认可 / Some("reject")=不认可 /
/// None=清空回未表态（读取按缺省认可处理）。不改变正文、不置位人工编辑保护。
Future<WikiPageDto> setWikiOpinion({required String slug, String? opinion}) =>
    RustLib.instance.api.crateApiSetWikiOpinion(slug: slug, opinion: opinion);

/// 与某页相关的人物关系（双向：作为人物方或作为事情/项目方）
Future<List<RelationDto>> listRelationsForPage({required String slug}) =>
    RustLib.instance.api.crateApiListRelationsForPage(slug: slug);

/// 全部人物关系（备用：未来人物视图）
Future<List<RelationDto>> listRelations() =>
    RustLib.instance.api.crateApiListRelations();

/// 手动添加/刷新一条人物关系（应用内修复合用；一般由 AI 草拟、用户确认后生成）。
/// 两侧页面必须已存在；返回落库后的关系（含真实 id）。
Future<RelationDto> addRelation({
  required String fromSlug,
  required String toSlug,
  required String relation,
  String? note,
}) => RustLib.instance.api.crateApiAddRelation(
  fromSlug: fromSlug,
  toSlug: toSlug,
  relation: relation,
  note: note,
);

/// 删除一条人物关系（修正误识别时用）。返回是否真的删掉了。
Future<bool> deleteRelation({required String id}) =>
    RustLib.instance.api.crateApiDeleteRelation(id: id);

/// 从 x.com / twitter.com 推文链接抓取长文（只解析 json，不写库）。
/// 是否入库由后续「保存」动作决定。
Future<TweetFetchDto> fetchTweet({required String url}) =>
    RustLib.instance.api.crateApiFetchTweet(url: url);

/// 把已抓取的推文内容保存为知识库页面（kind=source）并返回该页。
/// 只有用户点击「保存」才走这里入库存。
Future<WikiPageDto> saveTweetPage({
  required String tweetId,
  required String text,
  String? title,
  String? authorName,
  String? screenName,
}) => RustLib.instance.api.crateApiSaveTweetPage(
  tweetId: tweetId,
  text: text,
  title: title,
  authorName: authorName,
  screenName: screenName,
);

/// 把用户粘贴的纯文本保存为知识库页面（kind=topic），返回该页。
/// content_md 保留全文，不截断；tags 可选（页面保留「note」锚点标签）。
Future<WikiPageDto> saveTextPage({
  required String text,
  String? title,
  required List<String> tags,
}) => RustLib.instance.api.crateApiSaveTextPage(
  text: text,
  title: title,
  tags: tags,
);

/// 判断一个网址是否需要走专用抓取 API（当前：x.com/twitter.com 推文 → fxtwitter）。
/// 返回 "tweet" 或 "web"，供导入入口统一分发，避免前端各自猜测。
Future<String> guessImportKind({required String url}) =>
    RustLib.instance.api.crateApiGuessImportKind(url: url);

/// 针对一段抓取内容做一次性对话回复（不写库，供保存前与 AI 讨论内容）
Future<String> generateContentChat({
  required String content,
  required List<ContentChatMessageDto> messages,
}) => RustLib.instance.api.crateApiGenerateContentChat(
  content: content,
  messages: messages,
);

/// 当前推文抓取服务（设置页读取；当前仅支持 fxtwitter）
Future<String> getTweetFetchService() =>
    RustLib.instance.api.crateApiGetTweetFetchService();

/// 更新推文抓取服务（设置页保存）
Future<void> updateTweetFetchService({required String service}) =>
    RustLib.instance.api.crateApiUpdateTweetFetchService(service: service);

/// 按推文链接查知识库是否已存在对应页面（URL 查重）。
/// 已保存过则返回该页 DTO（UI 直接打开、不再抓取）；否则返回 None。
/// 链接格式不合法 / 未找到都算「不存在」。
Future<WikiPageDto?> findTweetSourcePage({required String url}) =>
    RustLib.instance.api.crateApiFindTweetSourcePage(url: url);

/// 读取主题偏好（默认深色 + 琥珀 + Inter + 16px，保留现有观感；
/// 编辑器覆盖层无则 None，UI 回落全局）
Future<ThemePrefsDto> getThemePrefs() =>
    RustLib.instance.api.crateApiGetThemePrefs();

/// 保存主题偏好（设置页「外观」保存）。编辑器覆盖层参数 None = 跟随全局，
/// 会从 app_meta 删除对应键（覆盖态回归继承态）。
Future<void> updateThemePrefs({
  required String mode,
  required String preset,
  required String font,
  required double fontSize,
  String? editorFont,
  double? editorFontSize,
  double? editorLineHeight,
}) => RustLib.instance.api.crateApiUpdateThemePrefs(
  mode: mode,
  preset: preset,
  font: font,
  fontSize: fontSize,
  editorFont: editorFont,
  editorFontSize: editorFontSize,
  editorLineHeight: editorLineHeight,
);

/// 列出待办（status 过滤：open/done/archived；None 时列出 open+done）
Future<List<TodoDto>> listTodos({String? status}) =>
    RustLib.instance.api.crateApiListTodos(status: status);

/// 新建待办（用户手动创建，直接生效）
Future<TodoDto> createTodo({
  required String title,
  String? dueAt,
  String? priority,
  String? relatedWikiSlug,
  String? note,
}) => RustLib.instance.api.crateApiCreateTodo(
  title: title,
  dueAt: dueAt,
  priority: priority,
  relatedWikiSlug: relatedWikiSlug,
  note: note,
);

/// 更新待办状态（open/done/archived）
Future<void> updateTodoStatus({required String id, required String status}) =>
    RustLib.instance.api.crateApiUpdateTodoStatus(id: id, status: status);

/// 打开待办对应的可讨论工作项；无关联页时按需创建并回写关联。
Future<WikiPageDto> openTodoWorkItem({required String id}) =>
    RustLib.instance.api.crateApiOpenTodoWorkItem(id: id);

/// 更新待办的可编辑字段（标题 / 补充 / 优先级 / 截止时间）。
/// 可选字段传 None 表示清除（如结束拖延、去掉截止时间）。
Future<void> updateTodo({
  required String id,
  required String title,
  String? note,
  String? priority,
  String? dueAt,
}) => RustLib.instance.api.crateApiUpdateTodo(
  id: id,
  title: title,
  note: note,
  priority: priority,
  dueAt: dueAt,
);

/// 删除一条待办
Future<bool> deleteTodo({required String id}) =>
    RustLib.instance.api.crateApiDeleteTodo(id: id);

/// 抓取任意 URL 的内容（推文走 fxtwitter，普通页面走 HTML 文本提取）。
/// 只解析不写库，由后续「保存」动作决定。
Future<ImportUrlDto> fetchImportUrl({required String url}) =>
    RustLib.instance.api.crateApiFetchImportUrl(url: url);

/// 把抓取到的 URL 内容保存为知识库页面（kind=source，带 source_url 溯源）。
/// 用户点击「保存」才走这里入库。
Future<WikiPageDto> saveImportedPage({
  required String title,
  required String contentMd,
  required String sourceUrl,
  required String sourceKind,
  required List<String> tags,
}) => RustLib.instance.api.crateApiSaveImportedPage(
  title: title,
  contentMd: contentMd,
  sourceUrl: sourceUrl,
  sourceKind: sourceKind,
  tags: tags,
);

/// 获取（不存在则创建）某个知识页的处理会话，返回会话 DTO。
/// 页内 AI 聊天通过该会话进行；生成时自动注入页面内容。
Future<ConversationDto> ensureWikiPageChat({required String pageSlug}) =>
    RustLib.instance.api.crateApiEnsureWikiPageChat(pageSlug: pageSlug);

/// 删除一个知识页的处理会话（重建时用）
Future<void> archiveWikiPageChat({required String pageSlug}) =>
    RustLib.instance.api.crateApiArchiveWikiPageChat(pageSlug: pageSlug);

/// 枚举系统字体（Linux/macOS/Windows；fontdb 直接扫描，不 spawn 外部命令）。
Future<List<SystemFontFace>> listSystemFonts() =>
    RustLib.instance.api.crateApiListSystemFonts();

/// AI provider config DTO for Flutter settings page
class AiProviderConfigDto {
  final String id;
  final String name;
  final String providerType;
  final String baseUrl;
  final String model;
  final String apiKeySource;

  /// 明文密钥只在保存时上行；读取时不回传（用 api_key_source 判断是否已配置）
  final String apiKey;
  final bool isActive;
  final double temperature;
  final PlatformInt64? maxTokens;

  const AiProviderConfigDto({
    required this.id,
    required this.name,
    required this.providerType,
    required this.baseUrl,
    required this.model,
    required this.apiKeySource,
    required this.apiKey,
    required this.isActive,
    required this.temperature,
    this.maxTokens,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      providerType.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      apiKeySource.hashCode ^
      apiKey.hashCode ^
      isActive.hashCode ^
      temperature.hashCode ^
      maxTokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiProviderConfigDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          providerType == other.providerType &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          apiKeySource == other.apiKeySource &&
          apiKey == other.apiKey &&
          isActive == other.isActive &&
          temperature == other.temperature &&
          maxTokens == other.maxTokens;
}

/// Analysis result DTO
class AnalysisDto {
  final String eventType;
  final double confidence;
  final String summary;
  final List<String> clarifications;

  const AnalysisDto({
    required this.eventType,
    required this.confidence,
    required this.summary,
    required this.clarifications,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      confidence.hashCode ^
      summary.hashCode ^
      clarifications.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisDto &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          confidence == other.confidence &&
          summary == other.summary &&
          clarifications == other.clarifications;
}

/// Durable event-analysis queue counts for operational visibility.
class AnalysisJobStatsDto {
  final PlatformInt64 pending;
  final PlatformInt64 running;
  final PlatformInt64 retry;
  final PlatformInt64 succeeded;
  final PlatformInt64 failed;

  const AnalysisJobStatsDto({
    required this.pending,
    required this.running,
    required this.retry,
    required this.succeeded,
    required this.failed,
  });

  @override
  int get hashCode =>
      pending.hashCode ^
      running.hashCode ^
      retry.hashCode ^
      succeeded.hashCode ^
      failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisJobStatsDto &&
          runtimeType == other.runtimeType &&
          pending == other.pending &&
          running == other.running &&
          retry == other.retry &&
          succeeded == other.succeeded &&
          failed == other.failed;
}

/// 内容对话消息 DTO（临时讨论的一条消息）
class ContentChatMessageDto {
  final String role;
  final String content;

  const ContentChatMessageDto({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentChatMessageDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

/// Conversation DTO for Flutter
class ConversationDto {
  final String id;
  final String? title;
  final String? tag;
  final String createdAt;
  final String updatedAt;
  final int messageCount;
  final String? lastMessagePreview;
  final bool archived;
  final String? wikiPageSlug;

  const ConversationDto({
    required this.id,
    this.title,
    this.tag,
    required this.createdAt,
    required this.updatedAt,
    required this.messageCount,
    this.lastMessagePreview,
    required this.archived,
    this.wikiPageSlug,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      tag.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      messageCount.hashCode ^
      lastMessagePreview.hashCode ^
      archived.hashCode ^
      wikiPageSlug.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          tag == other.tag &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          messageCount == other.messageCount &&
          lastMessagePreview == other.lastMessagePreview &&
          archived == other.archived &&
          wikiPageSlug == other.wikiPageSlug;
}

class DailyEntryDto {
  final String eventId;
  final String? inputId;
  final String? messageId;
  final String rawText;
  final String source;
  final String eventStatus;
  final String recordedAt;

  const DailyEntryDto({
    required this.eventId,
    this.inputId,
    this.messageId,
    required this.rawText,
    required this.source,
    required this.eventStatus,
    required this.recordedAt,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      inputId.hashCode ^
      messageId.hashCode ^
      rawText.hashCode ^
      source.hashCode ^
      eventStatus.hashCode ^
      recordedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyEntryDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          inputId == other.inputId &&
          messageId == other.messageId &&
          rawText == other.rawText &&
          source == other.source &&
          eventStatus == other.eventStatus &&
          recordedAt == other.recordedAt;
}

class DailyOverviewDto {
  final String date;
  final List<DailyEntryDto> entries;
  final DailyReviewDto? review;
  final List<TodoDto> todos;

  const DailyOverviewDto({
    required this.date,
    required this.entries,
    this.review,
    required this.todos,
  });

  @override
  int get hashCode =>
      date.hashCode ^ entries.hashCode ^ review.hashCode ^ todos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyOverviewDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          entries == other.entries &&
          review == other.review &&
          todos == other.todos;
}

class DailyReviewDto {
  final String id;
  final String date;
  final String promptVersion;
  final String createdAt;
  final List<DailyReviewItemDto> accomplishments;
  final List<DailyReviewItemDto> ideasDecisions;
  final List<DailyReviewItemDto> peopleProjects;
  final List<DailyReviewItemDto> followUps;

  const DailyReviewDto({
    required this.id,
    required this.date,
    required this.promptVersion,
    required this.createdAt,
    required this.accomplishments,
    required this.ideasDecisions,
    required this.peopleProjects,
    required this.followUps,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      date.hashCode ^
      promptVersion.hashCode ^
      createdAt.hashCode ^
      accomplishments.hashCode ^
      ideasDecisions.hashCode ^
      peopleProjects.hashCode ^
      followUps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyReviewDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          date == other.date &&
          promptVersion == other.promptVersion &&
          createdAt == other.createdAt &&
          accomplishments == other.accomplishments &&
          ideasDecisions == other.ideasDecisions &&
          peopleProjects == other.peopleProjects &&
          followUps == other.followUps;
}

class DailyReviewItemDto {
  final String text;
  final List<String> sourceEventIds;

  const DailyReviewItemDto({required this.text, required this.sourceEventIds});

  @override
  int get hashCode => text.hashCode ^ sourceEventIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyReviewItemDto &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          sourceEventIds == other.sourceEventIds;
}

/// Daily token usage DTO for Flutter（每日 token 使用统计）
class DailyTokenUsageDto {
  final String date;
  final PlatformInt64 promptTokens;
  final PlatformInt64 completionTokens;
  final PlatformInt64 totalTokens;
  final PlatformInt64 callCount;

  const DailyTokenUsageDto({
    required this.date,
    required this.promptTokens,
    required this.completionTokens,
    required this.totalTokens,
    required this.callCount,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      promptTokens.hashCode ^
      completionTokens.hashCode ^
      totalTokens.hashCode ^
      callCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyTokenUsageDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens &&
          callCount == other.callCount;
}

class EntityFactDto {
  final String id;
  final String entityKind;
  final String entitySlug;
  final String factText;
  final String occurredAt;
  final PlatformInt64 confidence;
  final String sourceEventId;
  final String createdAt;
  final String lastSeenAt;

  const EntityFactDto({
    required this.id,
    required this.entityKind,
    required this.entitySlug,
    required this.factText,
    required this.occurredAt,
    required this.confidence,
    required this.sourceEventId,
    required this.createdAt,
    required this.lastSeenAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      entityKind.hashCode ^
      entitySlug.hashCode ^
      factText.hashCode ^
      occurredAt.hashCode ^
      confidence.hashCode ^
      sourceEventId.hashCode ^
      createdAt.hashCode ^
      lastSeenAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityFactDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          entityKind == other.entityKind &&
          entitySlug == other.entitySlug &&
          factText == other.factText &&
          occurredAt == other.occurredAt &&
          confidence == other.confidence &&
          sourceEventId == other.sourceEventId &&
          createdAt == other.createdAt &&
          lastSeenAt == other.lastSeenAt;
}

class EntityMergeStatusDto {
  final String sourceSlug;
  final String targetSlug;
  final String entityKind;
  final String createdAt;

  const EntityMergeStatusDto({
    required this.sourceSlug,
    required this.targetSlug,
    required this.entityKind,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      sourceSlug.hashCode ^
      targetSlug.hashCode ^
      entityKind.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityMergeStatusDto &&
          runtimeType == other.runtimeType &&
          sourceSlug == other.sourceSlug &&
          targetSlug == other.targetSlug &&
          entityKind == other.entityKind &&
          createdAt == other.createdAt;
}

class EventAnalysisDetailDto {
  final String eventId;
  final String rawText;
  final String source;
  final String recordedAt;
  final String eventStatus;
  final String jobStatus;
  final PlatformInt64 attempts;
  final String? lastError;
  final String availableAt;
  final String? promptVersion;
  final String? analysisCreatedAt;
  final String? schemaVersion;
  final String? eventType;
  final double? confidence;
  final String? summary;
  final List<String> clarifications;
  final List<String> people;
  final List<String> projects;
  final List<String> activities;
  final List<String> followUps;
  final bool? recordable;
  final String? kind;
  final bool effectiveRecordable;
  final String effectiveKind;
  final String recordabilitySource;

  const EventAnalysisDetailDto({
    required this.eventId,
    required this.rawText,
    required this.source,
    required this.recordedAt,
    required this.eventStatus,
    required this.jobStatus,
    required this.attempts,
    this.lastError,
    required this.availableAt,
    this.promptVersion,
    this.analysisCreatedAt,
    this.schemaVersion,
    this.eventType,
    this.confidence,
    this.summary,
    required this.clarifications,
    required this.people,
    required this.projects,
    required this.activities,
    required this.followUps,
    this.recordable,
    this.kind,
    required this.effectiveRecordable,
    required this.effectiveKind,
    required this.recordabilitySource,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      rawText.hashCode ^
      source.hashCode ^
      recordedAt.hashCode ^
      eventStatus.hashCode ^
      jobStatus.hashCode ^
      attempts.hashCode ^
      lastError.hashCode ^
      availableAt.hashCode ^
      promptVersion.hashCode ^
      analysisCreatedAt.hashCode ^
      schemaVersion.hashCode ^
      eventType.hashCode ^
      confidence.hashCode ^
      summary.hashCode ^
      clarifications.hashCode ^
      people.hashCode ^
      projects.hashCode ^
      activities.hashCode ^
      followUps.hashCode ^
      recordable.hashCode ^
      kind.hashCode ^
      effectiveRecordable.hashCode ^
      effectiveKind.hashCode ^
      recordabilitySource.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventAnalysisDetailDto &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          rawText == other.rawText &&
          source == other.source &&
          recordedAt == other.recordedAt &&
          eventStatus == other.eventStatus &&
          jobStatus == other.jobStatus &&
          attempts == other.attempts &&
          lastError == other.lastError &&
          availableAt == other.availableAt &&
          promptVersion == other.promptVersion &&
          analysisCreatedAt == other.analysisCreatedAt &&
          schemaVersion == other.schemaVersion &&
          eventType == other.eventType &&
          confidence == other.confidence &&
          summary == other.summary &&
          clarifications == other.clarifications &&
          people == other.people &&
          projects == other.projects &&
          activities == other.activities &&
          followUps == other.followUps &&
          recordable == other.recordable &&
          kind == other.kind &&
          effectiveRecordable == other.effectiveRecordable &&
          effectiveKind == other.effectiveKind &&
          recordabilitySource == other.recordabilitySource;
}

/// Event data transfer object for Flutter
class EventDto {
  final String id;
  final String rawText;
  final String recordedAt;
  final String occurredAt;
  final String source;
  final String status;

  const EventDto({
    required this.id,
    required this.rawText,
    required this.recordedAt,
    required this.occurredAt,
    required this.source,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rawText.hashCode ^
      recordedAt.hashCode ^
      occurredAt.hashCode ^
      source.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rawText == other.rawText &&
          recordedAt == other.recordedAt &&
          occurredAt == other.occurredAt &&
          source == other.source &&
          status == other.status;
}

/// 任意 URL 抓取结果 DTO（推文或普通页面，只解析不入库）
class ImportUrlDto {
  final String sourceUrl;

  /// "tweet" | "webpage"
  final String sourceKind;
  final String? title;
  final String contentMd;
  final String? authorName;
  final String? screenName;

  const ImportUrlDto({
    required this.sourceUrl,
    required this.sourceKind,
    this.title,
    required this.contentMd,
    this.authorName,
    this.screenName,
  });

  @override
  int get hashCode =>
      sourceUrl.hashCode ^
      sourceKind.hashCode ^
      title.hashCode ^
      contentMd.hashCode ^
      authorName.hashCode ^
      screenName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportUrlDto &&
          runtimeType == other.runtimeType &&
          sourceUrl == other.sourceUrl &&
          sourceKind == other.sourceKind &&
          title == other.title &&
          contentMd == other.contentMd &&
          authorName == other.authorName &&
          screenName == other.screenName;
}

class InputRecordDto {
  final String id;
  final String rawText;
  final String source;
  final String routeStatus;
  final String? idempotencyKey;
  final String? eventId;
  final String? messageId;
  final String? wikiPageSlug;
  final String? todoId;
  final String createdAt;
  final String updatedAt;

  const InputRecordDto({
    required this.id,
    required this.rawText,
    required this.source,
    required this.routeStatus,
    this.idempotencyKey,
    this.eventId,
    this.messageId,
    this.wikiPageSlug,
    this.todoId,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rawText.hashCode ^
      source.hashCode ^
      routeStatus.hashCode ^
      idempotencyKey.hashCode ^
      eventId.hashCode ^
      messageId.hashCode ^
      wikiPageSlug.hashCode ^
      todoId.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputRecordDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rawText == other.rawText &&
          source == other.source &&
          routeStatus == other.routeStatus &&
          idempotencyKey == other.idempotencyKey &&
          eventId == other.eventId &&
          messageId == other.messageId &&
          wikiPageSlug == other.wikiPageSlug &&
          todoId == other.todoId &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// Message DTO for Flutter
class MessageDto {
  final String id;
  final String conversationId;
  final String? parentMessageId;
  final String role;
  final String content;
  final String createdAt;

  const MessageDto({
    required this.id,
    required this.conversationId,
    this.parentMessageId,
    required this.role,
    required this.content,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      parentMessageId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          parentMessageId == other.parentMessageId &&
          role == other.role &&
          content == other.content &&
          createdAt == other.createdAt;
}

class MessageRecordabilityDto {
  final String messageId;
  final String eventId;
  final bool recordable;
  final String kind;
  final String source;
  final String jobStatus;
  final String? summary;

  const MessageRecordabilityDto({
    required this.messageId,
    required this.eventId,
    required this.recordable,
    required this.kind,
    required this.source,
    required this.jobStatus,
    this.summary,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      eventId.hashCode ^
      recordable.hashCode ^
      kind.hashCode ^
      source.hashCode ^
      jobStatus.hashCode ^
      summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageRecordabilityDto &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          eventId == other.eventId &&
          recordable == other.recordable &&
          kind == other.kind &&
          source == other.source &&
          jobStatus == other.jobStatus &&
          summary == other.summary;
}

class PendingActionDto {
  final String id;
  final String action;
  final String argsJson;
  final String createdAt;

  const PendingActionDto({
    required this.id,
    required this.action,
    required this.argsJson,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ action.hashCode ^ argsJson.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingActionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          action == other.action &&
          argsJson == other.argsJson &&
          createdAt == other.createdAt;
}

/// 一条人物关系 DTO（AI 从对话识别「人 ↔ 事情/项目」，用户确认后保存）
class RelationDto {
  final String id;
  final String fromSlug;
  final String fromKind;
  final String toSlug;
  final String toKind;
  final String relation;
  final String? note;
  final PlatformInt64 confidence;
  final String createdAt;
  final String lastSeenAt;

  const RelationDto({
    required this.id,
    required this.fromSlug,
    required this.fromKind,
    required this.toSlug,
    required this.toKind,
    required this.relation,
    this.note,
    required this.confidence,
    required this.createdAt,
    required this.lastSeenAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      fromSlug.hashCode ^
      fromKind.hashCode ^
      toSlug.hashCode ^
      toKind.hashCode ^
      relation.hashCode ^
      note.hashCode ^
      confidence.hashCode ^
      createdAt.hashCode ^
      lastSeenAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RelationDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          fromSlug == other.fromSlug &&
          fromKind == other.fromKind &&
          toSlug == other.toSlug &&
          toKind == other.toKind &&
          relation == other.relation &&
          note == other.note &&
          confidence == other.confidence &&
          createdAt == other.createdAt &&
          lastSeenAt == other.lastSeenAt;
}

/// Create a new conversation
/// 个人经验规则 DTO
class RuleDto {
  final String id;
  final String content;
  final String status;
  final String createdAt;

  const RuleDto({
    required this.id,
    required this.content,
    required this.status,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ content.hashCode ^ status.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuleDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          status == other.status &&
          createdAt == other.createdAt;
}

/// 一条系统字体字面。Dart 侧按家族去重、保留首选样式（Regular 优先）。
class SystemFontFace {
  final String family;
  final String file;
  final String style;

  const SystemFontFace({
    required this.family,
    required this.file,
    required this.style,
  });

  @override
  int get hashCode => family.hashCode ^ file.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SystemFontFace &&
          runtimeType == other.runtimeType &&
          family == other.family &&
          file == other.file &&
          style == other.style;
}

/// 主题偏好 DTO（设置页「外观」：模式 + 预设 + 字体 + 正文字号；存 app_meta。
/// 后三项为编辑器内容区覆盖层，None = 跟随全局，见两层覆盖模型）
class ThemePrefsDto {
  /// "light" | "dark" | "system"
  final String mode;

  /// 预设名，如 "amber" | "indigo" | "aqua" | "violet"
  final String preset;

  /// 字体名，如 "inter" | "notoSansSc" | "notoSerifSc" | "system"
  final String font;

  /// 知识库正文字号（12.0–24.0，默认 16.0）
  final double fontSize;

  /// 编辑器（内容区）字体覆盖；None = 跟随全局
  final String? editorFont;

  /// 编辑器（内容区）字号覆盖；None = 跟随全局
  final double? editorFontSize;

  /// 编辑器（内容区）行距覆盖；None = 跟随全局
  final double? editorLineHeight;

  const ThemePrefsDto({
    required this.mode,
    required this.preset,
    required this.font,
    required this.fontSize,
    this.editorFont,
    this.editorFontSize,
    this.editorLineHeight,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      preset.hashCode ^
      font.hashCode ^
      fontSize.hashCode ^
      editorFont.hashCode ^
      editorFontSize.hashCode ^
      editorLineHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemePrefsDto &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          preset == other.preset &&
          font == other.font &&
          fontSize == other.fontSize &&
          editorFont == other.editorFont &&
          editorFontSize == other.editorFontSize &&
          editorLineHeight == other.editorLineHeight;
}

/// 待办 DTO
class TodoDto {
  final String id;
  final String title;
  final String status;
  final String priority;
  final String? dueAt;
  final String? relatedEventId;
  final String? relatedWikiSlug;
  final String? note;
  final String createdAt;
  final String updatedAt;

  const TodoDto({
    required this.id,
    required this.title,
    required this.status,
    required this.priority,
    this.dueAt,
    this.relatedEventId,
    this.relatedWikiSlug,
    this.note,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      dueAt.hashCode ^
      relatedEventId.hashCode ^
      relatedWikiSlug.hashCode ^
      note.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          status == other.status &&
          priority == other.priority &&
          dueAt == other.dueAt &&
          relatedEventId == other.relatedEventId &&
          relatedWikiSlug == other.relatedWikiSlug &&
          note == other.note &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 抓取的推文内容 DTO（只解析，不入库）
class TweetFetchDto {
  final String tweetId;
  final String url;
  final String text;

  /// 文章型推文的标题（article.title），普通推文为 None
  final String? title;
  final String? authorName;
  final String? screenName;

  const TweetFetchDto({
    required this.tweetId,
    required this.url,
    required this.text,
    this.title,
    this.authorName,
    this.screenName,
  });

  @override
  int get hashCode =>
      tweetId.hashCode ^
      url.hashCode ^
      text.hashCode ^
      title.hashCode ^
      authorName.hashCode ^
      screenName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TweetFetchDto &&
          runtimeType == other.runtimeType &&
          tweetId == other.tweetId &&
          url == other.url &&
          text == other.text &&
          title == other.title &&
          authorName == other.authorName &&
          screenName == other.screenName;
}

/// Wiki page data transfer object for Flutter（知识库浏览）
class WikiPageDto {
  final String id;
  final String slug;
  final String kind;
  final String title;
  final String summary;
  final String contentMd;
  final List<String> tags;
  final List<String> sourceEventIds;
  final PlatformInt64 evidenceCount;
  final String firstSeenAt;
  final String lastSeenAt;
  final String status;
  final String createdAt;
  final String updatedAt;
  final String? sourceUrl;

  /// 来源/用途分区：imported（素材库）/ network（人物项目）/ insight（知识沉淀）/ derivative（派生产物）
  final String area;

  /// 派生产物指向的原页面 slug（仅 derivative 有值）
  final String? basedOn;

  /// 派生产物的加工类型（总结/提炼观点/抖音文案…，仅 derivative 有值）
  final String? contentType;

  /// 最近一次人工编辑正文的时间（非空 ⇔ 该页由人工持有，digest 不整篇覆盖）
  final String? humanEditedAt;

  /// 素材页观点评价：Some("endorse")/Some("reject")/None=未表态（缺省认可）
  final String? opinion;

  const WikiPageDto({
    required this.id,
    required this.slug,
    required this.kind,
    required this.title,
    required this.summary,
    required this.contentMd,
    required this.tags,
    required this.sourceEventIds,
    required this.evidenceCount,
    required this.firstSeenAt,
    required this.lastSeenAt,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
    this.sourceUrl,
    required this.area,
    this.basedOn,
    this.contentType,
    this.humanEditedAt,
    this.opinion,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      slug.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      contentMd.hashCode ^
      tags.hashCode ^
      sourceEventIds.hashCode ^
      evidenceCount.hashCode ^
      firstSeenAt.hashCode ^
      lastSeenAt.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      sourceUrl.hashCode ^
      area.hashCode ^
      basedOn.hashCode ^
      contentType.hashCode ^
      humanEditedAt.hashCode ^
      opinion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WikiPageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          slug == other.slug &&
          kind == other.kind &&
          title == other.title &&
          summary == other.summary &&
          contentMd == other.contentMd &&
          tags == other.tags &&
          sourceEventIds == other.sourceEventIds &&
          evidenceCount == other.evidenceCount &&
          firstSeenAt == other.firstSeenAt &&
          lastSeenAt == other.lastSeenAt &&
          status == other.status &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          sourceUrl == other.sourceUrl &&
          area == other.area &&
          basedOn == other.basedOn &&
          contentType == other.contentType &&
          humanEditedAt == other.humanEditedAt &&
          opinion == other.opinion;
}
