// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Initialize the bridge with database path
Future<String> initBridge({String? databasePath}) =>
    RustLib.instance.api.crateApiInitBridge(databasePath: databasePath);

/// Record a new event
Future<EventDto> recordEvent({required String rawText}) =>
    RustLib.instance.api.crateApiRecordEvent(rawText: rawText);

/// List all events
Future<List<EventDto>> listEvents() =>
    RustLib.instance.api.crateApiListEvents();

/// List completed analyses
Future<List<AnalysisDto>> listAnalyses() =>
    RustLib.instance.api.crateApiListAnalyses();

/// Get active AI provider info
Future<String?> getAiProvider() => RustLib.instance.api.crateApiGetAiProvider();

/// Get the active AI provider full config (for settings page prefill)
Future<AiProviderConfigDto?> getAiProviderConfig() =>
    RustLib.instance.api.crateApiGetAiProviderConfig();

/// Upsert the active AI provider config (settings page save)
Future<void> updateAiProviderConfig({
  required String baseUrl,
  required String model,
  required String apiKey,
}) => RustLib.instance.api.crateApiUpdateAiProviderConfig(
  baseUrl: baseUrl,
  model: model,
  apiKey: apiKey,
);

/// Trigger AI analysis for pending events
/// Returns "success" or "error: <message>"
Future<String> triggerAnalysis() =>
    RustLib.instance.api.crateApiTriggerAnalysis();

/// Create a new conversation
Future<ConversationDto> createConversation({String? title, String? tag}) =>
    RustLib.instance.api.crateApiCreateConversation(title: title, tag: tag);

/// List all non-archived conversations
Future<List<ConversationDto>> listConversations() =>
    RustLib.instance.api.crateApiListConversations();

/// List archived conversations
Future<List<ConversationDto>> listArchivedConversations() =>
    RustLib.instance.api.crateApiListArchivedConversations();

/// Rename a conversation
Future<void> renameConversation({
  required String conversationId,
  required String title,
}) => RustLib.instance.api.crateApiRenameConversation(
  conversationId: conversationId,
  title: title,
);

/// Archive or unarchive a conversation
Future<void> setConversationArchived({
  required String conversationId,
  required bool archived,
}) => RustLib.instance.api.crateApiSetConversationArchived(
  conversationId: conversationId,
  archived: archived,
);

/// Get a specific conversation
Future<ConversationDto?> getConversation({required String conversationId}) =>
    RustLib.instance.api.crateApiGetConversation(
      conversationId: conversationId,
    );

/// Send a message in a conversation
Future<MessageDto> sendMessage({
  required String conversationId,
  required String role,
  required String content,
  String? parentMessageId,
}) => RustLib.instance.api.crateApiSendMessage(
  conversationId: conversationId,
  role: role,
  content: content,
  parentMessageId: parentMessageId,
);

/// List messages in a conversation
Future<List<MessageDto>> listMessages({required String conversationId}) =>
    RustLib.instance.api.crateApiListMessages(conversationId: conversationId);

/// Get child messages of a specific message (for branching conversations)
Future<List<MessageDto>> getChildMessages({required String parentId}) =>
    RustLib.instance.api.crateApiGetChildMessages(parentId: parentId);

/// Get the message chain from root to a specific message
Future<List<MessageDto>> getMessageChain({required String messageId}) =>
    RustLib.instance.api.crateApiGetMessageChain(messageId: messageId);

/// Generate AI reply for a conversation
Future<String> generateReply({
  required String conversationId,
  String? providerType,
  String? memoryType,
  int? memoryWindowSize,
}) => RustLib.instance.api.crateApiGenerateReply(
  conversationId: conversationId,
  providerType: providerType,
  memoryType: memoryType,
  memoryWindowSize: memoryWindowSize,
);

/// 获取最近 N 天的每日 token 用量统计（含当天，日期倒序）
Future<List<DailyTokenUsageDto>> getDailyTokenUsage({required int days}) =>
    RustLib.instance.api.crateApiGetDailyTokenUsage(days: days);

/// List wiki pages（可过滤 kind）；kind 为 None 时列出全部
Future<List<WikiPageDto>> listWikiPages({String? kind}) =>
    RustLib.instance.api.crateApiListWikiPages(kind: kind);

/// Get a single wiki page by slug
Future<WikiPageDto?> getWikiPage({required String slug}) =>
    RustLib.instance.api.crateApiGetWikiPage(slug: slug);

/// 从 x.com / twitter.com 推文链接抓取长文（只解析 json，不写库）。
/// 是否入库由后续「保存」动作决定。
Future<TweetFetchDto> fetchTweet({required String url}) =>
    RustLib.instance.api.crateApiFetchTweet(url: url);

/// 把已抓取的推文内容保存为知识库页面（kind=source）并返回该页。
/// 只有用户点击「保存」才走这里入库存。
Future<WikiPageDto> saveTweetPage({
  required String tweetId,
  required String text,
  String? title,
  String? authorName,
  String? screenName,
}) => RustLib.instance.api.crateApiSaveTweetPage(
  tweetId: tweetId,
  text: text,
  title: title,
  authorName: authorName,
  screenName: screenName,
);

/// 针对一段抓取内容做一次性对话回复（不写库，供保存前与 AI 讨论内容）
Future<String> generateContentChat({
  required String content,
  required List<ContentChatMessageDto> messages,
}) => RustLib.instance.api.crateApiGenerateContentChat(
  content: content,
  messages: messages,
);

/// 当前推文抓取服务（设置页读取；当前仅支持 fxtwitter）
Future<String> getTweetFetchService() =>
    RustLib.instance.api.crateApiGetTweetFetchService();

/// 更新推文抓取服务（设置页保存）
Future<void> updateTweetFetchService({required String service}) =>
    RustLib.instance.api.crateApiUpdateTweetFetchService(service: service);

/// 按推文链接查知识库是否已存在对应页面（URL 查重）。
/// 已保存过则返回该页 DTO（UI 直接打开、不再抓取）；否则返回 None。
/// 链接格式不合法 / 未找到都算「不存在」。
Future<WikiPageDto?> findTweetSourcePage({required String url}) =>
    RustLib.instance.api.crateApiFindTweetSourcePage(url: url);

/// 读取主题偏好（默认深色 + 琥珀，保留现有观感）
Future<ThemePrefsDto> getThemePrefs() =>
    RustLib.instance.api.crateApiGetThemePrefs();

/// 保存主题偏好（设置页「外观」保存）
Future<void> updateThemePrefs({required String mode, required String preset}) =>
    RustLib.instance.api.crateApiUpdateThemePrefs(mode: mode, preset: preset);

/// AI provider config DTO for Flutter settings page
class AiProviderConfigDto {
  final String providerType;
  final String baseUrl;
  final String model;
  final String apiKey;

  const AiProviderConfigDto({
    required this.providerType,
    required this.baseUrl,
    required this.model,
    required this.apiKey,
  });

  @override
  int get hashCode =>
      providerType.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      apiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiProviderConfigDto &&
          runtimeType == other.runtimeType &&
          providerType == other.providerType &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          apiKey == other.apiKey;
}

/// Analysis result DTO
class AnalysisDto {
  final String eventType;
  final double confidence;
  final String summary;
  final List<String> clarifications;

  const AnalysisDto({
    required this.eventType,
    required this.confidence,
    required this.summary,
    required this.clarifications,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      confidence.hashCode ^
      summary.hashCode ^
      clarifications.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisDto &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          confidence == other.confidence &&
          summary == other.summary &&
          clarifications == other.clarifications;
}

/// 内容对话消息 DTO（临时讨论的一条消息）
class ContentChatMessageDto {
  final String role;
  final String content;

  const ContentChatMessageDto({required this.role, required this.content});

  @override
  int get hashCode => role.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentChatMessageDto &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content;
}

/// Conversation DTO for Flutter
class ConversationDto {
  final String id;
  final String? title;
  final String? tag;
  final String createdAt;
  final String updatedAt;
  final int messageCount;
  final String? lastMessagePreview;
  final bool archived;

  const ConversationDto({
    required this.id,
    this.title,
    this.tag,
    required this.createdAt,
    required this.updatedAt,
    required this.messageCount,
    this.lastMessagePreview,
    required this.archived,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      tag.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      messageCount.hashCode ^
      lastMessagePreview.hashCode ^
      archived.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConversationDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          tag == other.tag &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          messageCount == other.messageCount &&
          lastMessagePreview == other.lastMessagePreview &&
          archived == other.archived;
}

/// Daily token usage DTO for Flutter（每日 token 使用统计）
class DailyTokenUsageDto {
  final String date;
  final PlatformInt64 promptTokens;
  final PlatformInt64 completionTokens;
  final PlatformInt64 totalTokens;
  final PlatformInt64 callCount;

  const DailyTokenUsageDto({
    required this.date,
    required this.promptTokens,
    required this.completionTokens,
    required this.totalTokens,
    required this.callCount,
  });

  @override
  int get hashCode =>
      date.hashCode ^
      promptTokens.hashCode ^
      completionTokens.hashCode ^
      totalTokens.hashCode ^
      callCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyTokenUsageDto &&
          runtimeType == other.runtimeType &&
          date == other.date &&
          promptTokens == other.promptTokens &&
          completionTokens == other.completionTokens &&
          totalTokens == other.totalTokens &&
          callCount == other.callCount;
}

/// Event data transfer object for Flutter
class EventDto {
  final String id;
  final String rawText;
  final String recordedAt;
  final String occurredAt;
  final String source;
  final String status;

  const EventDto({
    required this.id,
    required this.rawText,
    required this.recordedAt,
    required this.occurredAt,
    required this.source,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      rawText.hashCode ^
      recordedAt.hashCode ^
      occurredAt.hashCode ^
      source.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EventDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          rawText == other.rawText &&
          recordedAt == other.recordedAt &&
          occurredAt == other.occurredAt &&
          source == other.source &&
          status == other.status;
}

/// Message DTO for Flutter
class MessageDto {
  final String id;
  final String conversationId;
  final String? parentMessageId;
  final String role;
  final String content;
  final String createdAt;

  const MessageDto({
    required this.id,
    required this.conversationId,
    this.parentMessageId,
    required this.role,
    required this.content,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      conversationId.hashCode ^
      parentMessageId.hashCode ^
      role.hashCode ^
      content.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          conversationId == other.conversationId &&
          parentMessageId == other.parentMessageId &&
          role == other.role &&
          content == other.content &&
          createdAt == other.createdAt;
}

/// 主题偏好 DTO（设置页「外观」：模式 + 预设；存 app_meta）
class ThemePrefsDto {
  /// "light" | "dark" | "system"
  final String mode;

  /// 预设名，如 "amber" | "indigo" | "aqua" | "violet"
  final String preset;

  const ThemePrefsDto({required this.mode, required this.preset});

  @override
  int get hashCode => mode.hashCode ^ preset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThemePrefsDto &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          preset == other.preset;
}

/// 抓取的推文内容 DTO（只解析，不入库）
class TweetFetchDto {
  final String tweetId;
  final String url;
  final String text;

  /// 文章型推文的标题（article.title），普通推文为 None
  final String? title;
  final String? authorName;
  final String? screenName;

  const TweetFetchDto({
    required this.tweetId,
    required this.url,
    required this.text,
    this.title,
    this.authorName,
    this.screenName,
  });

  @override
  int get hashCode =>
      tweetId.hashCode ^
      url.hashCode ^
      text.hashCode ^
      title.hashCode ^
      authorName.hashCode ^
      screenName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TweetFetchDto &&
          runtimeType == other.runtimeType &&
          tweetId == other.tweetId &&
          url == other.url &&
          text == other.text &&
          title == other.title &&
          authorName == other.authorName &&
          screenName == other.screenName;
}

/// Wiki page data transfer object for Flutter（知识库浏览）
class WikiPageDto {
  final String id;
  final String slug;
  final String kind;
  final String title;
  final String summary;
  final String contentMd;
  final List<String> tags;
  final List<String> sourceEventIds;
  final PlatformInt64 evidenceCount;
  final String firstSeenAt;
  final String lastSeenAt;
  final String status;
  final String createdAt;
  final String updatedAt;

  const WikiPageDto({
    required this.id,
    required this.slug,
    required this.kind,
    required this.title,
    required this.summary,
    required this.contentMd,
    required this.tags,
    required this.sourceEventIds,
    required this.evidenceCount,
    required this.firstSeenAt,
    required this.lastSeenAt,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      slug.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      summary.hashCode ^
      contentMd.hashCode ^
      tags.hashCode ^
      sourceEventIds.hashCode ^
      evidenceCount.hashCode ^
      firstSeenAt.hashCode ^
      lastSeenAt.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WikiPageDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          slug == other.slug &&
          kind == other.kind &&
          title == other.title &&
          summary == other.summary &&
          contentMd == other.contentMd &&
          tags == other.tags &&
          sourceEventIds == other.sourceEventIds &&
          evidenceCount == other.evidenceCount &&
          firstSeenAt == other.firstSeenAt &&
          lastSeenAt == other.lastSeenAt &&
          status == other.status &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
