// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiProviderConfigDto dco_decode_ai_provider_config_dto(dynamic raw);

  @protected
  AnalysisDto dco_decode_analysis_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiProviderConfigDto dco_decode_box_autoadd_ai_provider_config_dto(
    dynamic raw,
  );

  @protected
  ConversationDto dco_decode_box_autoadd_conversation_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WikiPageDto dco_decode_box_autoadd_wiki_page_dto(dynamic raw);

  @protected
  ContentChatMessageDto dco_decode_content_chat_message_dto(dynamic raw);

  @protected
  ConversationDto dco_decode_conversation_dto(dynamic raw);

  @protected
  DailyTokenUsageDto dco_decode_daily_token_usage_dto(dynamic raw);

  @protected
  EventDto dco_decode_event_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportUrlDto dco_decode_import_url_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiProviderConfigDto> dco_decode_list_ai_provider_config_dto(dynamic raw);

  @protected
  List<AnalysisDto> dco_decode_list_analysis_dto(dynamic raw);

  @protected
  List<ContentChatMessageDto> dco_decode_list_content_chat_message_dto(
    dynamic raw,
  );

  @protected
  List<ConversationDto> dco_decode_list_conversation_dto(dynamic raw);

  @protected
  List<DailyTokenUsageDto> dco_decode_list_daily_token_usage_dto(dynamic raw);

  @protected
  List<EventDto> dco_decode_list_event_dto(dynamic raw);

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RuleDto> dco_decode_list_rule_dto(dynamic raw);

  @protected
  List<TodoDto> dco_decode_list_todo_dto(dynamic raw);

  @protected
  List<WikiPageDto> dco_decode_list_wiki_page_dto(dynamic raw);

  @protected
  MessageDto dco_decode_message_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AiProviderConfigDto? dco_decode_opt_box_autoadd_ai_provider_config_dto(
    dynamic raw,
  );

  @protected
  ConversationDto? dco_decode_opt_box_autoadd_conversation_dto(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WikiPageDto? dco_decode_opt_box_autoadd_wiki_page_dto(dynamic raw);

  @protected
  RuleDto dco_decode_rule_dto(dynamic raw);

  @protected
  ThemePrefsDto dco_decode_theme_prefs_dto(dynamic raw);

  @protected
  TodoDto dco_decode_todo_dto(dynamic raw);

  @protected
  TweetFetchDto dco_decode_tweet_fetch_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WikiPageDto dco_decode_wiki_page_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiProviderConfigDto sse_decode_ai_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  AnalysisDto sse_decode_analysis_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiProviderConfigDto sse_decode_box_autoadd_ai_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDto sse_decode_box_autoadd_conversation_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WikiPageDto sse_decode_box_autoadd_wiki_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  ContentChatMessageDto sse_decode_content_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDto sse_decode_conversation_dto(SseDeserializer deserializer);

  @protected
  DailyTokenUsageDto sse_decode_daily_token_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  EventDto sse_decode_event_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportUrlDto sse_decode_import_url_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiProviderConfigDto> sse_decode_list_ai_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AnalysisDto> sse_decode_list_analysis_dto(SseDeserializer deserializer);

  @protected
  List<ContentChatMessageDto> sse_decode_list_content_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ConversationDto> sse_decode_list_conversation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DailyTokenUsageDto> sse_decode_list_daily_token_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EventDto> sse_decode_list_event_dto(SseDeserializer deserializer);

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RuleDto> sse_decode_list_rule_dto(SseDeserializer deserializer);

  @protected
  List<TodoDto> sse_decode_list_todo_dto(SseDeserializer deserializer);

  @protected
  List<WikiPageDto> sse_decode_list_wiki_page_dto(SseDeserializer deserializer);

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AiProviderConfigDto? sse_decode_opt_box_autoadd_ai_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDto? sse_decode_opt_box_autoadd_conversation_dto(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WikiPageDto? sse_decode_opt_box_autoadd_wiki_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  RuleDto sse_decode_rule_dto(SseDeserializer deserializer);

  @protected
  ThemePrefsDto sse_decode_theme_prefs_dto(SseDeserializer deserializer);

  @protected
  TodoDto sse_decode_todo_dto(SseDeserializer deserializer);

  @protected
  TweetFetchDto sse_decode_tweet_fetch_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WikiPageDto sse_decode_wiki_page_dto(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_ai_provider_config_dto>
  cst_encode_box_autoadd_ai_provider_config_dto(AiProviderConfigDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_ai_provider_config_dto();
    cst_api_fill_to_wire_ai_provider_config_dto(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_conversation_dto>
  cst_encode_box_autoadd_conversation_dto(ConversationDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_conversation_dto();
    cst_api_fill_to_wire_conversation_dto(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_32(cst_encode_u_32(raw));
  }

  @protected
  ffi.Pointer<wire_cst_wiki_page_dto> cst_encode_box_autoadd_wiki_page_dto(
    WikiPageDto raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_wiki_page_dto();
    cst_api_fill_to_wire_wiki_page_dto(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_ai_provider_config_dto>
  cst_encode_list_ai_provider_config_dto(List<AiProviderConfigDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_ai_provider_config_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_ai_provider_config_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_analysis_dto> cst_encode_list_analysis_dto(
    List<AnalysisDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_analysis_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_analysis_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_content_chat_message_dto>
  cst_encode_list_content_chat_message_dto(List<ContentChatMessageDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_content_chat_message_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_content_chat_message_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_conversation_dto> cst_encode_list_conversation_dto(
    List<ConversationDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_conversation_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_conversation_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_daily_token_usage_dto>
  cst_encode_list_daily_token_usage_dto(List<DailyTokenUsageDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_daily_token_usage_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_daily_token_usage_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_event_dto> cst_encode_list_event_dto(
    List<EventDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_event_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_event_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_message_dto> cst_encode_list_message_dto(
    List<MessageDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_message_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_message_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_rule_dto> cst_encode_list_rule_dto(
    List<RuleDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_rule_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_rule_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_todo_dto> cst_encode_list_todo_dto(
    List<TodoDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_todo_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_todo_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_wiki_page_dto> cst_encode_list_wiki_page_dto(
    List<WikiPageDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_wiki_page_dto(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_wiki_page_dto(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<wire_cst_ai_provider_config_dto>
  cst_encode_opt_box_autoadd_ai_provider_config_dto(AiProviderConfigDto? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_ai_provider_config_dto(raw);
  }

  @protected
  ffi.Pointer<wire_cst_conversation_dto>
  cst_encode_opt_box_autoadd_conversation_dto(ConversationDto? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_conversation_dto(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  ffi.Pointer<wire_cst_wiki_page_dto> cst_encode_opt_box_autoadd_wiki_page_dto(
    WikiPageDto? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? ffi.nullptr
        : cst_encode_box_autoadd_wiki_page_dto(raw);
  }

  @protected
  void cst_api_fill_to_wire_ai_provider_config_dto(
    AiProviderConfigDto apiObj,
    wire_cst_ai_provider_config_dto wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.provider_type = cst_encode_String(apiObj.providerType);
    wireObj.base_url = cst_encode_String(apiObj.baseUrl);
    wireObj.model = cst_encode_String(apiObj.model);
    wireObj.api_key_source = cst_encode_String(apiObj.apiKeySource);
    wireObj.api_key = cst_encode_String(apiObj.apiKey);
    wireObj.is_active = cst_encode_bool(apiObj.isActive);
    wireObj.temperature = cst_encode_f_64(apiObj.temperature);
    wireObj.max_tokens = cst_encode_opt_box_autoadd_i_64(apiObj.maxTokens);
  }

  @protected
  void cst_api_fill_to_wire_analysis_dto(
    AnalysisDto apiObj,
    wire_cst_analysis_dto wireObj,
  ) {
    wireObj.event_type = cst_encode_String(apiObj.eventType);
    wireObj.confidence = cst_encode_f_64(apiObj.confidence);
    wireObj.summary = cst_encode_String(apiObj.summary);
    wireObj.clarifications = cst_encode_list_String(apiObj.clarifications);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_ai_provider_config_dto(
    AiProviderConfigDto apiObj,
    ffi.Pointer<wire_cst_ai_provider_config_dto> wireObj,
  ) {
    cst_api_fill_to_wire_ai_provider_config_dto(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_conversation_dto(
    ConversationDto apiObj,
    ffi.Pointer<wire_cst_conversation_dto> wireObj,
  ) {
    cst_api_fill_to_wire_conversation_dto(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_wiki_page_dto(
    WikiPageDto apiObj,
    ffi.Pointer<wire_cst_wiki_page_dto> wireObj,
  ) {
    cst_api_fill_to_wire_wiki_page_dto(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_content_chat_message_dto(
    ContentChatMessageDto apiObj,
    wire_cst_content_chat_message_dto wireObj,
  ) {
    wireObj.role = cst_encode_String(apiObj.role);
    wireObj.content = cst_encode_String(apiObj.content);
  }

  @protected
  void cst_api_fill_to_wire_conversation_dto(
    ConversationDto apiObj,
    wire_cst_conversation_dto wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.title = cst_encode_opt_String(apiObj.title);
    wireObj.tag = cst_encode_opt_String(apiObj.tag);
    wireObj.created_at = cst_encode_String(apiObj.createdAt);
    wireObj.updated_at = cst_encode_String(apiObj.updatedAt);
    wireObj.message_count = cst_encode_i_32(apiObj.messageCount);
    wireObj.last_message_preview = cst_encode_opt_String(
      apiObj.lastMessagePreview,
    );
    wireObj.archived = cst_encode_bool(apiObj.archived);
    wireObj.wiki_page_slug = cst_encode_opt_String(apiObj.wikiPageSlug);
  }

  @protected
  void cst_api_fill_to_wire_daily_token_usage_dto(
    DailyTokenUsageDto apiObj,
    wire_cst_daily_token_usage_dto wireObj,
  ) {
    wireObj.date = cst_encode_String(apiObj.date);
    wireObj.prompt_tokens = cst_encode_i_64(apiObj.promptTokens);
    wireObj.completion_tokens = cst_encode_i_64(apiObj.completionTokens);
    wireObj.total_tokens = cst_encode_i_64(apiObj.totalTokens);
    wireObj.call_count = cst_encode_i_64(apiObj.callCount);
  }

  @protected
  void cst_api_fill_to_wire_event_dto(
    EventDto apiObj,
    wire_cst_event_dto wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.raw_text = cst_encode_String(apiObj.rawText);
    wireObj.recorded_at = cst_encode_String(apiObj.recordedAt);
    wireObj.occurred_at = cst_encode_String(apiObj.occurredAt);
    wireObj.source = cst_encode_String(apiObj.source);
    wireObj.status = cst_encode_String(apiObj.status);
  }

  @protected
  void cst_api_fill_to_wire_import_url_dto(
    ImportUrlDto apiObj,
    wire_cst_import_url_dto wireObj,
  ) {
    wireObj.source_url = cst_encode_String(apiObj.sourceUrl);
    wireObj.source_kind = cst_encode_String(apiObj.sourceKind);
    wireObj.title = cst_encode_opt_String(apiObj.title);
    wireObj.content_md = cst_encode_String(apiObj.contentMd);
    wireObj.author_name = cst_encode_opt_String(apiObj.authorName);
    wireObj.screen_name = cst_encode_opt_String(apiObj.screenName);
  }

  @protected
  void cst_api_fill_to_wire_message_dto(
    MessageDto apiObj,
    wire_cst_message_dto wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.conversation_id = cst_encode_String(apiObj.conversationId);
    wireObj.parent_message_id = cst_encode_opt_String(apiObj.parentMessageId);
    wireObj.role = cst_encode_String(apiObj.role);
    wireObj.content = cst_encode_String(apiObj.content);
    wireObj.created_at = cst_encode_String(apiObj.createdAt);
  }

  @protected
  void cst_api_fill_to_wire_rule_dto(
    RuleDto apiObj,
    wire_cst_rule_dto wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.content = cst_encode_String(apiObj.content);
    wireObj.status = cst_encode_String(apiObj.status);
    wireObj.created_at = cst_encode_String(apiObj.createdAt);
  }

  @protected
  void cst_api_fill_to_wire_theme_prefs_dto(
    ThemePrefsDto apiObj,
    wire_cst_theme_prefs_dto wireObj,
  ) {
    wireObj.mode = cst_encode_String(apiObj.mode);
    wireObj.preset = cst_encode_String(apiObj.preset);
  }

  @protected
  void cst_api_fill_to_wire_todo_dto(
    TodoDto apiObj,
    wire_cst_todo_dto wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.status = cst_encode_String(apiObj.status);
    wireObj.priority = cst_encode_String(apiObj.priority);
    wireObj.due_at = cst_encode_opt_String(apiObj.dueAt);
    wireObj.related_event_id = cst_encode_opt_String(apiObj.relatedEventId);
    wireObj.related_wiki_slug = cst_encode_opt_String(apiObj.relatedWikiSlug);
    wireObj.note = cst_encode_opt_String(apiObj.note);
    wireObj.created_at = cst_encode_String(apiObj.createdAt);
    wireObj.updated_at = cst_encode_String(apiObj.updatedAt);
  }

  @protected
  void cst_api_fill_to_wire_tweet_fetch_dto(
    TweetFetchDto apiObj,
    wire_cst_tweet_fetch_dto wireObj,
  ) {
    wireObj.tweet_id = cst_encode_String(apiObj.tweetId);
    wireObj.url = cst_encode_String(apiObj.url);
    wireObj.text = cst_encode_String(apiObj.text);
    wireObj.title = cst_encode_opt_String(apiObj.title);
    wireObj.author_name = cst_encode_opt_String(apiObj.authorName);
    wireObj.screen_name = cst_encode_opt_String(apiObj.screenName);
  }

  @protected
  void cst_api_fill_to_wire_wiki_page_dto(
    WikiPageDto apiObj,
    wire_cst_wiki_page_dto wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.slug = cst_encode_String(apiObj.slug);
    wireObj.kind = cst_encode_String(apiObj.kind);
    wireObj.title = cst_encode_String(apiObj.title);
    wireObj.summary = cst_encode_String(apiObj.summary);
    wireObj.content_md = cst_encode_String(apiObj.contentMd);
    wireObj.tags = cst_encode_list_String(apiObj.tags);
    wireObj.source_event_ids = cst_encode_list_String(apiObj.sourceEventIds);
    wireObj.evidence_count = cst_encode_i_64(apiObj.evidenceCount);
    wireObj.first_seen_at = cst_encode_String(apiObj.firstSeenAt);
    wireObj.last_seen_at = cst_encode_String(apiObj.lastSeenAt);
    wireObj.status = cst_encode_String(apiObj.status);
    wireObj.created_at = cst_encode_String(apiObj.createdAt);
    wireObj.updated_at = cst_encode_String(apiObj.updatedAt);
    wireObj.source_url = cst_encode_opt_String(apiObj.sourceUrl);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_provider_config_dto(
    AiProviderConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_analysis_dto(AnalysisDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_provider_config_dto(
    AiProviderConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wiki_page_dto(
    WikiPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content_chat_message_dto(
    ContentChatMessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_daily_token_usage_dto(
    DailyTokenUsageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_event_dto(EventDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_url_dto(ImportUrlDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_provider_config_dto(
    List<AiProviderConfigDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_analysis_dto(
    List<AnalysisDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_content_chat_message_dto(
    List<ContentChatMessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_dto(
    List<ConversationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_daily_token_usage_dto(
    List<DailyTokenUsageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_event_dto(List<EventDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_rule_dto(List<RuleDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_todo_dto(List<TodoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wiki_page_dto(
    List<WikiPageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ai_provider_config_dto(
    AiProviderConfigDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_conversation_dto(
    ConversationDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_wiki_page_dto(
    WikiPageDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rule_dto(RuleDto self, SseSerializer serializer);

  @protected
  void sse_encode_theme_prefs_dto(ThemePrefsDto self, SseSerializer serializer);

  @protected
  void sse_encode_todo_dto(TodoDto self, SseSerializer serializer);

  @protected
  void sse_encode_tweet_fetch_dto(TweetFetchDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_wiki_page_dto(WikiPageDto self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  ffi.Pointer<wire_cst_ai_provider_config_dto>
  cst_new_box_autoadd_ai_provider_config_dto() {
    return _cst_new_box_autoadd_ai_provider_config_dto();
  }

  late final _cst_new_box_autoadd_ai_provider_config_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_ai_provider_config_dto> Function()
        >
      >('frbgen_elsewhen_ui_cst_new_box_autoadd_ai_provider_config_dto');
  late final _cst_new_box_autoadd_ai_provider_config_dto =
      _cst_new_box_autoadd_ai_provider_config_dtoPtr
          .asFunction<
            ffi.Pointer<wire_cst_ai_provider_config_dto> Function()
          >();

  ffi.Pointer<wire_cst_conversation_dto>
  cst_new_box_autoadd_conversation_dto() {
    return _cst_new_box_autoadd_conversation_dto();
  }

  late final _cst_new_box_autoadd_conversation_dtoPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_conversation_dto> Function()>
      >('frbgen_elsewhen_ui_cst_new_box_autoadd_conversation_dto');
  late final _cst_new_box_autoadd_conversation_dto =
      _cst_new_box_autoadd_conversation_dtoPtr
          .asFunction<ffi.Pointer<wire_cst_conversation_dto> Function()>();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_i_64(int value) {
    return _cst_new_box_autoadd_i_64(value);
  }

  late final _cst_new_box_autoadd_i_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_cst_new_box_autoadd_i_64',
      );
  late final _cst_new_box_autoadd_i_64 = _cst_new_box_autoadd_i_64Ptr
      .asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<ffi.Uint32> cst_new_box_autoadd_u_32(int value) {
    return _cst_new_box_autoadd_u_32(value);
  }

  late final _cst_new_box_autoadd_u_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint32> Function(ffi.Uint32)>>(
        'frbgen_elsewhen_ui_cst_new_box_autoadd_u_32',
      );
  late final _cst_new_box_autoadd_u_32 = _cst_new_box_autoadd_u_32Ptr
      .asFunction<ffi.Pointer<ffi.Uint32> Function(int)>();

  ffi.Pointer<wire_cst_wiki_page_dto> cst_new_box_autoadd_wiki_page_dto() {
    return _cst_new_box_autoadd_wiki_page_dto();
  }

  late final _cst_new_box_autoadd_wiki_page_dtoPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<wire_cst_wiki_page_dto> Function()>
      >('frbgen_elsewhen_ui_cst_new_box_autoadd_wiki_page_dto');
  late final _cst_new_box_autoadd_wiki_page_dto =
      _cst_new_box_autoadd_wiki_page_dtoPtr
          .asFunction<ffi.Pointer<wire_cst_wiki_page_dto> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_String');
  late final _cst_new_list_String = _cst_new_list_StringPtr
      .asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_ai_provider_config_dto>
  cst_new_list_ai_provider_config_dto(int len) {
    return _cst_new_list_ai_provider_config_dto(len);
  }

  late final _cst_new_list_ai_provider_config_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_ai_provider_config_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_ai_provider_config_dto');
  late final _cst_new_list_ai_provider_config_dto =
      _cst_new_list_ai_provider_config_dtoPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_ai_provider_config_dto> Function(int)
          >();

  ffi.Pointer<wire_cst_list_analysis_dto> cst_new_list_analysis_dto(int len) {
    return _cst_new_list_analysis_dto(len);
  }

  late final _cst_new_list_analysis_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_analysis_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_analysis_dto');
  late final _cst_new_list_analysis_dto = _cst_new_list_analysis_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_analysis_dto> Function(int)>();

  ffi.Pointer<wire_cst_list_content_chat_message_dto>
  cst_new_list_content_chat_message_dto(int len) {
    return _cst_new_list_content_chat_message_dto(len);
  }

  late final _cst_new_list_content_chat_message_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_content_chat_message_dto> Function(
            ffi.Int32,
          )
        >
      >('frbgen_elsewhen_ui_cst_new_list_content_chat_message_dto');
  late final _cst_new_list_content_chat_message_dto =
      _cst_new_list_content_chat_message_dtoPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_content_chat_message_dto> Function(int)
          >();

  ffi.Pointer<wire_cst_list_conversation_dto> cst_new_list_conversation_dto(
    int len,
  ) {
    return _cst_new_list_conversation_dto(len);
  }

  late final _cst_new_list_conversation_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_conversation_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_conversation_dto');
  late final _cst_new_list_conversation_dto = _cst_new_list_conversation_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_conversation_dto> Function(int)>();

  ffi.Pointer<wire_cst_list_daily_token_usage_dto>
  cst_new_list_daily_token_usage_dto(int len) {
    return _cst_new_list_daily_token_usage_dto(len);
  }

  late final _cst_new_list_daily_token_usage_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_daily_token_usage_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_daily_token_usage_dto');
  late final _cst_new_list_daily_token_usage_dto =
      _cst_new_list_daily_token_usage_dtoPtr
          .asFunction<
            ffi.Pointer<wire_cst_list_daily_token_usage_dto> Function(int)
          >();

  ffi.Pointer<wire_cst_list_event_dto> cst_new_list_event_dto(int len) {
    return _cst_new_list_event_dto(len);
  }

  late final _cst_new_list_event_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_event_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_event_dto');
  late final _cst_new_list_event_dto = _cst_new_list_event_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_event_dto> Function(int)>();

  ffi.Pointer<wire_cst_list_message_dto> cst_new_list_message_dto(int len) {
    return _cst_new_list_message_dto(len);
  }

  late final _cst_new_list_message_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_message_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_message_dto');
  late final _cst_new_list_message_dto = _cst_new_list_message_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_message_dto> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_rule_dto> cst_new_list_rule_dto(int len) {
    return _cst_new_list_rule_dto(len);
  }

  late final _cst_new_list_rule_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_rule_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_rule_dto');
  late final _cst_new_list_rule_dto = _cst_new_list_rule_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_rule_dto> Function(int)>();

  ffi.Pointer<wire_cst_list_todo_dto> cst_new_list_todo_dto(int len) {
    return _cst_new_list_todo_dto(len);
  }

  late final _cst_new_list_todo_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_todo_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_todo_dto');
  late final _cst_new_list_todo_dto = _cst_new_list_todo_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_todo_dto> Function(int)>();

  ffi.Pointer<wire_cst_list_wiki_page_dto> cst_new_list_wiki_page_dto(int len) {
    return _cst_new_list_wiki_page_dto(len);
  }

  late final _cst_new_list_wiki_page_dtoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_wiki_page_dto> Function(ffi.Int32)
        >
      >('frbgen_elsewhen_ui_cst_new_list_wiki_page_dto');
  late final _cst_new_list_wiki_page_dto = _cst_new_list_wiki_page_dtoPtr
      .asFunction<ffi.Pointer<wire_cst_list_wiki_page_dto> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__add_rule(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
  ) {
    return _wire__crate__api__add_rule(port_, content);
  }

  late final _wire__crate__api__add_rulePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__add_rule');
  late final _wire__crate__api__add_rule = _wire__crate__api__add_rulePtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__archive_wiki_page_chat(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> page_slug,
  ) {
    return _wire__crate__api__archive_wiki_page_chat(port_, page_slug);
  }

  late final _wire__crate__api__archive_wiki_page_chatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__archive_wiki_page_chat');
  late final _wire__crate__api__archive_wiki_page_chat =
      _wire__crate__api__archive_wiki_page_chatPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__create_conversation(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tag,
  ) {
    return _wire__crate__api__create_conversation(port_, title, tag);
  }

  late final _wire__crate__api__create_conversationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__create_conversation');
  late final _wire__crate__api__create_conversation =
      _wire__crate__api__create_conversationPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__create_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> due_at,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> priority,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> related_wiki_slug,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> note,
  ) {
    return _wire__crate__api__create_todo(
      port_,
      title,
      due_at,
      priority,
      related_wiki_slug,
      note,
    );
  }

  late final _wire__crate__api__create_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__create_todo');
  late final _wire__crate__api__create_todo = _wire__crate__api__create_todoPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__delete_ai_provider_config(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__delete_ai_provider_config(port_, id);
  }

  late final _wire__crate__api__delete_ai_provider_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__delete_ai_provider_config');
  late final _wire__crate__api__delete_ai_provider_config =
      _wire__crate__api__delete_ai_provider_configPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__delete_rule(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> rule_id,
  ) {
    return _wire__crate__api__delete_rule(port_, rule_id);
  }

  late final _wire__crate__api__delete_rulePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__delete_rule');
  late final _wire__crate__api__delete_rule = _wire__crate__api__delete_rulePtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__delete_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__delete_todo(port_, id);
  }

  late final _wire__crate__api__delete_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__delete_todo');
  late final _wire__crate__api__delete_todo = _wire__crate__api__delete_todoPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__ensure_wiki_page_chat(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> page_slug,
  ) {
    return _wire__crate__api__ensure_wiki_page_chat(port_, page_slug);
  }

  late final _wire__crate__api__ensure_wiki_page_chatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__ensure_wiki_page_chat');
  late final _wire__crate__api__ensure_wiki_page_chat =
      _wire__crate__api__ensure_wiki_page_chatPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__fetch_import_url(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
  ) {
    return _wire__crate__api__fetch_import_url(port_, url);
  }

  late final _wire__crate__api__fetch_import_urlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__fetch_import_url');
  late final _wire__crate__api__fetch_import_url =
      _wire__crate__api__fetch_import_urlPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__fetch_tweet(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
  ) {
    return _wire__crate__api__fetch_tweet(port_, url);
  }

  late final _wire__crate__api__fetch_tweetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__fetch_tweet');
  late final _wire__crate__api__fetch_tweet = _wire__crate__api__fetch_tweetPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__find_tweet_source_page(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
  ) {
    return _wire__crate__api__find_tweet_source_page(port_, url);
  }

  late final _wire__crate__api__find_tweet_source_pagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__find_tweet_source_page');
  late final _wire__crate__api__find_tweet_source_page =
      _wire__crate__api__find_tweet_source_pagePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__generate_content_chat(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
    ffi.Pointer<wire_cst_list_content_chat_message_dto> messages,
  ) {
    return _wire__crate__api__generate_content_chat(port_, content, messages);
  }

  late final _wire__crate__api__generate_content_chatPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_content_chat_message_dto>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__generate_content_chat');
  late final _wire__crate__api__generate_content_chat =
      _wire__crate__api__generate_content_chatPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_content_chat_message_dto>,
            )
          >();

  void wire__crate__api__generate_reply(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> conversation_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> provider_type,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> memory_type,
    ffi.Pointer<ffi.Uint32> memory_window_size,
  ) {
    return _wire__crate__api__generate_reply(
      port_,
      conversation_id,
      provider_type,
      memory_type,
      memory_window_size,
    );
  }

  late final _wire__crate__api__generate_replyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<ffi.Uint32>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__generate_reply');
  late final _wire__crate__api__generate_reply =
      _wire__crate__api__generate_replyPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<ffi.Uint32>,
            )
          >();

  void wire__crate__api__get_ai_provider(int port_) {
    return _wire__crate__api__get_ai_provider(port_);
  }

  late final _wire__crate__api__get_ai_providerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__get_ai_provider',
      );
  late final _wire__crate__api__get_ai_provider =
      _wire__crate__api__get_ai_providerPtr.asFunction<void Function(int)>();

  void wire__crate__api__get_ai_provider_config(int port_) {
    return _wire__crate__api__get_ai_provider_config(port_);
  }

  late final _wire__crate__api__get_ai_provider_configPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__get_ai_provider_config',
      );
  late final _wire__crate__api__get_ai_provider_config =
      _wire__crate__api__get_ai_provider_configPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__get_child_messages(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_id,
  ) {
    return _wire__crate__api__get_child_messages(port_, parent_id);
  }

  late final _wire__crate__api__get_child_messagesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__get_child_messages');
  late final _wire__crate__api__get_child_messages =
      _wire__crate__api__get_child_messagesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__get_conversation(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> conversation_id,
  ) {
    return _wire__crate__api__get_conversation(port_, conversation_id);
  }

  late final _wire__crate__api__get_conversationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__get_conversation');
  late final _wire__crate__api__get_conversation =
      _wire__crate__api__get_conversationPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__get_daily_token_usage(int port_, int days) {
    return _wire__crate__api__get_daily_token_usage(port_, days);
  }

  late final _wire__crate__api__get_daily_token_usagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Uint32)>>(
        'frbgen_elsewhen_ui_wire__crate__api__get_daily_token_usage',
      );
  late final _wire__crate__api__get_daily_token_usage =
      _wire__crate__api__get_daily_token_usagePtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__get_message_chain(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> message_id,
  ) {
    return _wire__crate__api__get_message_chain(port_, message_id);
  }

  late final _wire__crate__api__get_message_chainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__get_message_chain');
  late final _wire__crate__api__get_message_chain =
      _wire__crate__api__get_message_chainPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__get_theme_prefs(int port_) {
    return _wire__crate__api__get_theme_prefs(port_);
  }

  late final _wire__crate__api__get_theme_prefsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__get_theme_prefs',
      );
  late final _wire__crate__api__get_theme_prefs =
      _wire__crate__api__get_theme_prefsPtr.asFunction<void Function(int)>();

  void wire__crate__api__get_tweet_fetch_service(int port_) {
    return _wire__crate__api__get_tweet_fetch_service(port_);
  }

  late final _wire__crate__api__get_tweet_fetch_servicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__get_tweet_fetch_service',
      );
  late final _wire__crate__api__get_tweet_fetch_service =
      _wire__crate__api__get_tweet_fetch_servicePtr
          .asFunction<void Function(int)>();

  void wire__crate__api__get_wiki_page(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> slug,
  ) {
    return _wire__crate__api__get_wiki_page(port_, slug);
  }

  late final _wire__crate__api__get_wiki_pagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__get_wiki_page');
  late final _wire__crate__api__get_wiki_page =
      _wire__crate__api__get_wiki_pagePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__guess_import_kind(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
  ) {
    return _wire__crate__api__guess_import_kind(port_, url);
  }

  late final _wire__crate__api__guess_import_kindPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__guess_import_kind');
  late final _wire__crate__api__guess_import_kind =
      _wire__crate__api__guess_import_kindPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__init_bridge(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> database_path,
  ) {
    return _wire__crate__api__init_bridge(port_, database_path);
  }

  late final _wire__crate__api__init_bridgePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__init_bridge');
  late final _wire__crate__api__init_bridge = _wire__crate__api__init_bridgePtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__list_ai_provider_configs(int port_) {
    return _wire__crate__api__list_ai_provider_configs(port_);
  }

  late final _wire__crate__api__list_ai_provider_configsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__list_ai_provider_configs',
      );
  late final _wire__crate__api__list_ai_provider_configs =
      _wire__crate__api__list_ai_provider_configsPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__list_analyses(int port_) {
    return _wire__crate__api__list_analyses(port_);
  }

  late final _wire__crate__api__list_analysesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__list_analyses',
      );
  late final _wire__crate__api__list_analyses =
      _wire__crate__api__list_analysesPtr.asFunction<void Function(int)>();

  void wire__crate__api__list_archived_conversations(int port_) {
    return _wire__crate__api__list_archived_conversations(port_);
  }

  late final _wire__crate__api__list_archived_conversationsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__list_archived_conversations',
      );
  late final _wire__crate__api__list_archived_conversations =
      _wire__crate__api__list_archived_conversationsPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__list_conversations(int port_) {
    return _wire__crate__api__list_conversations(port_);
  }

  late final _wire__crate__api__list_conversationsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__list_conversations',
      );
  late final _wire__crate__api__list_conversations =
      _wire__crate__api__list_conversationsPtr.asFunction<void Function(int)>();

  void wire__crate__api__list_events(int port_) {
    return _wire__crate__api__list_events(port_);
  }

  late final _wire__crate__api__list_eventsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__list_events',
      );
  late final _wire__crate__api__list_events = _wire__crate__api__list_eventsPtr
      .asFunction<void Function(int)>();

  void wire__crate__api__list_messages(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> conversation_id,
  ) {
    return _wire__crate__api__list_messages(port_, conversation_id);
  }

  late final _wire__crate__api__list_messagesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__list_messages');
  late final _wire__crate__api__list_messages =
      _wire__crate__api__list_messagesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__list_rules(int port_) {
    return _wire__crate__api__list_rules(port_);
  }

  late final _wire__crate__api__list_rulesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__list_rules',
      );
  late final _wire__crate__api__list_rules = _wire__crate__api__list_rulesPtr
      .asFunction<void Function(int)>();

  void wire__crate__api__list_todos(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> status,
  ) {
    return _wire__crate__api__list_todos(port_, status);
  }

  late final _wire__crate__api__list_todosPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__list_todos');
  late final _wire__crate__api__list_todos = _wire__crate__api__list_todosPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__list_wiki_pages(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> kind,
  ) {
    return _wire__crate__api__list_wiki_pages(port_, kind);
  }

  late final _wire__crate__api__list_wiki_pagesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__list_wiki_pages');
  late final _wire__crate__api__list_wiki_pages =
      _wire__crate__api__list_wiki_pagesPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__record_event(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> raw_text,
  ) {
    return _wire__crate__api__record_event(port_, raw_text);
  }

  late final _wire__crate__api__record_eventPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__record_event');
  late final _wire__crate__api__record_event =
      _wire__crate__api__record_eventPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__rename_conversation(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> conversation_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
  ) {
    return _wire__crate__api__rename_conversation(
      port_,
      conversation_id,
      title,
    );
  }

  late final _wire__crate__api__rename_conversationPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__rename_conversation');
  late final _wire__crate__api__rename_conversation =
      _wire__crate__api__rename_conversationPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__save_ai_provider_config(
    int port_,
    ffi.Pointer<wire_cst_ai_provider_config_dto> provider,
  ) {
    return _wire__crate__api__save_ai_provider_config(port_, provider);
  }

  late final _wire__crate__api__save_ai_provider_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_ai_provider_config_dto>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__save_ai_provider_config');
  late final _wire__crate__api__save_ai_provider_config =
      _wire__crate__api__save_ai_provider_configPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_ai_provider_config_dto>)
          >();

  void wire__crate__api__save_imported_page(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> content_md,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> source_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> source_kind,
    ffi.Pointer<wire_cst_list_String> tags,
  ) {
    return _wire__crate__api__save_imported_page(
      port_,
      title,
      content_md,
      source_url,
      source_kind,
      tags,
    );
  }

  late final _wire__crate__api__save_imported_pagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__save_imported_page');
  late final _wire__crate__api__save_imported_page =
      _wire__crate__api__save_imported_pagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_String>,
            )
          >();

  void wire__crate__api__save_text_page(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_String> tags,
  ) {
    return _wire__crate__api__save_text_page(port_, text, title, tags);
  }

  late final _wire__crate__api__save_text_pagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__save_text_page');
  late final _wire__crate__api__save_text_page =
      _wire__crate__api__save_text_pagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_String>,
            )
          >();

  void wire__crate__api__save_tweet_page(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> tweet_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> author_name,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> screen_name,
  ) {
    return _wire__crate__api__save_tweet_page(
      port_,
      tweet_id,
      text,
      title,
      author_name,
      screen_name,
    );
  }

  late final _wire__crate__api__save_tweet_pagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__save_tweet_page');
  late final _wire__crate__api__save_tweet_page =
      _wire__crate__api__save_tweet_pagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__send_message(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> conversation_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> role,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_message_id,
  ) {
    return _wire__crate__api__send_message(
      port_,
      conversation_id,
      role,
      content,
      parent_message_id,
    );
  }

  late final _wire__crate__api__send_messagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__send_message');
  late final _wire__crate__api__send_message =
      _wire__crate__api__send_messagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__set_active_ai_provider_config(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
  ) {
    return _wire__crate__api__set_active_ai_provider_config(port_, id);
  }

  late final _wire__crate__api__set_active_ai_provider_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__set_active_ai_provider_config');
  late final _wire__crate__api__set_active_ai_provider_config =
      _wire__crate__api__set_active_ai_provider_configPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__set_conversation_archived(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> conversation_id,
    bool archived,
  ) {
    return _wire__crate__api__set_conversation_archived(
      port_,
      conversation_id,
      archived,
    );
  }

  late final _wire__crate__api__set_conversation_archivedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Bool,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__set_conversation_archived');
  late final _wire__crate__api__set_conversation_archived =
      _wire__crate__api__set_conversation_archivedPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, bool)
          >();

  void wire__crate__api__trigger_analysis(int port_) {
    return _wire__crate__api__trigger_analysis(port_);
  }

  late final _wire__crate__api__trigger_analysisPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_elsewhen_ui_wire__crate__api__trigger_analysis',
      );
  late final _wire__crate__api__trigger_analysis =
      _wire__crate__api__trigger_analysisPtr.asFunction<void Function(int)>();

  void wire__crate__api__update_ai_provider_config(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> model,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> api_key,
  ) {
    return _wire__crate__api__update_ai_provider_config(
      port_,
      base_url,
      model,
      api_key,
    );
  }

  late final _wire__crate__api__update_ai_provider_configPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__update_ai_provider_config');
  late final _wire__crate__api__update_ai_provider_config =
      _wire__crate__api__update_ai_provider_configPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__update_theme_prefs(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> mode,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> preset,
  ) {
    return _wire__crate__api__update_theme_prefs(port_, mode, preset);
  }

  late final _wire__crate__api__update_theme_prefsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__update_theme_prefs');
  late final _wire__crate__api__update_theme_prefs =
      _wire__crate__api__update_theme_prefsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__update_todo(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> note,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> priority,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> due_at,
  ) {
    return _wire__crate__api__update_todo(
      port_,
      id,
      title,
      note,
      priority,
      due_at,
    );
  }

  late final _wire__crate__api__update_todoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__update_todo');
  late final _wire__crate__api__update_todo = _wire__crate__api__update_todoPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        )
      >();

  void wire__crate__api__update_todo_status(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> status,
  ) {
    return _wire__crate__api__update_todo_status(port_, id, status);
  }

  late final _wire__crate__api__update_todo_statusPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__update_todo_status');
  late final _wire__crate__api__update_todo_status =
      _wire__crate__api__update_todo_statusPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__update_tweet_fetch_service(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> service,
  ) {
    return _wire__crate__api__update_tweet_fetch_service(port_, service);
  }

  late final _wire__crate__api__update_tweet_fetch_servicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__update_tweet_fetch_service');
  late final _wire__crate__api__update_tweet_fetch_service =
      _wire__crate__api__update_tweet_fetch_servicePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__update_wiki_tags(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> slug,
    ffi.Pointer<wire_cst_list_String> tags,
  ) {
    return _wire__crate__api__update_wiki_tags(port_, slug, tags);
  }

  late final _wire__crate__api__update_wiki_tagsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_String>,
          )
        >
      >('frbgen_elsewhen_ui_wire__crate__api__update_wiki_tags');
  late final _wire__crate__api__update_wiki_tags =
      _wire__crate__api__update_wiki_tagsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_String>,
            )
          >();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
  DartPort port_id,
  ffi.Pointer<ffi.Void> message,
);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
  DartDartPort port_id,
  ffi.Pointer<ffi.Void> message,
);

final class wire_cst_ai_provider_config_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> provider_type;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> model;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> api_key_source;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> api_key;

  @ffi.Bool()
  external bool is_active;

  @ffi.Double()
  external double temperature;

  external ffi.Pointer<ffi.Int64> max_tokens;

  static ffi.Pointer<wire_cst_ai_provider_config_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> provider_type,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> base_url,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> model,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> api_key_source,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> api_key,
    required bool is_active,
    required double temperature,
    required ffi.Pointer<ffi.Int64> max_tokens,
  }) => $allocator<wire_cst_ai_provider_config_dto>()
    ..ref.id = id
    ..ref.name = name
    ..ref.provider_type = provider_type
    ..ref.base_url = base_url
    ..ref.model = model
    ..ref.api_key_source = api_key_source
    ..ref.api_key = api_key
    ..ref.is_active = is_active
    ..ref.temperature = temperature
    ..ref.max_tokens = max_tokens;
}

final class wire_cst_analysis_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> event_type;

  @ffi.Double()
  external double confidence;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> summary;

  external ffi.Pointer<wire_cst_list_String> clarifications;

  static ffi.Pointer<wire_cst_analysis_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> event_type,
    required double confidence,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> summary,
    required ffi.Pointer<wire_cst_list_String> clarifications,
  }) => $allocator<wire_cst_analysis_dto>()
    ..ref.event_type = event_type
    ..ref.confidence = confidence
    ..ref.summary = summary
    ..ref.clarifications = clarifications;
}

final class wire_cst_content_chat_message_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> role;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> content;

  static ffi.Pointer<wire_cst_content_chat_message_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> role,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
  }) => $allocator<wire_cst_content_chat_message_dto>()
    ..ref.role = role
    ..ref.content = content;
}

final class wire_cst_conversation_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> tag;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> updated_at;

  @ffi.Int32()
  external int message_count;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> last_message_preview;

  @ffi.Bool()
  external bool archived;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> wiki_page_slug;

  static ffi.Pointer<wire_cst_conversation_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> tag,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> updated_at,
    required int message_count,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> last_message_preview,
    required bool archived,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> wiki_page_slug,
  }) => $allocator<wire_cst_conversation_dto>()
    ..ref.id = id
    ..ref.title = title
    ..ref.tag = tag
    ..ref.created_at = created_at
    ..ref.updated_at = updated_at
    ..ref.message_count = message_count
    ..ref.last_message_preview = last_message_preview
    ..ref.archived = archived
    ..ref.wiki_page_slug = wiki_page_slug;
}

final class wire_cst_daily_token_usage_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> date;

  @ffi.Int64()
  external int prompt_tokens;

  @ffi.Int64()
  external int completion_tokens;

  @ffi.Int64()
  external int total_tokens;

  @ffi.Int64()
  external int call_count;

  static ffi.Pointer<wire_cst_daily_token_usage_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> date,
    required int prompt_tokens,
    required int completion_tokens,
    required int total_tokens,
    required int call_count,
  }) => $allocator<wire_cst_daily_token_usage_dto>()
    ..ref.date = date
    ..ref.prompt_tokens = prompt_tokens
    ..ref.completion_tokens = completion_tokens
    ..ref.total_tokens = total_tokens
    ..ref.call_count = call_count;
}

final class wire_cst_event_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> raw_text;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> recorded_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> occurred_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> source;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status;

  static ffi.Pointer<wire_cst_event_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> raw_text,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> recorded_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> occurred_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> source,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> status,
  }) => $allocator<wire_cst_event_dto>()
    ..ref.id = id
    ..ref.raw_text = raw_text
    ..ref.recorded_at = recorded_at
    ..ref.occurred_at = occurred_at
    ..ref.source = source
    ..ref.status = status;
}

final class wire_cst_import_url_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> source_url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> source_kind;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> content_md;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> author_name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> screen_name;

  static ffi.Pointer<wire_cst_import_url_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> source_url,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> source_kind,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> content_md,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> author_name,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> screen_name,
  }) => $allocator<wire_cst_import_url_dto>()
    ..ref.source_url = source_url
    ..ref.source_kind = source_kind
    ..ref.title = title
    ..ref.content_md = content_md
    ..ref.author_name = author_name
    ..ref.screen_name = screen_name;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_String> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr,
    required int len,
  }) => $allocator<wire_cst_list_String>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_ai_provider_config_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_ai_provider_config_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_ai_provider_config_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_ai_provider_config_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_ai_provider_config_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_analysis_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_analysis_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_analysis_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_analysis_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_analysis_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_content_chat_message_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_content_chat_message_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_content_chat_message_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_content_chat_message_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_content_chat_message_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_conversation_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_conversation_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_conversation_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_conversation_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_conversation_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_daily_token_usage_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_daily_token_usage_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_daily_token_usage_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_daily_token_usage_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_daily_token_usage_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_event_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_event_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_event_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_event_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_event_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_message_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_message_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_message_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_message_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_message_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_prim_u_8_strict> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Uint8> ptr,
    required int len,
  }) => $allocator<wire_cst_list_prim_u_8_strict>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_rule_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_rule_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_rule_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_rule_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_rule_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_todo_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_todo_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_todo_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_todo_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_todo_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_list_wiki_page_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_wiki_page_dto> ptr;

  @ffi.Int32()
  external int len;

  static ffi.Pointer<wire_cst_list_wiki_page_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_wiki_page_dto> ptr,
    required int len,
  }) => $allocator<wire_cst_list_wiki_page_dto>()
    ..ref.ptr = ptr
    ..ref.len = len;
}

final class wire_cst_message_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> conversation_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_message_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> role;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> content;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at;

  static ffi.Pointer<wire_cst_message_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> conversation_id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> parent_message_id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> role,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at,
  }) => $allocator<wire_cst_message_dto>()
    ..ref.id = id
    ..ref.conversation_id = conversation_id
    ..ref.parent_message_id = parent_message_id
    ..ref.role = role
    ..ref.content = content
    ..ref.created_at = created_at;
}

final class wire_cst_rule_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> content;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at;

  static ffi.Pointer<wire_cst_rule_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> content,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> status,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at,
  }) => $allocator<wire_cst_rule_dto>()
    ..ref.id = id
    ..ref.content = content
    ..ref.status = status
    ..ref.created_at = created_at;
}

final class wire_cst_theme_prefs_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> mode;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> preset;

  static ffi.Pointer<wire_cst_theme_prefs_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> mode,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> preset,
  }) => $allocator<wire_cst_theme_prefs_dto>()
    ..ref.mode = mode
    ..ref.preset = preset;
}

final class wire_cst_todo_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> priority;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> due_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> related_event_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> related_wiki_slug;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> note;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> updated_at;

  static ffi.Pointer<wire_cst_todo_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> status,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> priority,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> due_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> related_event_id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> related_wiki_slug,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> note,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> updated_at,
  }) => $allocator<wire_cst_todo_dto>()
    ..ref.id = id
    ..ref.title = title
    ..ref.status = status
    ..ref.priority = priority
    ..ref.due_at = due_at
    ..ref.related_event_id = related_event_id
    ..ref.related_wiki_slug = related_wiki_slug
    ..ref.note = note
    ..ref.created_at = created_at
    ..ref.updated_at = updated_at;
}

final class wire_cst_tweet_fetch_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> tweet_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> text;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> author_name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> screen_name;

  static ffi.Pointer<wire_cst_tweet_fetch_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> tweet_id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> url,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> text,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> author_name,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> screen_name,
  }) => $allocator<wire_cst_tweet_fetch_dto>()
    ..ref.tweet_id = tweet_id
    ..ref.url = url
    ..ref.text = text
    ..ref.title = title
    ..ref.author_name = author_name
    ..ref.screen_name = screen_name;
}

final class wire_cst_wiki_page_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> slug;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> kind;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> title;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> summary;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> content_md;

  external ffi.Pointer<wire_cst_list_String> tags;

  external ffi.Pointer<wire_cst_list_String> source_event_ids;

  @ffi.Int64()
  external int evidence_count;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> first_seen_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> last_seen_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> updated_at;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> source_url;

  static ffi.Pointer<wire_cst_wiki_page_dto> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> id,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> slug,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> kind,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> title,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> summary,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> content_md,
    required ffi.Pointer<wire_cst_list_String> tags,
    required ffi.Pointer<wire_cst_list_String> source_event_ids,
    required int evidence_count,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> first_seen_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> last_seen_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> status,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> created_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> updated_at,
    required ffi.Pointer<wire_cst_list_prim_u_8_strict> source_url,
  }) => $allocator<wire_cst_wiki_page_dto>()
    ..ref.id = id
    ..ref.slug = slug
    ..ref.kind = kind
    ..ref.title = title
    ..ref.summary = summary
    ..ref.content_md = content_md
    ..ref.tags = tags
    ..ref.source_event_ids = source_event_ids
    ..ref.evidence_count = evidence_count
    ..ref.first_seen_at = first_seen_at
    ..ref.last_seen_at = last_seen_at
    ..ref.status = status
    ..ref.created_at = created_at
    ..ref.updated_at = updated_at
    ..ref.source_url = source_url;
}
