// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiProviderConfigDto dco_decode_ai_provider_config_dto(dynamic raw);

  @protected
  AnalysisDto dco_decode_analysis_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiProviderConfigDto dco_decode_box_autoadd_ai_provider_config_dto(
    dynamic raw,
  );

  @protected
  ConversationDto dco_decode_box_autoadd_conversation_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WikiPageDto dco_decode_box_autoadd_wiki_page_dto(dynamic raw);

  @protected
  ContentChatMessageDto dco_decode_content_chat_message_dto(dynamic raw);

  @protected
  ConversationDto dco_decode_conversation_dto(dynamic raw);

  @protected
  DailyTokenUsageDto dco_decode_daily_token_usage_dto(dynamic raw);

  @protected
  EventDto dco_decode_event_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AnalysisDto> dco_decode_list_analysis_dto(dynamic raw);

  @protected
  List<ContentChatMessageDto> dco_decode_list_content_chat_message_dto(
    dynamic raw,
  );

  @protected
  List<ConversationDto> dco_decode_list_conversation_dto(dynamic raw);

  @protected
  List<DailyTokenUsageDto> dco_decode_list_daily_token_usage_dto(dynamic raw);

  @protected
  List<EventDto> dco_decode_list_event_dto(dynamic raw);

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<WikiPageDto> dco_decode_list_wiki_page_dto(dynamic raw);

  @protected
  MessageDto dco_decode_message_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AiProviderConfigDto? dco_decode_opt_box_autoadd_ai_provider_config_dto(
    dynamic raw,
  );

  @protected
  ConversationDto? dco_decode_opt_box_autoadd_conversation_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WikiPageDto? dco_decode_opt_box_autoadd_wiki_page_dto(dynamic raw);

  @protected
  ThemePrefsDto dco_decode_theme_prefs_dto(dynamic raw);

  @protected
  TweetFetchDto dco_decode_tweet_fetch_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WikiPageDto dco_decode_wiki_page_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiProviderConfigDto sse_decode_ai_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  AnalysisDto sse_decode_analysis_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiProviderConfigDto sse_decode_box_autoadd_ai_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDto sse_decode_box_autoadd_conversation_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WikiPageDto sse_decode_box_autoadd_wiki_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  ContentChatMessageDto sse_decode_content_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDto sse_decode_conversation_dto(SseDeserializer deserializer);

  @protected
  DailyTokenUsageDto sse_decode_daily_token_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  EventDto sse_decode_event_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AnalysisDto> sse_decode_list_analysis_dto(SseDeserializer deserializer);

  @protected
  List<ContentChatMessageDto> sse_decode_list_content_chat_message_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ConversationDto> sse_decode_list_conversation_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DailyTokenUsageDto> sse_decode_list_daily_token_usage_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<EventDto> sse_decode_list_event_dto(SseDeserializer deserializer);

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<WikiPageDto> sse_decode_list_wiki_page_dto(SseDeserializer deserializer);

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AiProviderConfigDto? sse_decode_opt_box_autoadd_ai_provider_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConversationDto? sse_decode_opt_box_autoadd_conversation_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WikiPageDto? sse_decode_opt_box_autoadd_wiki_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  ThemePrefsDto sse_decode_theme_prefs_dto(SseDeserializer deserializer);

  @protected
  TweetFetchDto sse_decode_tweet_fetch_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WikiPageDto sse_decode_wiki_page_dto(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_ai_provider_config_dto(AiProviderConfigDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.providerType),
      cst_encode_String(raw.baseUrl),
      cst_encode_String(raw.model),
      cst_encode_String(raw.apiKey),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_analysis_dto(AnalysisDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.eventType),
      cst_encode_f_64(raw.confidence),
      cst_encode_String(raw.summary),
      cst_encode_list_String(raw.clarifications),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_box_autoadd_ai_provider_config_dto(AiProviderConfigDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_ai_provider_config_dto(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_conversation_dto(ConversationDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_conversation_dto(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_32(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_wiki_page_dto(WikiPageDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_wiki_page_dto(raw);
  }

  @protected
  JSAny cst_encode_content_chat_message_dto(ContentChatMessageDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.role),
      cst_encode_String(raw.content),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_conversation_dto(ConversationDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_opt_String(raw.title),
      cst_encode_opt_String(raw.tag),
      cst_encode_String(raw.createdAt),
      cst_encode_String(raw.updatedAt),
      cst_encode_i_32(raw.messageCount),
      cst_encode_opt_String(raw.lastMessagePreview),
      cst_encode_bool(raw.archived),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_daily_token_usage_dto(DailyTokenUsageDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.date),
      cst_encode_i_64(raw.promptTokens),
      cst_encode_i_64(raw.completionTokens),
      cst_encode_i_64(raw.totalTokens),
      cst_encode_i_64(raw.callCount),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_event_dto(EventDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.rawText),
      cst_encode_String(raw.recordedAt),
      cst_encode_String(raw.occurredAt),
      cst_encode_String(raw.source),
      cst_encode_String(raw.status),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_analysis_dto(List<AnalysisDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_analysis_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_content_chat_message_dto(
    List<ContentChatMessageDto> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_content_chat_message_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_conversation_dto(List<ConversationDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_conversation_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_daily_token_usage_dto(List<DailyTokenUsageDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_daily_token_usage_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_event_dto(List<EventDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_event_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_message_dto(List<MessageDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_message_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_wiki_page_dto(List<WikiPageDto> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_wiki_page_dto).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_message_dto(MessageDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.conversationId),
      cst_encode_opt_String(raw.parentMessageId),
      cst_encode_String(raw.role),
      cst_encode_String(raw.content),
      cst_encode_String(raw.createdAt),
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_ai_provider_config_dto(
    AiProviderConfigDto? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_ai_provider_config_dto(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_conversation_dto(ConversationDto? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_conversation_dto(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_wiki_page_dto(WikiPageDto? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_wiki_page_dto(raw);
  }

  @protected
  JSAny cst_encode_theme_prefs_dto(ThemePrefsDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.mode),
      cst_encode_String(raw.preset),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_tweet_fetch_dto(TweetFetchDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.tweetId),
      cst_encode_String(raw.url),
      cst_encode_String(raw.text),
      cst_encode_opt_String(raw.title),
      cst_encode_opt_String(raw.authorName),
      cst_encode_opt_String(raw.screenName),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_wiki_page_dto(WikiPageDto raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_String(raw.slug),
      cst_encode_String(raw.kind),
      cst_encode_String(raw.title),
      cst_encode_String(raw.summary),
      cst_encode_String(raw.contentMd),
      cst_encode_list_String(raw.tags),
      cst_encode_list_String(raw.sourceEventIds),
      cst_encode_i_64(raw.evidenceCount),
      cst_encode_String(raw.firstSeenAt),
      cst_encode_String(raw.lastSeenAt),
      cst_encode_String(raw.status),
      cst_encode_String(raw.createdAt),
      cst_encode_String(raw.updatedAt),
    ].jsify()!;
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_provider_config_dto(
    AiProviderConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_analysis_dto(AnalysisDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_provider_config_dto(
    AiProviderConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_wiki_page_dto(
    WikiPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_content_chat_message_dto(
    ContentChatMessageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_daily_token_usage_dto(
    DailyTokenUsageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_event_dto(EventDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_analysis_dto(
    List<AnalysisDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_content_chat_message_dto(
    List<ContentChatMessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conversation_dto(
    List<ConversationDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_daily_token_usage_dto(
    List<DailyTokenUsageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_event_dto(List<EventDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_wiki_page_dto(
    List<WikiPageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ai_provider_config_dto(
    AiProviderConfigDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_conversation_dto(
    ConversationDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_wiki_page_dto(
    WikiPageDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_theme_prefs_dto(ThemePrefsDto self, SseSerializer serializer);

  @protected
  void sse_encode_tweet_fetch_dto(TweetFetchDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_wiki_page_dto(WikiPageDto self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__create_conversation(
    NativePortType port_,
    String? title,
    String? tag,
  ) => wasmModule.wire__crate__api__create_conversation(port_, title, tag);

  void wire__crate__api__fetch_tweet(NativePortType port_, String url) =>
      wasmModule.wire__crate__api__fetch_tweet(port_, url);

  void wire__crate__api__find_tweet_source_page(
    NativePortType port_,
    String url,
  ) => wasmModule.wire__crate__api__find_tweet_source_page(port_, url);

  void wire__crate__api__generate_content_chat(
    NativePortType port_,
    String content,
    JSAny messages,
  ) => wasmModule.wire__crate__api__generate_content_chat(
    port_,
    content,
    messages,
  );

  void wire__crate__api__generate_reply(
    NativePortType port_,
    String conversation_id,
    String? provider_type,
    String? memory_type,
    int? memory_window_size,
  ) => wasmModule.wire__crate__api__generate_reply(
    port_,
    conversation_id,
    provider_type,
    memory_type,
    memory_window_size,
  );

  void wire__crate__api__get_ai_provider(NativePortType port_) =>
      wasmModule.wire__crate__api__get_ai_provider(port_);

  void wire__crate__api__get_ai_provider_config(NativePortType port_) =>
      wasmModule.wire__crate__api__get_ai_provider_config(port_);

  void wire__crate__api__get_child_messages(
    NativePortType port_,
    String parent_id,
  ) => wasmModule.wire__crate__api__get_child_messages(port_, parent_id);

  void wire__crate__api__get_conversation(
    NativePortType port_,
    String conversation_id,
  ) => wasmModule.wire__crate__api__get_conversation(port_, conversation_id);

  void wire__crate__api__get_daily_token_usage(
    NativePortType port_,
    int days,
  ) => wasmModule.wire__crate__api__get_daily_token_usage(port_, days);

  void wire__crate__api__get_message_chain(
    NativePortType port_,
    String message_id,
  ) => wasmModule.wire__crate__api__get_message_chain(port_, message_id);

  void wire__crate__api__get_theme_prefs(NativePortType port_) =>
      wasmModule.wire__crate__api__get_theme_prefs(port_);

  void wire__crate__api__get_tweet_fetch_service(NativePortType port_) =>
      wasmModule.wire__crate__api__get_tweet_fetch_service(port_);

  void wire__crate__api__get_wiki_page(NativePortType port_, String slug) =>
      wasmModule.wire__crate__api__get_wiki_page(port_, slug);

  void wire__crate__api__init_bridge(
    NativePortType port_,
    String? database_path,
  ) => wasmModule.wire__crate__api__init_bridge(port_, database_path);

  void wire__crate__api__list_analyses(NativePortType port_) =>
      wasmModule.wire__crate__api__list_analyses(port_);

  void wire__crate__api__list_archived_conversations(NativePortType port_) =>
      wasmModule.wire__crate__api__list_archived_conversations(port_);

  void wire__crate__api__list_conversations(NativePortType port_) =>
      wasmModule.wire__crate__api__list_conversations(port_);

  void wire__crate__api__list_events(NativePortType port_) =>
      wasmModule.wire__crate__api__list_events(port_);

  void wire__crate__api__list_messages(
    NativePortType port_,
    String conversation_id,
  ) => wasmModule.wire__crate__api__list_messages(port_, conversation_id);

  void wire__crate__api__list_wiki_pages(NativePortType port_, String? kind) =>
      wasmModule.wire__crate__api__list_wiki_pages(port_, kind);

  void wire__crate__api__record_event(NativePortType port_, String raw_text) =>
      wasmModule.wire__crate__api__record_event(port_, raw_text);

  void wire__crate__api__rename_conversation(
    NativePortType port_,
    String conversation_id,
    String title,
  ) => wasmModule.wire__crate__api__rename_conversation(
    port_,
    conversation_id,
    title,
  );

  void wire__crate__api__save_tweet_page(
    NativePortType port_,
    String tweet_id,
    String text,
    String? title,
    String? author_name,
    String? screen_name,
  ) => wasmModule.wire__crate__api__save_tweet_page(
    port_,
    tweet_id,
    text,
    title,
    author_name,
    screen_name,
  );

  void wire__crate__api__send_message(
    NativePortType port_,
    String conversation_id,
    String role,
    String content,
    String? parent_message_id,
  ) => wasmModule.wire__crate__api__send_message(
    port_,
    conversation_id,
    role,
    content,
    parent_message_id,
  );

  void wire__crate__api__set_conversation_archived(
    NativePortType port_,
    String conversation_id,
    bool archived,
  ) => wasmModule.wire__crate__api__set_conversation_archived(
    port_,
    conversation_id,
    archived,
  );

  void wire__crate__api__trigger_analysis(NativePortType port_) =>
      wasmModule.wire__crate__api__trigger_analysis(port_);

  void wire__crate__api__update_ai_provider_config(
    NativePortType port_,
    String base_url,
    String model,
    String api_key,
  ) => wasmModule.wire__crate__api__update_ai_provider_config(
    port_,
    base_url,
    model,
    api_key,
  );

  void wire__crate__api__update_theme_prefs(
    NativePortType port_,
    String mode,
    String preset,
  ) => wasmModule.wire__crate__api__update_theme_prefs(port_, mode, preset);

  void wire__crate__api__update_tweet_fetch_service(
    NativePortType port_,
    String service,
  ) => wasmModule.wire__crate__api__update_tweet_fetch_service(port_, service);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__create_conversation(
    NativePortType port_,
    String? title,
    String? tag,
  );

  external void wire__crate__api__fetch_tweet(NativePortType port_, String url);

  external void wire__crate__api__find_tweet_source_page(
    NativePortType port_,
    String url,
  );

  external void wire__crate__api__generate_content_chat(
    NativePortType port_,
    String content,
    JSAny messages,
  );

  external void wire__crate__api__generate_reply(
    NativePortType port_,
    String conversation_id,
    String? provider_type,
    String? memory_type,
    int? memory_window_size,
  );

  external void wire__crate__api__get_ai_provider(NativePortType port_);

  external void wire__crate__api__get_ai_provider_config(NativePortType port_);

  external void wire__crate__api__get_child_messages(
    NativePortType port_,
    String parent_id,
  );

  external void wire__crate__api__get_conversation(
    NativePortType port_,
    String conversation_id,
  );

  external void wire__crate__api__get_daily_token_usage(
    NativePortType port_,
    int days,
  );

  external void wire__crate__api__get_message_chain(
    NativePortType port_,
    String message_id,
  );

  external void wire__crate__api__get_theme_prefs(NativePortType port_);

  external void wire__crate__api__get_tweet_fetch_service(NativePortType port_);

  external void wire__crate__api__get_wiki_page(
    NativePortType port_,
    String slug,
  );

  external void wire__crate__api__init_bridge(
    NativePortType port_,
    String? database_path,
  );

  external void wire__crate__api__list_analyses(NativePortType port_);

  external void wire__crate__api__list_archived_conversations(
    NativePortType port_,
  );

  external void wire__crate__api__list_conversations(NativePortType port_);

  external void wire__crate__api__list_events(NativePortType port_);

  external void wire__crate__api__list_messages(
    NativePortType port_,
    String conversation_id,
  );

  external void wire__crate__api__list_wiki_pages(
    NativePortType port_,
    String? kind,
  );

  external void wire__crate__api__record_event(
    NativePortType port_,
    String raw_text,
  );

  external void wire__crate__api__rename_conversation(
    NativePortType port_,
    String conversation_id,
    String title,
  );

  external void wire__crate__api__save_tweet_page(
    NativePortType port_,
    String tweet_id,
    String text,
    String? title,
    String? author_name,
    String? screen_name,
  );

  external void wire__crate__api__send_message(
    NativePortType port_,
    String conversation_id,
    String role,
    String content,
    String? parent_message_id,
  );

  external void wire__crate__api__set_conversation_archived(
    NativePortType port_,
    String conversation_id,
    bool archived,
  );

  external void wire__crate__api__trigger_analysis(NativePortType port_);

  external void wire__crate__api__update_ai_provider_config(
    NativePortType port_,
    String base_url,
    String model,
    String api_key,
  );

  external void wire__crate__api__update_theme_prefs(
    NativePortType port_,
    String mode,
    String preset,
  );

  external void wire__crate__api__update_tweet_fetch_service(
    NativePortType port_,
    String service,
  );
}
