// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.14.0-beta.2';

  @override
  int get rustContentHash => -1403263869;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'elsewhen',
        ioDirectory: '../target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiAddRule({required String content});

  Future<void> crateApiArchiveWikiPageChat({required String pageSlug});

  Future<ConversationDto> crateApiCreateConversation({
    String? title,
    String? tag,
  });

  Future<TodoDto> crateApiCreateTodo({
    required String title,
    String? dueAt,
    String? priority,
    String? relatedWikiSlug,
    String? note,
  });

  Future<void> crateApiDeleteAiProviderConfig({required String id});

  Future<void> crateApiDeleteRule({required String ruleId});

  Future<bool> crateApiDeleteTodo({required String id});

  Future<ConversationDto> crateApiEnsureWikiPageChat({
    required String pageSlug,
  });

  Future<ImportUrlDto> crateApiFetchImportUrl({required String url});

  Future<TweetFetchDto> crateApiFetchTweet({required String url});

  Future<WikiPageDto?> crateApiFindTweetSourcePage({required String url});

  Future<String> crateApiGenerateContentChat({
    required String content,
    required List<ContentChatMessageDto> messages,
  });

  Future<String> crateApiGenerateReply({
    required String conversationId,
    String? providerType,
    String? memoryType,
    int? memoryWindowSize,
  });

  Future<String?> crateApiGetAiProvider();

  Future<AiProviderConfigDto?> crateApiGetAiProviderConfig();

  Future<List<MessageDto>> crateApiGetChildMessages({required String parentId});

  Future<ConversationDto?> crateApiGetConversation({
    required String conversationId,
  });

  Future<List<DailyTokenUsageDto>> crateApiGetDailyTokenUsage({
    required int days,
  });

  Future<List<MessageDto>> crateApiGetMessageChain({required String messageId});

  Future<ThemePrefsDto> crateApiGetThemePrefs();

  Future<String> crateApiGetTweetFetchService();

  Future<WikiPageDto?> crateApiGetWikiPage({required String slug});

  Future<String> crateApiGuessImportKind({required String url});

  Future<String> crateApiInitBridge({String? databasePath});

  Future<List<AiProviderConfigDto>> crateApiListAiProviderConfigs();

  Future<List<AnalysisDto>> crateApiListAnalyses();

  Future<List<ConversationDto>> crateApiListArchivedConversations();

  Future<List<ConversationDto>> crateApiListConversations();

  Future<List<EventDto>> crateApiListEvents();

  Future<List<MessageDto>> crateApiListMessages({
    required String conversationId,
  });

  Future<List<RuleDto>> crateApiListRules();

  Future<List<TodoDto>> crateApiListTodos({String? status});

  Future<List<WikiPageDto>> crateApiListWikiPages({String? kind});

  Future<EventDto> crateApiRecordEvent({required String rawText});

  Future<void> crateApiRenameConversation({
    required String conversationId,
    required String title,
  });

  Future<String> crateApiSaveAiProviderConfig({
    required AiProviderConfigDto provider,
  });

  Future<WikiPageDto> crateApiSaveImportedPage({
    required String title,
    required String contentMd,
    required String sourceUrl,
    required String sourceKind,
    required List<String> tags,
  });

  Future<WikiPageDto> crateApiSaveTextPage({
    required String text,
    String? title,
    required List<String> tags,
  });

  Future<WikiPageDto> crateApiSaveTweetPage({
    required String tweetId,
    required String text,
    String? title,
    String? authorName,
    String? screenName,
  });

  Future<MessageDto> crateApiSendMessage({
    required String conversationId,
    required String role,
    required String content,
    String? parentMessageId,
  });

  Future<void> crateApiSetActiveAiProviderConfig({required String id});

  Future<void> crateApiSetConversationArchived({
    required String conversationId,
    required bool archived,
  });

  Future<String> crateApiTriggerAnalysis();

  Future<void> crateApiUpdateAiProviderConfig({
    required String baseUrl,
    required String model,
    required String apiKey,
  });

  Future<void> crateApiUpdateThemePrefs({
    required String mode,
    required String preset,
  });

  Future<void> crateApiUpdateTodo({
    required String id,
    required String title,
    String? note,
    String? priority,
    String? dueAt,
  });

  Future<void> crateApiUpdateTodoStatus({
    required String id,
    required String status,
  });

  Future<void> crateApiUpdateTweetFetchService({required String service});

  Future<WikiPageDto> crateApiUpdateWikiTags({
    required String slug,
    required List<String> tags,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiAddRule({required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(content);
          return wire.wire__crate__api__add_rule(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiAddRuleConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddRuleConstMeta =>
      const TaskConstMeta(debugName: "add_rule", argNames: ["content"]);

  @override
  Future<void> crateApiArchiveWikiPageChat({required String pageSlug}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(pageSlug);
          return wire.wire__crate__api__archive_wiki_page_chat(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiArchiveWikiPageChatConstMeta,
        argValues: [pageSlug],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiArchiveWikiPageChatConstMeta =>
      const TaskConstMeta(
        debugName: "archive_wiki_page_chat",
        argNames: ["pageSlug"],
      );

  @override
  Future<ConversationDto> crateApiCreateConversation({
    String? title,
    String? tag,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(title);
          var arg1 = cst_encode_opt_String(tag);
          return wire.wire__crate__api__create_conversation(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_conversation_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreateConversationConstMeta,
        argValues: [title, tag],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateConversationConstMeta => const TaskConstMeta(
    debugName: "create_conversation",
    argNames: ["title", "tag"],
  );

  @override
  Future<TodoDto> crateApiCreateTodo({
    required String title,
    String? dueAt,
    String? priority,
    String? relatedWikiSlug,
    String? note,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(title);
          var arg1 = cst_encode_opt_String(dueAt);
          var arg2 = cst_encode_opt_String(priority);
          var arg3 = cst_encode_opt_String(relatedWikiSlug);
          var arg4 = cst_encode_opt_String(note);
          return wire.wire__crate__api__create_todo(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_todo_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreateTodoConstMeta,
        argValues: [title, dueAt, priority, relatedWikiSlug, note],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateTodoConstMeta => const TaskConstMeta(
    debugName: "create_todo",
    argNames: ["title", "dueAt", "priority", "relatedWikiSlug", "note"],
  );

  @override
  Future<void> crateApiDeleteAiProviderConfig({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(id);
          return wire.wire__crate__api__delete_ai_provider_config(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteAiProviderConfigConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteAiProviderConfigConstMeta =>
      const TaskConstMeta(
        debugName: "delete_ai_provider_config",
        argNames: ["id"],
      );

  @override
  Future<void> crateApiDeleteRule({required String ruleId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(ruleId);
          return wire.wire__crate__api__delete_rule(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteRuleConstMeta,
        argValues: [ruleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteRuleConstMeta =>
      const TaskConstMeta(debugName: "delete_rule", argNames: ["ruleId"]);

  @override
  Future<bool> crateApiDeleteTodo({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(id);
          return wire.wire__crate__api__delete_todo(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_bool,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteTodoConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteTodoConstMeta =>
      const TaskConstMeta(debugName: "delete_todo", argNames: ["id"]);

  @override
  Future<ConversationDto> crateApiEnsureWikiPageChat({
    required String pageSlug,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(pageSlug);
          return wire.wire__crate__api__ensure_wiki_page_chat(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_conversation_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiEnsureWikiPageChatConstMeta,
        argValues: [pageSlug],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnsureWikiPageChatConstMeta => const TaskConstMeta(
    debugName: "ensure_wiki_page_chat",
    argNames: ["pageSlug"],
  );

  @override
  Future<ImportUrlDto> crateApiFetchImportUrl({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(url);
          return wire.wire__crate__api__fetch_import_url(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_import_url_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchImportUrlConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchImportUrlConstMeta =>
      const TaskConstMeta(debugName: "fetch_import_url", argNames: ["url"]);

  @override
  Future<TweetFetchDto> crateApiFetchTweet({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(url);
          return wire.wire__crate__api__fetch_tweet(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_tweet_fetch_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiFetchTweetConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFetchTweetConstMeta =>
      const TaskConstMeta(debugName: "fetch_tweet", argNames: ["url"]);

  @override
  Future<WikiPageDto?> crateApiFindTweetSourcePage({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(url);
          return wire.wire__crate__api__find_tweet_source_page(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_wiki_page_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiFindTweetSourcePageConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFindTweetSourcePageConstMeta =>
      const TaskConstMeta(
        debugName: "find_tweet_source_page",
        argNames: ["url"],
      );

  @override
  Future<String> crateApiGenerateContentChat({
    required String content,
    required List<ContentChatMessageDto> messages,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(content);
          var arg1 = cst_encode_list_content_chat_message_dto(messages);
          return wire.wire__crate__api__generate_content_chat(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGenerateContentChatConstMeta,
        argValues: [content, messages],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateContentChatConstMeta =>
      const TaskConstMeta(
        debugName: "generate_content_chat",
        argNames: ["content", "messages"],
      );

  @override
  Future<String> crateApiGenerateReply({
    required String conversationId,
    String? providerType,
    String? memoryType,
    int? memoryWindowSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(conversationId);
          var arg1 = cst_encode_opt_String(providerType);
          var arg2 = cst_encode_opt_String(memoryType);
          var arg3 = cst_encode_opt_box_autoadd_u_32(memoryWindowSize);
          return wire.wire__crate__api__generate_reply(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGenerateReplyConstMeta,
        argValues: [conversationId, providerType, memoryType, memoryWindowSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateReplyConstMeta => const TaskConstMeta(
    debugName: "generate_reply",
    argNames: [
      "conversationId",
      "providerType",
      "memoryType",
      "memoryWindowSize",
    ],
  );

  @override
  Future<String?> crateApiGetAiProvider() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__get_ai_provider(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetAiProviderConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAiProviderConstMeta =>
      const TaskConstMeta(debugName: "get_ai_provider", argNames: []);

  @override
  Future<AiProviderConfigDto?> crateApiGetAiProviderConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__get_ai_provider_config(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_ai_provider_config_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetAiProviderConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetAiProviderConfigConstMeta =>
      const TaskConstMeta(debugName: "get_ai_provider_config", argNames: []);

  @override
  Future<List<MessageDto>> crateApiGetChildMessages({
    required String parentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(parentId);
          return wire.wire__crate__api__get_child_messages(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_message_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetChildMessagesConstMeta,
        argValues: [parentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetChildMessagesConstMeta => const TaskConstMeta(
    debugName: "get_child_messages",
    argNames: ["parentId"],
  );

  @override
  Future<ConversationDto?> crateApiGetConversation({
    required String conversationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(conversationId);
          return wire.wire__crate__api__get_conversation(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_conversation_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetConversationConstMeta,
        argValues: [conversationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetConversationConstMeta => const TaskConstMeta(
    debugName: "get_conversation",
    argNames: ["conversationId"],
  );

  @override
  Future<List<DailyTokenUsageDto>> crateApiGetDailyTokenUsage({
    required int days,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_u_32(days);
          return wire.wire__crate__api__get_daily_token_usage(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_daily_token_usage_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetDailyTokenUsageConstMeta,
        argValues: [days],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDailyTokenUsageConstMeta => const TaskConstMeta(
    debugName: "get_daily_token_usage",
    argNames: ["days"],
  );

  @override
  Future<List<MessageDto>> crateApiGetMessageChain({
    required String messageId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(messageId);
          return wire.wire__crate__api__get_message_chain(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_message_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetMessageChainConstMeta,
        argValues: [messageId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMessageChainConstMeta => const TaskConstMeta(
    debugName: "get_message_chain",
    argNames: ["messageId"],
  );

  @override
  Future<ThemePrefsDto> crateApiGetThemePrefs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__get_theme_prefs(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_theme_prefs_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetThemePrefsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetThemePrefsConstMeta =>
      const TaskConstMeta(debugName: "get_theme_prefs", argNames: []);

  @override
  Future<String> crateApiGetTweetFetchService() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__get_tweet_fetch_service(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetTweetFetchServiceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTweetFetchServiceConstMeta =>
      const TaskConstMeta(debugName: "get_tweet_fetch_service", argNames: []);

  @override
  Future<WikiPageDto?> crateApiGetWikiPage({required String slug}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(slug);
          return wire.wire__crate__api__get_wiki_page(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_opt_box_autoadd_wiki_page_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetWikiPageConstMeta,
        argValues: [slug],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetWikiPageConstMeta =>
      const TaskConstMeta(debugName: "get_wiki_page", argNames: ["slug"]);

  @override
  Future<String> crateApiGuessImportKind({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(url);
          return wire.wire__crate__api__guess_import_kind(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiGuessImportKindConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGuessImportKindConstMeta =>
      const TaskConstMeta(debugName: "guess_import_kind", argNames: ["url"]);

  @override
  Future<String> crateApiInitBridge({String? databasePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(databasePath);
          return wire.wire__crate__api__init_bridge(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitBridgeConstMeta,
        argValues: [databasePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitBridgeConstMeta =>
      const TaskConstMeta(debugName: "init_bridge", argNames: ["databasePath"]);

  @override
  Future<List<AiProviderConfigDto>> crateApiListAiProviderConfigs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__list_ai_provider_configs(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_ai_provider_config_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListAiProviderConfigsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListAiProviderConfigsConstMeta =>
      const TaskConstMeta(debugName: "list_ai_provider_configs", argNames: []);

  @override
  Future<List<AnalysisDto>> crateApiListAnalyses() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__list_analyses(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_analysis_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListAnalysesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListAnalysesConstMeta =>
      const TaskConstMeta(debugName: "list_analyses", argNames: []);

  @override
  Future<List<ConversationDto>> crateApiListArchivedConversations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__list_archived_conversations(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_conversation_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListArchivedConversationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListArchivedConversationsConstMeta =>
      const TaskConstMeta(
        debugName: "list_archived_conversations",
        argNames: [],
      );

  @override
  Future<List<ConversationDto>> crateApiListConversations() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__list_conversations(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_conversation_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListConversationsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListConversationsConstMeta =>
      const TaskConstMeta(debugName: "list_conversations", argNames: []);

  @override
  Future<List<EventDto>> crateApiListEvents() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__list_events(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_event_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListEventsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListEventsConstMeta =>
      const TaskConstMeta(debugName: "list_events", argNames: []);

  @override
  Future<List<MessageDto>> crateApiListMessages({
    required String conversationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(conversationId);
          return wire.wire__crate__api__list_messages(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_message_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListMessagesConstMeta,
        argValues: [conversationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListMessagesConstMeta => const TaskConstMeta(
    debugName: "list_messages",
    argNames: ["conversationId"],
  );

  @override
  Future<List<RuleDto>> crateApiListRules() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__list_rules(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_rule_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListRulesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListRulesConstMeta =>
      const TaskConstMeta(debugName: "list_rules", argNames: []);

  @override
  Future<List<TodoDto>> crateApiListTodos({String? status}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(status);
          return wire.wire__crate__api__list_todos(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_todo_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListTodosConstMeta,
        argValues: [status],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListTodosConstMeta =>
      const TaskConstMeta(debugName: "list_todos", argNames: ["status"]);

  @override
  Future<List<WikiPageDto>> crateApiListWikiPages({String? kind}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_opt_String(kind);
          return wire.wire__crate__api__list_wiki_pages(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_wiki_page_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiListWikiPagesConstMeta,
        argValues: [kind],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListWikiPagesConstMeta =>
      const TaskConstMeta(debugName: "list_wiki_pages", argNames: ["kind"]);

  @override
  Future<EventDto> crateApiRecordEvent({required String rawText}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(rawText);
          return wire.wire__crate__api__record_event(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_event_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiRecordEventConstMeta,
        argValues: [rawText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRecordEventConstMeta =>
      const TaskConstMeta(debugName: "record_event", argNames: ["rawText"]);

  @override
  Future<void> crateApiRenameConversation({
    required String conversationId,
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(conversationId);
          var arg1 = cst_encode_String(title);
          return wire.wire__crate__api__rename_conversation(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiRenameConversationConstMeta,
        argValues: [conversationId, title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRenameConversationConstMeta => const TaskConstMeta(
    debugName: "rename_conversation",
    argNames: ["conversationId", "title"],
  );

  @override
  Future<String> crateApiSaveAiProviderConfig({
    required AiProviderConfigDto provider,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_box_autoadd_ai_provider_config_dto(provider);
          return wire.wire__crate__api__save_ai_provider_config(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiSaveAiProviderConfigConstMeta,
        argValues: [provider],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveAiProviderConfigConstMeta =>
      const TaskConstMeta(
        debugName: "save_ai_provider_config",
        argNames: ["provider"],
      );

  @override
  Future<WikiPageDto> crateApiSaveImportedPage({
    required String title,
    required String contentMd,
    required String sourceUrl,
    required String sourceKind,
    required List<String> tags,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(title);
          var arg1 = cst_encode_String(contentMd);
          var arg2 = cst_encode_String(sourceUrl);
          var arg3 = cst_encode_String(sourceKind);
          var arg4 = cst_encode_list_String(tags);
          return wire.wire__crate__api__save_imported_page(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_wiki_page_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiSaveImportedPageConstMeta,
        argValues: [title, contentMd, sourceUrl, sourceKind, tags],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveImportedPageConstMeta => const TaskConstMeta(
    debugName: "save_imported_page",
    argNames: ["title", "contentMd", "sourceUrl", "sourceKind", "tags"],
  );

  @override
  Future<WikiPageDto> crateApiSaveTextPage({
    required String text,
    String? title,
    required List<String> tags,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(text);
          var arg1 = cst_encode_opt_String(title);
          var arg2 = cst_encode_list_String(tags);
          return wire.wire__crate__api__save_text_page(port_, arg0, arg1, arg2);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_wiki_page_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiSaveTextPageConstMeta,
        argValues: [text, title, tags],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveTextPageConstMeta => const TaskConstMeta(
    debugName: "save_text_page",
    argNames: ["text", "title", "tags"],
  );

  @override
  Future<WikiPageDto> crateApiSaveTweetPage({
    required String tweetId,
    required String text,
    String? title,
    String? authorName,
    String? screenName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(tweetId);
          var arg1 = cst_encode_String(text);
          var arg2 = cst_encode_opt_String(title);
          var arg3 = cst_encode_opt_String(authorName);
          var arg4 = cst_encode_opt_String(screenName);
          return wire.wire__crate__api__save_tweet_page(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_wiki_page_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiSaveTweetPageConstMeta,
        argValues: [tweetId, text, title, authorName, screenName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveTweetPageConstMeta => const TaskConstMeta(
    debugName: "save_tweet_page",
    argNames: ["tweetId", "text", "title", "authorName", "screenName"],
  );

  @override
  Future<MessageDto> crateApiSendMessage({
    required String conversationId,
    required String role,
    required String content,
    String? parentMessageId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(conversationId);
          var arg1 = cst_encode_String(role);
          var arg2 = cst_encode_String(content);
          var arg3 = cst_encode_opt_String(parentMessageId);
          return wire.wire__crate__api__send_message(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_message_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiSendMessageConstMeta,
        argValues: [conversationId, role, content, parentMessageId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendMessageConstMeta => const TaskConstMeta(
    debugName: "send_message",
    argNames: ["conversationId", "role", "content", "parentMessageId"],
  );

  @override
  Future<void> crateApiSetActiveAiProviderConfig({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(id);
          return wire.wire__crate__api__set_active_ai_provider_config(
            port_,
            arg0,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetActiveAiProviderConfigConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetActiveAiProviderConfigConstMeta =>
      const TaskConstMeta(
        debugName: "set_active_ai_provider_config",
        argNames: ["id"],
      );

  @override
  Future<void> crateApiSetConversationArchived({
    required String conversationId,
    required bool archived,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(conversationId);
          var arg1 = cst_encode_bool(archived);
          return wire.wire__crate__api__set_conversation_archived(
            port_,
            arg0,
            arg1,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetConversationArchivedConstMeta,
        argValues: [conversationId, archived],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetConversationArchivedConstMeta =>
      const TaskConstMeta(
        debugName: "set_conversation_archived",
        argNames: ["conversationId", "archived"],
      );

  @override
  Future<String> crateApiTriggerAnalysis() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          return wire.wire__crate__api__trigger_analysis(port_);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiTriggerAnalysisConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTriggerAnalysisConstMeta =>
      const TaskConstMeta(debugName: "trigger_analysis", argNames: []);

  @override
  Future<void> crateApiUpdateAiProviderConfig({
    required String baseUrl,
    required String model,
    required String apiKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(baseUrl);
          var arg1 = cst_encode_String(model);
          var arg2 = cst_encode_String(apiKey);
          return wire.wire__crate__api__update_ai_provider_config(
            port_,
            arg0,
            arg1,
            arg2,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateAiProviderConfigConstMeta,
        argValues: [baseUrl, model, apiKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateAiProviderConfigConstMeta =>
      const TaskConstMeta(
        debugName: "update_ai_provider_config",
        argNames: ["baseUrl", "model", "apiKey"],
      );

  @override
  Future<void> crateApiUpdateThemePrefs({
    required String mode,
    required String preset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(mode);
          var arg1 = cst_encode_String(preset);
          return wire.wire__crate__api__update_theme_prefs(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateThemePrefsConstMeta,
        argValues: [mode, preset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateThemePrefsConstMeta => const TaskConstMeta(
    debugName: "update_theme_prefs",
    argNames: ["mode", "preset"],
  );

  @override
  Future<void> crateApiUpdateTodo({
    required String id,
    required String title,
    String? note,
    String? priority,
    String? dueAt,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(id);
          var arg1 = cst_encode_String(title);
          var arg2 = cst_encode_opt_String(note);
          var arg3 = cst_encode_opt_String(priority);
          var arg4 = cst_encode_opt_String(dueAt);
          return wire.wire__crate__api__update_todo(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateTodoConstMeta,
        argValues: [id, title, note, priority, dueAt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateTodoConstMeta => const TaskConstMeta(
    debugName: "update_todo",
    argNames: ["id", "title", "note", "priority", "dueAt"],
  );

  @override
  Future<void> crateApiUpdateTodoStatus({
    required String id,
    required String status,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(id);
          var arg1 = cst_encode_String(status);
          return wire.wire__crate__api__update_todo_status(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateTodoStatusConstMeta,
        argValues: [id, status],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateTodoStatusConstMeta => const TaskConstMeta(
    debugName: "update_todo_status",
    argNames: ["id", "status"],
  );

  @override
  Future<void> crateApiUpdateTweetFetchService({required String service}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(service);
          return wire.wire__crate__api__update_tweet_fetch_service(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_unit,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateTweetFetchServiceConstMeta,
        argValues: [service],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateTweetFetchServiceConstMeta =>
      const TaskConstMeta(
        debugName: "update_tweet_fetch_service",
        argNames: ["service"],
      );

  @override
  Future<WikiPageDto> crateApiUpdateWikiTags({
    required String slug,
    required List<String> tags,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(slug);
          var arg1 = cst_encode_list_String(tags);
          return wire.wire__crate__api__update_wiki_tags(port_, arg0, arg1);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_wiki_page_dto,
          decodeErrorData: dco_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateWikiTagsConstMeta,
        argValues: [slug, tags],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateWikiTagsConstMeta => const TaskConstMeta(
    debugName: "update_wiki_tags",
    argNames: ["slug", "tags"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(dcoDecodeString(raw));
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeString(raw);
  }

  @protected
  AiProviderConfigDto dco_decode_ai_provider_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return AiProviderConfigDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      providerType: dco_decode_String(arr[2]),
      baseUrl: dco_decode_String(arr[3]),
      model: dco_decode_String(arr[4]),
      apiKeySource: dco_decode_String(arr[5]),
      apiKey: dco_decode_String(arr[6]),
      isActive: dco_decode_bool(arr[7]),
      temperature: dco_decode_f_64(arr[8]),
      maxTokens: dco_decode_opt_box_autoadd_i_64(arr[9]),
    );
  }

  @protected
  AnalysisDto dco_decode_analysis_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AnalysisDto(
      eventType: dco_decode_String(arr[0]),
      confidence: dco_decode_f_64(arr[1]),
      summary: dco_decode_String(arr[2]),
      clarifications: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AiProviderConfigDto dco_decode_box_autoadd_ai_provider_config_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ai_provider_config_dto(raw);
  }

  @protected
  ConversationDto dco_decode_box_autoadd_conversation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_conversation_dto(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_32(raw);
  }

  @protected
  WikiPageDto dco_decode_box_autoadd_wiki_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_wiki_page_dto(raw);
  }

  @protected
  ContentChatMessageDto dco_decode_content_chat_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ContentChatMessageDto(
      role: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
    );
  }

  @protected
  ConversationDto dco_decode_conversation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ConversationDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_opt_String(arr[1]),
      tag: dco_decode_opt_String(arr[2]),
      createdAt: dco_decode_String(arr[3]),
      updatedAt: dco_decode_String(arr[4]),
      messageCount: dco_decode_i_32(arr[5]),
      lastMessagePreview: dco_decode_opt_String(arr[6]),
      archived: dco_decode_bool(arr[7]),
      wikiPageSlug: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  DailyTokenUsageDto dco_decode_daily_token_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return DailyTokenUsageDto(
      date: dco_decode_String(arr[0]),
      promptTokens: dco_decode_i_64(arr[1]),
      completionTokens: dco_decode_i_64(arr[2]),
      totalTokens: dco_decode_i_64(arr[3]),
      callCount: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  EventDto dco_decode_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EventDto(
      id: dco_decode_String(arr[0]),
      rawText: dco_decode_String(arr[1]),
      recordedAt: dco_decode_String(arr[2]),
      occurredAt: dco_decode_String(arr[3]),
      source: dco_decode_String(arr[4]),
      status: dco_decode_String(arr[5]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImportUrlDto dco_decode_import_url_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ImportUrlDto(
      sourceUrl: dco_decode_String(arr[0]),
      sourceKind: dco_decode_String(arr[1]),
      title: dco_decode_opt_String(arr[2]),
      contentMd: dco_decode_String(arr[3]),
      authorName: dco_decode_opt_String(arr[4]),
      screenName: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_String).toList();
  }

  @protected
  List<AiProviderConfigDto> dco_decode_list_ai_provider_config_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_ai_provider_config_dto).toList();
  }

  @protected
  List<AnalysisDto> dco_decode_list_analysis_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_analysis_dto).toList();
  }

  @protected
  List<ContentChatMessageDto> dco_decode_list_content_chat_message_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_content_chat_message_dto).toList();
  }

  @protected
  List<ConversationDto> dco_decode_list_conversation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_conversation_dto).toList();
  }

  @protected
  List<DailyTokenUsageDto> dco_decode_list_daily_token_usage_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_daily_token_usage_dto).toList();
  }

  @protected
  List<EventDto> dco_decode_list_event_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_event_dto).toList();
  }

  @protected
  List<MessageDto> dco_decode_list_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_message_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RuleDto> dco_decode_list_rule_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_rule_dto).toList();
  }

  @protected
  List<TodoDto> dco_decode_list_todo_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_todo_dto).toList();
  }

  @protected
  List<WikiPageDto> dco_decode_list_wiki_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeList(raw).map(dco_decode_wiki_page_dto).toList();
  }

  @protected
  MessageDto dco_decode_message_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MessageDto(
      id: dco_decode_String(arr[0]),
      conversationId: dco_decode_String(arr[1]),
      parentMessageId: dco_decode_opt_String(arr[2]),
      role: dco_decode_String(arr[3]),
      content: dco_decode_String(arr[4]),
      createdAt: dco_decode_String(arr[5]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AiProviderConfigDto? dco_decode_opt_box_autoadd_ai_provider_config_dto(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_ai_provider_config_dto(raw);
  }

  @protected
  ConversationDto? dco_decode_opt_box_autoadd_conversation_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_conversation_dto(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  WikiPageDto? dco_decode_opt_box_autoadd_wiki_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_wiki_page_dto(raw);
  }

  @protected
  RuleDto dco_decode_rule_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RuleDto(
      id: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
      status: dco_decode_String(arr[2]),
      createdAt: dco_decode_String(arr[3]),
    );
  }

  @protected
  ThemePrefsDto dco_decode_theme_prefs_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ThemePrefsDto(
      mode: dco_decode_String(arr[0]),
      preset: dco_decode_String(arr[1]),
    );
  }

  @protected
  TodoDto dco_decode_todo_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return TodoDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      status: dco_decode_String(arr[2]),
      priority: dco_decode_String(arr[3]),
      dueAt: dco_decode_opt_String(arr[4]),
      relatedEventId: dco_decode_opt_String(arr[5]),
      relatedWikiSlug: dco_decode_opt_String(arr[6]),
      note: dco_decode_opt_String(arr[7]),
      createdAt: dco_decode_String(arr[8]),
      updatedAt: dco_decode_String(arr[9]),
    );
  }

  @protected
  TweetFetchDto dco_decode_tweet_fetch_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TweetFetchDto(
      tweetId: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      text: dco_decode_String(arr[2]),
      title: dco_decode_opt_String(arr[3]),
      authorName: dco_decode_opt_String(arr[4]),
      screenName: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodePrimitiveInt(raw);
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WikiPageDto dco_decode_wiki_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = dcoDecodeList(raw);
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return WikiPageDto(
      id: dco_decode_String(arr[0]),
      slug: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
      title: dco_decode_String(arr[3]),
      summary: dco_decode_String(arr[4]),
      contentMd: dco_decode_String(arr[5]),
      tags: dco_decode_list_String(arr[6]),
      sourceEventIds: dco_decode_list_String(arr[7]),
      evidenceCount: dco_decode_i_64(arr[8]),
      firstSeenAt: dco_decode_String(arr[9]),
      lastSeenAt: dco_decode_String(arr[10]),
      status: dco_decode_String(arr[11]),
      createdAt: dco_decode_String(arr[12]),
      updatedAt: dco_decode_String(arr[13]),
      sourceUrl: dco_decode_opt_String(arr[14]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AiProviderConfigDto sse_decode_ai_provider_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_providerType = sse_decode_String(deserializer);
    var var_baseUrl = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_apiKeySource = sse_decode_String(deserializer);
    var var_apiKey = sse_decode_String(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    var var_temperature = sse_decode_f_64(deserializer);
    var var_maxTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    return AiProviderConfigDto(
      id: var_id,
      name: var_name,
      providerType: var_providerType,
      baseUrl: var_baseUrl,
      model: var_model,
      apiKeySource: var_apiKeySource,
      apiKey: var_apiKey,
      isActive: var_isActive,
      temperature: var_temperature,
      maxTokens: var_maxTokens,
    );
  }

  @protected
  AnalysisDto sse_decode_analysis_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventType = sse_decode_String(deserializer);
    var var_confidence = sse_decode_f_64(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_clarifications = sse_decode_list_String(deserializer);
    return AnalysisDto(
      eventType: var_eventType,
      confidence: var_confidence,
      summary: var_summary,
      clarifications: var_clarifications,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AiProviderConfigDto sse_decode_box_autoadd_ai_provider_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ai_provider_config_dto(deserializer));
  }

  @protected
  ConversationDto sse_decode_box_autoadd_conversation_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_conversation_dto(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  WikiPageDto sse_decode_box_autoadd_wiki_page_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_wiki_page_dto(deserializer));
  }

  @protected
  ContentChatMessageDto sse_decode_content_chat_message_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    return ContentChatMessageDto(role: var_role, content: var_content);
  }

  @protected
  ConversationDto sse_decode_conversation_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_tag = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_messageCount = sse_decode_i_32(deserializer);
    var var_lastMessagePreview = sse_decode_opt_String(deserializer);
    var var_archived = sse_decode_bool(deserializer);
    var var_wikiPageSlug = sse_decode_opt_String(deserializer);
    return ConversationDto(
      id: var_id,
      title: var_title,
      tag: var_tag,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      messageCount: var_messageCount,
      lastMessagePreview: var_lastMessagePreview,
      archived: var_archived,
      wikiPageSlug: var_wikiPageSlug,
    );
  }

  @protected
  DailyTokenUsageDto sse_decode_daily_token_usage_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_date = sse_decode_String(deserializer);
    var var_promptTokens = sse_decode_i_64(deserializer);
    var var_completionTokens = sse_decode_i_64(deserializer);
    var var_totalTokens = sse_decode_i_64(deserializer);
    var var_callCount = sse_decode_i_64(deserializer);
    return DailyTokenUsageDto(
      date: var_date,
      promptTokens: var_promptTokens,
      completionTokens: var_completionTokens,
      totalTokens: var_totalTokens,
      callCount: var_callCount,
    );
  }

  @protected
  EventDto sse_decode_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_rawText = sse_decode_String(deserializer);
    var var_recordedAt = sse_decode_String(deserializer);
    var var_occurredAt = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return EventDto(
      id: var_id,
      rawText: var_rawText,
      recordedAt: var_recordedAt,
      occurredAt: var_occurredAt,
      source: var_source,
      status: var_status,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImportUrlDto sse_decode_import_url_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceUrl = sse_decode_String(deserializer);
    var var_sourceKind = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_contentMd = sse_decode_String(deserializer);
    var var_authorName = sse_decode_opt_String(deserializer);
    var var_screenName = sse_decode_opt_String(deserializer);
    return ImportUrlDto(
      sourceUrl: var_sourceUrl,
      sourceKind: var_sourceKind,
      title: var_title,
      contentMd: var_contentMd,
      authorName: var_authorName,
      screenName: var_screenName,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AiProviderConfigDto> sse_decode_list_ai_provider_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AiProviderConfigDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ai_provider_config_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<AnalysisDto> sse_decode_list_analysis_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnalysisDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_analysis_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ContentChatMessageDto> sse_decode_list_content_chat_message_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ContentChatMessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_content_chat_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConversationDto> sse_decode_list_conversation_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConversationDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conversation_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DailyTokenUsageDto> sse_decode_list_daily_token_usage_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DailyTokenUsageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_daily_token_usage_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<EventDto> sse_decode_list_event_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EventDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_event_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<MessageDto> sse_decode_list_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MessageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_message_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RuleDto> sse_decode_list_rule_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RuleDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rule_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<TodoDto> sse_decode_list_todo_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TodoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_todo_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<WikiPageDto> sse_decode_list_wiki_page_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WikiPageDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_wiki_page_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MessageDto sse_decode_message_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_conversationId = sse_decode_String(deserializer);
    var var_parentMessageId = sse_decode_opt_String(deserializer);
    var var_role = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return MessageDto(
      id: var_id,
      conversationId: var_conversationId,
      parentMessageId: var_parentMessageId,
      role: var_role,
      content: var_content,
      createdAt: var_createdAt,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AiProviderConfigDto? sse_decode_opt_box_autoadd_ai_provider_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ai_provider_config_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ConversationDto? sse_decode_opt_box_autoadd_conversation_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_conversation_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WikiPageDto? sse_decode_opt_box_autoadd_wiki_page_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_wiki_page_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RuleDto sse_decode_rule_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    return RuleDto(
      id: var_id,
      content: var_content,
      status: var_status,
      createdAt: var_createdAt,
    );
  }

  @protected
  ThemePrefsDto sse_decode_theme_prefs_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_String(deserializer);
    var var_preset = sse_decode_String(deserializer);
    return ThemePrefsDto(mode: var_mode, preset: var_preset);
  }

  @protected
  TodoDto sse_decode_todo_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_priority = sse_decode_String(deserializer);
    var var_dueAt = sse_decode_opt_String(deserializer);
    var var_relatedEventId = sse_decode_opt_String(deserializer);
    var var_relatedWikiSlug = sse_decode_opt_String(deserializer);
    var var_note = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return TodoDto(
      id: var_id,
      title: var_title,
      status: var_status,
      priority: var_priority,
      dueAt: var_dueAt,
      relatedEventId: var_relatedEventId,
      relatedWikiSlug: var_relatedWikiSlug,
      note: var_note,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  TweetFetchDto sse_decode_tweet_fetch_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tweetId = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_authorName = sse_decode_opt_String(deserializer);
    var var_screenName = sse_decode_opt_String(deserializer);
    return TweetFetchDto(
      tweetId: var_tweetId,
      url: var_url,
      text: var_text,
      title: var_title,
      authorName: var_authorName,
      screenName: var_screenName,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WikiPageDto sse_decode_wiki_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_slug = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_summary = sse_decode_String(deserializer);
    var var_contentMd = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_sourceEventIds = sse_decode_list_String(deserializer);
    var var_evidenceCount = sse_decode_i_64(deserializer);
    var var_firstSeenAt = sse_decode_String(deserializer);
    var var_lastSeenAt = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_sourceUrl = sse_decode_opt_String(deserializer);
    return WikiPageDto(
      id: var_id,
      slug: var_slug,
      kind: var_kind,
      title: var_title,
      summary: var_summary,
      contentMd: var_contentMd,
      tags: var_tags,
      sourceEventIds: var_sourceEventIds,
      evidenceCount: var_evidenceCount,
      firstSeenAt: var_firstSeenAt,
      lastSeenAt: var_lastSeenAt,
      status: var_status,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      sourceUrl: var_sourceUrl,
    );
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ai_provider_config_dto(
    AiProviderConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.providerType, serializer);
    sse_encode_String(self.baseUrl, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.apiKeySource, serializer);
    sse_encode_String(self.apiKey, serializer);
    sse_encode_bool(self.isActive, serializer);
    sse_encode_f_64(self.temperature, serializer);
    sse_encode_opt_box_autoadd_i_64(self.maxTokens, serializer);
  }

  @protected
  void sse_encode_analysis_dto(AnalysisDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventType, serializer);
    sse_encode_f_64(self.confidence, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_list_String(self.clarifications, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ai_provider_config_dto(
    AiProviderConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ai_provider_config_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_conversation_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_wiki_page_dto(
    WikiPageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_wiki_page_dto(self, serializer);
  }

  @protected
  void sse_encode_content_chat_message_dto(
    ContentChatMessageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
  }

  @protected
  void sse_encode_conversation_dto(
    ConversationDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.tag, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_i_32(self.messageCount, serializer);
    sse_encode_opt_String(self.lastMessagePreview, serializer);
    sse_encode_bool(self.archived, serializer);
    sse_encode_opt_String(self.wikiPageSlug, serializer);
  }

  @protected
  void sse_encode_daily_token_usage_dto(
    DailyTokenUsageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.date, serializer);
    sse_encode_i_64(self.promptTokens, serializer);
    sse_encode_i_64(self.completionTokens, serializer);
    sse_encode_i_64(self.totalTokens, serializer);
    sse_encode_i_64(self.callCount, serializer);
  }

  @protected
  void sse_encode_event_dto(EventDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.rawText, serializer);
    sse_encode_String(self.recordedAt, serializer);
    sse_encode_String(self.occurredAt, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_import_url_dto(ImportUrlDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourceUrl, serializer);
    sse_encode_String(self.sourceKind, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_String(self.contentMd, serializer);
    sse_encode_opt_String(self.authorName, serializer);
    sse_encode_opt_String(self.screenName, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ai_provider_config_dto(
    List<AiProviderConfigDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ai_provider_config_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_analysis_dto(
    List<AnalysisDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_analysis_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_content_chat_message_dto(
    List<ContentChatMessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_content_chat_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conversation_dto(
    List<ConversationDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conversation_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_daily_token_usage_dto(
    List<DailyTokenUsageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_daily_token_usage_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_event_dto(
    List<EventDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_event_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_message_dto(
    List<MessageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_message_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rule_dto(List<RuleDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rule_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_todo_dto(List<TodoDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_todo_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_wiki_page_dto(
    List<WikiPageDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_wiki_page_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_message_dto(MessageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.conversationId, serializer);
    sse_encode_opt_String(self.parentMessageId, serializer);
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ai_provider_config_dto(
    AiProviderConfigDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ai_provider_config_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_conversation_dto(
    ConversationDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_conversation_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_wiki_page_dto(
    WikiPageDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_wiki_page_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_rule_dto(RuleDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.createdAt, serializer);
  }

  @protected
  void sse_encode_theme_prefs_dto(
    ThemePrefsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mode, serializer);
    sse_encode_String(self.preset, serializer);
  }

  @protected
  void sse_encode_todo_dto(TodoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.priority, serializer);
    sse_encode_opt_String(self.dueAt, serializer);
    sse_encode_opt_String(self.relatedEventId, serializer);
    sse_encode_opt_String(self.relatedWikiSlug, serializer);
    sse_encode_opt_String(self.note, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_tweet_fetch_dto(
    TweetFetchDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tweetId, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.authorName, serializer);
    sse_encode_opt_String(self.screenName, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wiki_page_dto(WikiPageDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.slug, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.summary, serializer);
    sse_encode_String(self.contentMd, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_list_String(self.sourceEventIds, serializer);
    sse_encode_i_64(self.evidenceCount, serializer);
    sse_encode_String(self.firstSeenAt, serializer);
    sse_encode_String(self.lastSeenAt, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_opt_String(self.sourceUrl, serializer);
  }
}
